Repository woowacourse-teams/2024-code-zap, pull requests merged in 2024-08, with the labels that each got.

#217 Member 도메인 생성
  backend/src/main/java/codezap/member/domain/Member.java
  backend/src/main/java/codezap/member/repository/MemberRepository.java
Labels: feature, zap, BE

#220 [REFACTOR] 무중단 배포 파이프라인 구성
  .github/workflows/backend_cd.yml
Labels: refactor, BE

#227 Text 컴포넌트에서 Heading 컴포넌트 분리 및 스타일토큰 적용
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Heading/Heading.style.ts
  frontend/src/components/Heading/Heading.tsx
  frontend/src/components/SelectList/SelectList.tsx
  frontend/src/components/TemplateItem/TemplateItem.tsx
  frontend/src/components/Text/Text.style.ts
  frontend/src/components/Text/Text.tsx
  frontend/src/components/Text/style.ts
  frontend/src/components/index.ts
  frontend/src/pages/TemplateListPage/TemplateListPage.tsx
  frontend/src/pages/TemplatePage/TemplatePage.tsx
Labels: FE, refactor

#228 Header 컴포넌트 새로운 디자인으로 리팩토링
  frontend/src/assets/images/index.ts
  frontend/src/assets/images/logo.png
  frontend/src/assets/images/logo_24x24.png
  frontend/src/assets/images/newTemplate.png
  frontend/src/assets/images/newTemplate_12x12.png
  frontend/src/assets/images/userMenu_38x38.png
  frontend/src/components/Header/Header.style.ts
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/style.ts
Labels: FE, refactor

#234 레이아웃에 헤더 높이 만큼 padding-top 적용, Input style rem값 변경
  frontend/src/components/Input/Input.style.ts
  frontend/src/components/Input/Input.tsx
  frontend/src/components/Layout/Layout.style.ts
  frontend/src/components/Layout/Layout.tsx
  frontend/src/pages/TemplateEditPage/TemplateEditPage.tsx
  frontend/src/pages/TemplateListPage/TemplateListPage.tsx
  frontend/src/pages/TemplatePage/TemplatePage.tsx
  frontend/src/pages/TemplateUploadPage/TemplateUploadPage.tsx
Labels: FE, refactor

#231 템플릿 CRUD 리팩토링
  backend/src/main/java/codezap/category/service/CategoryService.java
  backend/src/main/java/codezap/template/domain/Template.java
  backend/src/main/java/codezap/template/domain/TemplateTag.java
  backend/src/main/java/codezap/template/dto/request/UpdateTemplateRequest.java
  backend/src/main/java/codezap/template/dto/response/FindTagByIdResponse.java
  backend/src/main/java/codezap/template/dto/response/FindTemplateByIdResponse.java
  backend/src/main/java/codezap/template/repository/TagRepository.java
  backend/src/main/java/codezap/template/repository/TemplateTagRepository.java
  backend/src/main/java/codezap/template/service/TemplateService.java
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
  backend/src/test/java/codezap/template/repository/SnippetRepositoryTest.java
  backend/src/test/java/codezap/template/service/TemplateServiceTest.java
  backend/src/test/resources/clear.sql
Labels: feature, BE

#239 템플릿 API 문서 수정
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
Labels: documentation, BE

#249 제약 조건 추가 및 리팩토링
  backend/src/main/java/codezap/category/controller/CategoryController.java
  backend/src/main/java/codezap/category/dto/request/CreateCategoryRequest.java
  backend/src/main/java/codezap/category/dto/request/UpdateCategoryRequest.java
  backend/src/main/java/codezap/category/service/CategoryService.java
  backend/src/main/java/codezap/global/cors/WebCorsConfiguration.java
  backend/src/main/java/codezap/global/validation/ValidationGroups.java
  backend/src/main/java/codezap/global/validation/ValidationSequence.java
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
  backend/src/main/java/codezap/template/controller/TemplateController.java
  backend/src/main/java/codezap/template/domain/Template.java
  backend/src/main/java/codezap/template/dto/request/CreateSnippetRequest.java
  backend/src/main/java/codezap/template/dto/request/CreateTemplateRequest.java
  backend/src/main/java/codezap/template/dto/request/UpdateSnippetRequest.java
  backend/src/main/java/codezap/template/dto/request/UpdateTemplateRequest.java
  backend/src/main/java/codezap/template/dto/response/FindAllSnippetByTemplateResponse.java
  backend/src/main/java/codezap/template/dto/response/FindTagByIdResponse.java
  backend/src/main/java/codezap/template/dto/response/FindTemplateByIdResponse.java
  backend/src/main/java/codezap/template/dto/response/FindThumbnailSnippetResponse.java
  backend/src/main/java/codezap/template/service/TemplateService.java
  backend/src/test/java/codezap/category/controller/CategoryControllerTest.java
  backend/src/test/java/codezap/category/service/CategoryServiceTest.java
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
  backend/src/test/java/codezap/template/repository/SnippetRepositoryTest.java
  backend/src/test/java/codezap/template/service/TemplateServiceTest.java
Labels: feature, documentation, BE

#248 Input 컴포넌트 사이즈 추가
  frontend/src/components/Input/Input.stories.tsx
  frontend/src/components/Input/Input.style.ts
  frontend/src/components/Input/Input.tsx
Labels: FE, refactor, zap

#253 README 서비스 소개 업데이트
  README.md
Labels: documentation, FE, BE

#255 CD jar 파일 다운로드 위치 변경
  .github/workflows/backend_cd.yml
Labels: refactor, BE

#235 Logback 구성 및 환경별 설정
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/logback-spring.xml
  backend/src/main/resources/logger/console/console-appender.xml
  backend/src/main/resources/logger/console/parameter-appender.xml
  backend/src/main/resources/logger/file/error-appender.xml
  backend/src/main/resources/logger/file/info-appender.xml
  backend/src/main/resources/logger/file/warn-appender.xml
  backend/src/main/resources/logger/logback-spring-dev.xml
  backend/src/main/resources/logger/logback-spring-local.xml
  backend/src/main/resources/logger/logback-spring-prod.xml
Labels: zap, BE

#245 스프링단 로그 추가
  backend/src/main/java/codezap/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/codezap/global/logger/MDCFilter.java
  backend/src/main/java/codezap/global/logger/MethodExecutionTimeAspect.java
  backend/src/main/java/codezap/global/logger/RequestResponseLogger.java
Labels: feature, BE

#261 frontend_cd 빌드 환경에서 환경변수 파일 설정
  .github/workflows/frontend_cd.yml
Labels: bug, FE, zap

#269 CI/CD build 실행 self-hosted-runner에서 하도록 변경
  .github/workflows/backend_cd.yml
  .github/workflows/backend_ci.yml
Labels: refactor, BE

#263 각종 슬랙 알람을 위한 워크플로 작성
  .github/workflows/ci_cd_fail_notification.yml
  .github/workflows/pr_notification.yml
  .github/workflows/review_notification.yml
Labels: documentation, FE, zap, BE

#258 Button 컴포넌트 리팩토링(디자인 반영)
  frontend/src/components/Button/Button.stories.tsx
  frontend/src/components/Button/Button.style.ts
  frontend/src/components/Button/Button.tsx
  frontend/src/components/Button/style.ts
  frontend/src/components/Header/Header.style.ts
  frontend/src/components/Header/Header.tsx
Labels: FE, refactor

#276 로그 및 액션 파일 최신화를 위한 PR
  .github/workflows/backend_cd.yml
  .github/workflows/backend_ci.yml
  README.md
  backend/.gitignore
  backend/build.gradle
  backend/docker/docker-compose.yml
  backend/src/main/java/codezap/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/codezap/global/logger/MDCFilter.java
  backend/src/main/java/codezap/global/logger/MethodExecutionTimeAspect.java
  backend/src/main/java/codezap/global/logger/RequestResponseLogger.java
  backend/src/main/java/codezap/member/domain/Member.java
  backend/src/main/java/codezap/member/repository/MemberRepository.java
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/logback-spring.xml
  backend/src/main/resources/logger/console/console-appender.xml
  backend/src/main/resources/logger/console/parameter-appender.xml
  backend/src/main/resources/logger/file/error-appender.xml
  backend/src/main/resources/logger/file/info-appender.xml
  backend/src/main/resources/logger/file/warn-appender.xml
  backend/src/main/resources/logger/logback-spring-dev.xml
  backend/src/main/resources/logger/logback-spring-local.xml
  backend/src/main/resources/logger/logback-spring-prod.xml
Labels: feature, BE

#286 실패하는 테스트 코드 수정
  backend/src/main/java/codezap/template/service/TemplateService.java
  backend/src/test/java/codezap/template/service/TemplateServiceTest.java
Labels: bug, BE

#270 커스텀한 에러 응답 어노테이션 중복 정의 안되는 이슈 해결
  backend/src/main/java/codezap/global/swagger/error/ApiErrorResponse.java
  backend/src/main/java/codezap/global/swagger/error/ApiErrorResponses.java
Labels: bug, documentation, zap, BE

#279 Sentry 설정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/index.tsx
  frontend/webpack.common.js
Labels: feature, FE

#278 요청 로깅 시 쿠키 헤더 값도 기록
  backend/src/main/java/codezap/global/logger/RequestResponseLogger.java
Labels: feature, refactor, BE

#283 로거 순환 참조로 MethodExecutionTimeAspect 적용되지 않는 문제
  backend/src/main/java/codezap/global/logger/MethodExecutionTimeAspect.java
Labels: bug, BE

#295 dev 서버 로그 안찍히는 문제 해결
  backend/src/main/resources/logback-spring.xml
  backend/src/main/resources/logger/file/error-appender.xml
  backend/src/main/resources/logger/file/info-appender.xml
  backend/src/main/resources/logger/file/warn-appender.xml
  backend/src/main/resources/logger/logback-spring-dev.xml
  backend/src/main/resources/logger/logback-spring-prod.xml
Labels: bug, BE

#297 백엔드 API 명세에 따른 리팩토링
  frontend/src/api/categories.ts
  frontend/src/api/index.ts
  frontend/src/api/templates.ts
  frontend/src/components/CategoryMenu/CategoryMenu.tsx
Labels: FE, refactor

#303 모든 요청, 응답에 헤더 로깅
  backend/src/main/java/codezap/global/logger/MethodExecutionTimeAspect.java
  backend/src/main/java/codezap/global/logger/RequestResponseLogger.java
Labels: refactor, BE

#280 검색 기능 구현
  backend/src/main/java/codezap/category/service/CategoryService.java
  backend/src/main/java/codezap/member/repository/MemberRepository.java
  backend/src/main/java/codezap/member/service/MemberService.java
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
  backend/src/main/java/codezap/template/controller/TemplateController.java
  backend/src/main/java/codezap/template/domain/Template.java
  backend/src/main/java/codezap/template/dto/response/FindAllMyTemplatesResponse.java
  backend/src/main/java/codezap/template/dto/response/FindMyTemplateResponse.java
  backend/src/main/java/codezap/template/repository/TemplateRepository.java
  backend/src/main/java/codezap/template/service/MyTemplateFacadeService.java
  backend/src/main/java/codezap/template/service/TemplateService.java
  backend/src/test/java/codezap/member/repository/FakeMemberRepository.java
  backend/src/test/java/codezap/template/service/TemplateServiceSearchTest.java
  backend/src/test/java/codezap/template/service/TemplateServiceTest.java
  backend/src/test/resources/clear.sql
Labels: BE

#306 카테고리 생성 hotfix
  frontend/src/api/queryKeys.ts
  frontend/src/hooks/authentication/useCheckLoginState.ts
  frontend/src/hooks/authentication/useLoginForm.ts
  frontend/src/queries/category/useCategoryUpload.ts
Labels: bug, FE

#307 logback springProfile 재지정
  backend/src/main/resources/logback-spring.xml
Labels: bug, BE

#308 springProfile을 그룹이 아닌 각각으로 설정
  backend/src/main/resources/logback-spring.xml
Labels: bug, BE

#314 fix(service): 회원가입 버그 수정
  backend/src/main/java/codezap/member/service/MemberService.java
Labels: bug, BE

#317 쿠키 설정 추가
  backend/src/main/java/codezap/member/controller/MemberController.java
Labels: refactor, BE

#310 예외처리 문서화 추가
  backend/src/main/java/codezap/category/controller/SpringDocCategoryController.java
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
Labels: documentation, BE

#318 '내 템플릿' 페이지 검색 기능 구현
  frontend/src/api/index.ts
  frontend/src/api/templates.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/utils/useDebounce.ts
  frontend/src/mocks/categoryList.json
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/templateList.json
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
  frontend/src/queries/template/useTemplateListQuery.ts
  frontend/src/types/api.ts
  frontend/src/types/index.ts
Labels: feature, FE

#321 개발 서버 로그 저장 위치 변경
  backend/src/main/resources/logback-spring.xml
  backend/src/main/resources/logger/logback-spring-dev.xml
  backend/src/main/resources/logger/logback-spring-prod.xml
Labels: bug, BE

#319 [BE] 회원가입 버그 수정, 로그아웃 버그 수정, API 명세 수정, 로그 설정 수정
  backend/src/main/java/codezap/category/controller/SpringDocCategoryController.java
  backend/src/main/java/codezap/member/controller/MemberController.java
  backend/src/main/java/codezap/member/service/MemberService.java
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
  backend/src/main/resources/logback-spring.xml
  backend/src/main/resources/logger/logback-spring-dev.xml
  backend/src/main/resources/logger/logback-spring-prod.xml
Labels: bug, zap, BE

#325 검색 & 목록 조회 기능 병합
  backend/src/main/java/codezap/category/domain/Category.java
  backend/src/main/java/codezap/global/swagger/error/ApiErrorResponsesCustomizer.java
  backend/src/main/java/codezap/member/controller/SpringDocMemberController.java
  backend/src/main/java/codezap/member/service/MemberService.java
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
  backend/src/main/java/codezap/template/controller/TemplateController.java
  backend/src/main/java/codezap/template/domain/Template.java
  backend/src/main/java/codezap/template/dto/response/FindAllMyTemplatesResponse.java
  backend/src/main/java/codezap/template/dto/response/FindMyTemplateResponse.java
  backend/src/main/java/codezap/template/repository/TagRepository.java
  backend/src/main/java/codezap/template/repository/TemplateRepository.java
  backend/src/main/java/codezap/template/service/MyTemplateFacadeService.java
  backend/src/main/java/codezap/template/service/TemplateService.java
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
  backend/src/test/java/codezap/template/service/TemplateServiceSearchTest.java
  backend/src/test/java/codezap/template/service/TemplateServiceTest.java
Labels: feature, BE

#326 [BE] 검색 & 전체 조회 기능 병합
  backend/src/main/java/codezap/category/domain/Category.java
  backend/src/main/java/codezap/global/swagger/error/ApiErrorResponsesCustomizer.java
  backend/src/main/java/codezap/member/controller/SpringDocMemberController.java
  backend/src/main/java/codezap/member/service/MemberService.java
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
  backend/src/main/java/codezap/template/controller/TemplateController.java
  backend/src/main/java/codezap/template/domain/Template.java
  backend/src/main/java/codezap/template/dto/response/FindAllMyTemplatesResponse.java
  backend/src/main/java/codezap/template/dto/response/FindMyTemplateResponse.java
  backend/src/main/java/codezap/template/repository/TagRepository.java
  backend/src/main/java/codezap/template/repository/TemplateRepository.java
  backend/src/main/java/codezap/template/service/MyTemplateFacadeService.java
  backend/src/main/java/codezap/template/service/TemplateService.java
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
  backend/src/test/java/codezap/template/service/TemplateServiceSearchTest.java
  backend/src/test/java/codezap/template/service/TemplateServiceTest.java
Labels: feature, BE

#329 [BE] Swagger 의 CORS 문제 해결
  backend/src/main/java/codezap/global/swagger/SpringDocConfiguration.java
Labels: bug, BE

#327 로그인 상태에 따른 Routes 보호, frontend_cd 업데이트, 로그인/회원가입 안내메시지 스타일 변경
  .github/workflows/frontend_cd.yml
  .gitignore
  frontend/src/components/Header/Header.tsx
  frontend/src/hooks/authentication/useCheckLoginState.ts
  frontend/src/hooks/authentication/useLoginForm.ts
  frontend/src/pages/LoginPage/LoginPage.tsx
  frontend/src/pages/SignupPage/SignupPage.tsx
  frontend/src/routes/AuthGuard.tsx
  frontend/src/routes/GuestGuard.tsx
  frontend/src/routes/router.tsx
Labels: FE, refactor, zap

#331 [FE] 3차 데모데이 - 1차 QA 후 수정사항 반영
  .github/workflows/frontend_cd.yml
  .gitignore
  frontend/src/api/index.ts
  frontend/src/api/queryKeys.ts
  frontend/src/api/templates.ts
  frontend/src/components/Header/Header.tsx
  frontend/src/hooks/authentication/useCheckLoginState.ts
  frontend/src/hooks/authentication/useLoginForm.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/utils/useDebounce.ts
  frontend/src/mocks/categoryList.json
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/templateList.json
  frontend/src/pages/LoginPage/LoginPage.tsx
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
  frontend/src/pages/SignupPage/SignupPage.tsx
  frontend/src/queries/category/useCategoryUpload.ts
  frontend/src/queries/template/useTemplateListQuery.ts
  frontend/src/routes/AuthGuard.tsx
  frontend/src/routes/GuestGuard.tsx
  frontend/src/routes/router.tsx
  frontend/src/types/api.ts
  frontend/src/types/index.ts
Labels: FE, refactor, zap

#337 카테고리 목록 조회 로직 변경
  backend/src/main/java/codezap/category/controller/CategoryController.java
  backend/src/main/java/codezap/category/controller/SpringDocCategoryController.java
  backend/src/main/java/codezap/category/service/CategoryService.java
  backend/src/test/java/codezap/category/controller/CategoryControllerTest.java
Labels: feature, BE

#338 로그인 후 사용자 정보 반환
  backend/src/main/java/codezap/member/controller/MemberController.java
  backend/src/main/java/codezap/member/controller/SpringDocMemberController.java
  backend/src/main/java/codezap/member/dto/LoginResponse.java
  backend/src/main/java/codezap/member/service/MemberService.java
Labels: zap, BE

#340 refactor(dto): 응답 형식 변경
  backend/src/main/java/codezap/member/dto/LoginResponse.java
Labels: zap, BE

#341 로그인 응답 변경
  backend/src/main/java/codezap/member/controller/MemberController.java
  backend/src/main/java/codezap/member/controller/SpringDocMemberController.java
  backend/src/main/java/codezap/member/dto/LoginResponse.java
  backend/src/main/java/codezap/member/service/MemberService.java
Labels: BE

#334 '내 템플릿' 페이지 정렬 기능
  frontend/src/api/index.ts
  frontend/src/api/templates.ts
  frontend/src/components/Dropdown/Dropdown.style.ts
  frontend/src/components/Dropdown/Dropdown.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
  frontend/src/queries/template/useTemplateListQuery.ts
  frontend/src/types/api.ts
  frontend/src/types/index.ts
Labels: feature, FE

#343 actuator 및 micrometer 의존성 추가
  backend/build.gradle
Labels: BE

#344 prometheus, micrometer prometheus 추가
  backend/build.gradle
Labels: feature, BE

#342 auth 전역 상태에 멤버 정보 추가, 템플릿 목록 조회 및 카테고리 목록 조회 요청의 Params에 memberId 추가
  frontend/src/api/authentication.ts
  frontend/src/api/categories.ts
  frontend/src/api/templates.ts
  frontend/src/contexts/authContext.tsx
  frontend/src/hooks/authentication/useLoginForm.ts
  frontend/src/queries/authentication/useLoginMutation.ts
  frontend/src/queries/category/useCategoryListQuery.ts
  frontend/src/queries/template/useTemplateListQuery.ts
  frontend/src/types/api.ts
  frontend/src/types/authentication.ts
Labels: feature, FE

#353 템플릿 반환 값에 생성 시간 포함하도록 변경
  backend/src/main/java/codezap/template/dto/response/FindAllTemplatesResponse.java
  backend/src/main/java/codezap/template/dto/response/FindTemplateResponse.java
Labels: bug, zap, BE

#359 3차 데모데이 전 버그 픽스
  frontend/src/api/authentication.ts
  frontend/src/api/templates.ts
  frontend/src/assets/images/codezapLogo.png
  frontend/src/assets/images/index.ts
  frontend/src/assets/images/newTemplate.png
  frontend/src/assets/images/newTemplate_12x12.png
  frontend/src/components/Button/Button.style.ts
  frontend/src/components/CategoryMenu/CategoryMenu.style.ts
  frontend/src/components/Header/Header.style.ts
  frontend/src/components/Header/Header.tsx
  frontend/src/components/PagingButton/PagingButton.style.ts
  frontend/src/context/ToastContext.tsx
  frontend/src/hooks/category/useCategory.ts
  frontend/src/mocks/handlers.ts
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
  frontend/src/queries/authentication/useLoginMutation.ts
  frontend/src/routes/AuthGuard.tsx
  frontend/src/routes/GuestGuard.tsx
  frontend/src/types/api.ts
Labels: FE, refactor, zap

#351 카테고리 전체 조회시 id 오름차순으로 정렬
  backend/src/main/java/codezap/category/repository/CategoryJpaRepository.java
  backend/src/main/java/codezap/category/repository/CategoryRepository.java
  backend/src/main/java/codezap/category/service/CategoryService.java
  backend/src/test/java/codezap/category/repository/FakeCategoryRepository.java
Labels: bug, zap, BE

#364 응답 요청 로깅에서 /actuator/prometheus 일 경우 제외
  backend/src/main/java/codezap/global/logger/RequestResponseLogger.java
Labels: refactor, BE

#368 템플릿 태그 검색 시 모든 태그가 포함된 템플릿만 검색되도록 수정
  backend/src/main/java/codezap/template/repository/TemplateTagRepository.java
  backend/src/main/java/codezap/template/service/TemplateService.java
  backend/src/test/java/codezap/template/service/TemplateServiceSearchTest.java
Labels: bug, zap, BE

#369 CD 수정, 아티팩터 다운로드 폴더 삭제 및 생성
  .github/workflows/frontend_cd.yml
Labels: bug, FE, zap

#365 README.md 파일에 위키 링크 추가
  README.md
Labels: documentation, FE, BE

#370 sentry auth token 오타 수정
  .github/workflows/frontend_cd.yml
Labels: bug, FE

#371 [FE] 3차 데모데이 - 2차 QA 후 수정사항 반영
  frontend/src/api/authentication.ts
  frontend/src/api/categories.ts
  frontend/src/api/index.ts
  frontend/src/api/queryKeys.ts
  frontend/src/api/tags.ts
  frontend/src/api/templates.ts
  frontend/src/assets/images/codezapLogo.png
  frontend/src/assets/images/index.ts
  frontend/src/assets/images/newTemplate.png
  frontend/src/assets/images/newTemplate_12x12.png
  frontend/src/components/Button/Button.style.ts
  frontend/src/components/CategoryFilterMenu/CategoryFilterMenu.stories.tsx
  frontend/src/components/CategoryFilterMenu/CategoryFilterMenu.style.ts
  frontend/src/components/CategoryFilterMenu/CategoryFilterMenu.tsx
  frontend/src/components/CategoryMenu/CategoryMenu.stories.tsx
  frontend/src/components/Dropdown/Dropdown.style.ts
  frontend/src/components/Dropdown/Dropdown.tsx
  frontend/src/components/Header/Header.style.ts
  frontend/src/components/Header/Header.tsx
  frontend/src/components/PagingButton/PagingButton.style.ts
  frontend/src/components/TagButton/TagButton.stories.tsx
  frontend/src/components/TagButton/TagButton.style.ts
  frontend/src/components/TagButton/TagButton.tsx
  frontend/src/components/TagFilterMenu/TagFilterMenu.style.ts
  frontend/src/components/TagFilterMenu/TagFilterMenu.tsx
  frontend/src/components/TemplateCard/TemplateCard.tsx
  frontend/src/components/index.ts
  frontend/src/context/ToastContext.tsx
  frontend/src/contexts/authContext.tsx
  frontend/src/hooks/authentication/useLoginForm.ts
  frontend/src/hooks/category/useCategory.ts
  frontend/src/mocks/handlers.ts
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
  frontend/src/pages/TemplatePage/TemplatePage.tsx
  frontend/src/queries/authentication/useLoginMutation.ts
  frontend/src/queries/category/useCategoryListQuery.ts
  frontend/src/queries/tag/index.ts
  frontend/src/queries/tag/useTagListQuery.ts
  frontend/src/queries/template/useTemplateListQuery.ts
  frontend/src/routes/AuthGuard.tsx
  frontend/src/routes/GuestGuard.tsx
  frontend/src/types/api.ts
  frontend/src/types/authentication.ts
  frontend/src/types/index.ts
Labels: FE, refactor

#375 서버 "/" 경로 접속시 띄울 404 화면 추가
  backend/src/main/resources/static/404.png
  backend/src/main/resources/static/index.html
Labels: refactor, BE

#373 404 페이지
  frontend/src/assets/images/index.ts
  frontend/src/assets/images/tigger.png
  frontend/src/contexts/authContext.tsx
  frontend/src/pages/NotFoundPage/NotFoundPage.tsx
Labels: feature, FE

#378 ErrorBoundary 적용, Fetch 변경
  frontend/src/api/authentication.ts
  frontend/src/api/categories.ts
  frontend/src/api/customFetch.ts
  frontend/src/api/tags.ts
  frontend/src/api/templates.ts
  frontend/src/components/Layout/Layout.tsx
  frontend/src/hooks/authentication/useSignupForm.ts
  frontend/src/hooks/template/useTemplateUpload.ts
  frontend/src/queries/tag/useTagListQuery.ts
  frontend/src/routes/router.tsx
  frontend/src/types/fetch.ts
  frontend/src/types/index.ts
Labels: FE, refactor, zap

#374 태그 조회 기능에 인가 플로우 추가
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
  backend/src/main/java/codezap/template/controller/TemplateController.java
Labels: refactor, BE

#379 모달 컴포넌트 및 삭제 모달 추가
  frontend/src/components/Modal/Modal.style.ts
  frontend/src/components/Modal/Modal.tsx
  frontend/src/components/index.ts
  frontend/src/hooks/utils/useModal.ts
  frontend/src/pages/TemplatePage/TemplatePage.tsx
Labels: feature, FE

#380 로그인 상태 유지 기능
  frontend/src/contexts/authContext.tsx
  frontend/src/queries/authentication/useLoginMutation.ts
  frontend/src/queries/authentication/useLogoutMutation.ts
  frontend/src/routes/AuthGuard.tsx
  frontend/src/routes/GuestGuard.tsx
Labels: feature, FE

#381 ErrorBoundary에 NotFound 페이지 적용
  frontend/src/components/Layout/Layout.tsx
  frontend/src/pages/NotFoundPage/NotFoundPage.tsx
  frontend/src/pages/index.ts
  frontend/src/routes/router.tsx
Labels: FE, refactor

#382 [FE] 3차 데모데이 - 3차 QA 후 수정사항 반영
  frontend/src/api/authentication.ts
  frontend/src/api/categories.ts
  frontend/src/api/customFetch.ts
  frontend/src/api/tags.ts
  frontend/src/api/templates.ts
  frontend/src/assets/images/index.ts
  frontend/src/assets/images/tigger.png
  frontend/src/components/Layout/Layout.tsx
  frontend/src/components/Modal/Modal.style.ts
  frontend/src/components/Modal/Modal.tsx
  frontend/src/components/index.ts
  frontend/src/contexts/authContext.tsx
  frontend/src/hooks/authentication/useSignupForm.ts
  frontend/src/hooks/template/useTemplateUpload.ts
  frontend/src/hooks/utils/useModal.ts
  frontend/src/pages/NotFoundPage/NotFoundPage.tsx
  frontend/src/pages/TemplatePage/TemplatePage.tsx
  frontend/src/pages/index.ts
  frontend/src/queries/authentication/useLoginMutation.ts
  frontend/src/queries/authentication/useLogoutMutation.ts
  frontend/src/queries/tag/useTagListQuery.ts
  frontend/src/routes/AuthGuard.tsx
  frontend/src/routes/GuestGuard.tsx
  frontend/src/routes/router.tsx
  frontend/src/types/fetch.ts
  frontend/src/types/index.ts
Labels: feature, FE

#383 LandingPage
  frontend/src/pages/LandingPage/LandingPage.tsx
  frontend/src/pages/index.ts
  frontend/src/routes/router.tsx
Labels: feature, FE

#386 랜딩페이지 적용
  frontend/src/pages/LandingPage/LandingPage.tsx
  frontend/src/pages/index.ts
  frontend/src/routes/router.tsx
Labels: feature, FE

#409 폴더별 누락된 index 생성 및 import 문 정리
  frontend/public/index.html
  frontend/src/api/index.ts
  frontend/src/components/index.ts
  frontend/src/contexts/HeaderContext.tsx
  frontend/src/contexts/ToastContext.tsx
  frontend/src/contexts/index.ts
  frontend/src/hooks/authentication/index.ts
  frontend/src/hooks/authentication/useAuth.ts
  frontend/src/hooks/authentication/useCheckLoginState.ts
  frontend/src/hooks/authentication/useLoginForm.ts
  frontend/src/hooks/authentication/useSignupForm.ts
  frontend/src/hooks/category/index.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/template/index.ts
  frontend/src/hooks/template/useTemplate.ts
  frontend/src/hooks/template/useTemplateEdit.ts
  frontend/src/hooks/template/useTemplateUpload.ts
  frontend/src/hooks/utils/index.ts
  frontend/src/hooks/utils/useCustomContext.ts
  frontend/src/hooks/utils/useHeaderHeight.ts
  frontend/src/hooks/utils/useInputWithValidate.ts
  frontend/src/hooks/utils/useWindowWidth.ts
  frontend/src/index.tsx
  frontend/src/mocks/templateList_2.json
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
  frontend/src/pages/TemplateEditPage/TemplateEditPage.tsx
  frontend/src/pages/TemplatePage/TemplatePage.tsx
  frontend/src/pages/index.ts
  frontend/src/queries/authentication/index.ts
  frontend/src/queries/authentication/useLoginMutation.ts
  frontend/src/queries/category/index.ts
  frontend/src/queries/category/useCategoryUploadMutation.ts
  frontend/src/queries/template/index.ts
  frontend/src/queries/template/useTemplateDeleteMutation.spec.tsx
  frontend/src/queries/template/useTemplateDeleteMutation.ts
  frontend/src/queries/template/useTemplateEditMutation.spec.tsx
  frontend/src/queries/template/useTemplateEditMutation.ts
  frontend/src/queries/template/useTemplateQuery.spec.tsx
  frontend/src/queries/template/useTemplateQuery.ts
  frontend/src/queries/template/useTemplateUploadMutation.spec.tsx
  frontend/src/queries/template/useTemplateUploadMutation.ts
  frontend/src/routes/AuthGuard.tsx
  frontend/src/routes/GuestGuard.tsx
  frontend/src/service/index.ts
  frontend/src/service/validates.ts
  frontend/src/utils/index.ts
Labels: FE, refactor

#411 [BE] 테스트 환경 변경
  backend/src/main/java/codezap/category/controller/CategoryController.java
  backend/src/main/java/codezap/category/controller/SpringDocCategoryController.java
  backend/src/main/java/codezap/category/domain/Category.java
  backend/src/main/java/codezap/category/service/CategoryService.java
  backend/src/main/java/codezap/global/swagger/AuthOperationCustomizer.java
  backend/src/main/java/codezap/global/swagger/SpringDocConfiguration.java
  backend/src/main/java/codezap/member/service/MemberService.java
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
  backend/src/main/java/codezap/template/controller/TemplateController.java
  backend/src/main/java/codezap/template/domain/Snippet.java
  backend/src/main/java/codezap/template/domain/Tag.java
  backend/src/main/java/codezap/template/domain/Template.java
  backend/src/main/java/codezap/template/domain/TemplateTag.java
  backend/src/main/java/codezap/template/domain/ThumbnailSnippet.java
  backend/src/main/java/codezap/template/repository/SnippetJpaRepository.java
  backend/src/main/java/codezap/template/repository/SnippetRepository.java
  backend/src/main/java/codezap/template/repository/TagJpaRepository.java
  backend/src/main/java/codezap/template/repository/TagRepository.java
  backend/src/main/java/codezap/template/repository/TemplateJpaRepository.java
  backend/src/main/java/codezap/template/repository/TemplateRepository.java
  backend/src/main/java/codezap/template/repository/TemplateTagJpaRepository.java
  backend/src/main/java/codezap/template/repository/TemplateTagRepository.java
  backend/src/main/java/codezap/template/repository/ThumbnailSnippetJpaRepository.java
  backend/src/main/java/codezap/template/repository/ThumbnailSnippetRepository.java
  backend/src/main/java/codezap/template/service/TemplateService.java
  backend/src/test/java/codezap/category/controller/CategoryControllerTest.java
  backend/src/test/java/codezap/category/repository/FakeCategoryRepository.java
  backend/src/test/java/codezap/category/service/CategoryServiceTest.java
  backend/src/test/java/codezap/member/repository/FakeMemberRepository.java
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
  backend/src/test/java/codezap/template/repository/FakeSnippetRepository.java
  backend/src/test/java/codezap/template/repository/FakeTagRepository.java
  backend/src/test/java/codezap/template/repository/FakeTemplateRepository.java
  backend/src/test/java/codezap/template/repository/FakeTemplateTagRepository.java
  backend/src/test/java/codezap/template/repository/FakeThumbnailSnippetRepository.java
  backend/src/test/java/codezap/template/repository/SnippetRepositoryTest.java
  backend/src/test/java/codezap/template/service/TagSearchTest.java
  backend/src/test/java/codezap/template/service/TemplateServiceSearchTest.java
  backend/src/test/java/codezap/template/service/TemplateServiceTest.java
Labels: feature, BE

#410 [FE] 디렉토리 스타일 통합
  frontend/public/index.html
  frontend/src/api/index.ts
  frontend/src/components/index.ts
  frontend/src/contexts/AuthContext.tsx
  frontend/src/contexts/HeaderContext.tsx
  frontend/src/contexts/ToastContext.tsx
  frontend/src/contexts/index.ts
  frontend/src/hooks/authentication/index.ts
  frontend/src/hooks/authentication/useAuth.ts
  frontend/src/hooks/authentication/useCheckLoginState.ts
  frontend/src/hooks/authentication/useLoginForm.ts
  frontend/src/hooks/authentication/useSignupForm.ts
  frontend/src/hooks/category/index.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/template/index.ts
  frontend/src/hooks/template/useTemplate.ts
  frontend/src/hooks/template/useTemplateEdit.ts
  frontend/src/hooks/template/useTemplateUpload.ts
  frontend/src/hooks/utils/index.ts
  frontend/src/hooks/utils/useCustomContext.ts
  frontend/src/hooks/utils/useHeaderHeight.ts
  frontend/src/hooks/utils/useInputWithValidate.ts
  frontend/src/hooks/utils/useWindowWidth.ts
  frontend/src/index.tsx
  frontend/src/mocks/templateList_2.json
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
  frontend/src/pages/TemplateEditPage/TemplateEditPage.tsx
  frontend/src/pages/TemplatePage/TemplatePage.tsx
  frontend/src/pages/index.ts
  frontend/src/queries/authentication/index.ts
  frontend/src/queries/authentication/useLoginMutation.ts
  frontend/src/queries/category/index.ts
  frontend/src/queries/category/useCategoryUploadMutation.ts
  frontend/src/queries/template/index.ts
  frontend/src/queries/template/useTemplateDeleteMutation.spec.tsx
  frontend/src/queries/template/useTemplateDeleteMutation.ts
  frontend/src/queries/template/useTemplateEditMutation.spec.tsx
  frontend/src/queries/template/useTemplateEditMutation.ts
  frontend/src/queries/template/useTemplateQuery.spec.tsx
  frontend/src/queries/template/useTemplateQuery.ts
  frontend/src/queries/template/useTemplateUploadMutation.spec.tsx
  frontend/src/queries/template/useTemplateUploadMutation.ts
  frontend/src/routes/AuthGuard.tsx
  frontend/src/routes/GuestGuard.tsx
  frontend/src/service/index.ts
  frontend/src/service/validates.ts
  frontend/src/utils/index.ts
Labels: FE, refactor

#428 비밀번호 유효성 검사 변경, 이메일 에러 메시지 변경
  frontend/src/service/validates.ts
Labels: bug, FE, zap

#412 CD 실행 브랜치 변경 및 self-hosted-runner 사용하도록 변경
  .github/workflows/backend_cd.yml
  .github/workflows/backend_ci.yml
  .github/workflows/frontend_cd.yml
  .github/workflows/frontend_ci.yml
Labels: refactor, BE, infrastructure

#415 member controller에 @ApiErrorResponse 적용
  backend/src/main/java/codezap/member/controller/SpringDocMemberController.java
Labels: refactor, BE

#417 GlobalExceptionHandler를 ResponseEntityExceptionHandler를 상속
  backend/src/main/java/codezap/global/exception/GlobalExceptionHandler.java
Labels: refactor, zap, BE

#419 회원 정보 수정, 조회 API 문서 작성
  backend/src/main/java/codezap/member/controller/MemberController.java
  backend/src/main/java/codezap/member/controller/SpringDocMemberController.java
  backend/src/main/java/codezap/member/dto/request/UpdateMemberProfileRequest.java
  backend/src/main/java/codezap/member/dto/response/FindMemberResponse.java
  backend/src/main/java/codezap/member/dto/response/UpdateMemberProfileResponse.java
Labels: documentation, BE

#418 하나의 status에 대해 예외 상황이 여러개일 경우, 문서가 덮어씌워지는 에러 해결
  backend/src/main/java/codezap/global/swagger/error/ApiErrorResponsesCustomizer.java
Labels: bug, zap, BE

#425 템플릿 선택 삭제 및 조회 시 썸네일 스니펫 추가한 API 문서 작성
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
  backend/src/main/java/codezap/template/controller/TemplateController.java
  backend/src/main/java/codezap/template/dto/request/CreateSnippetRequest.java
  backend/src/main/java/codezap/template/dto/request/CreateTemplateRequest.java
  backend/src/main/java/codezap/template/dto/request/UpdateSnippetRequest.java
  backend/src/main/java/codezap/template/dto/request/UpdateTemplateRequest.java
  backend/src/main/java/codezap/template/dto/response/FindAllTemplatesResponse.java
  backend/src/main/java/codezap/template/dto/response/FindThumbnailSnippetResponse.java
  backend/src/main/java/codezap/template/service/TemplateService.java
  backend/src/test/java/codezap/category/controller/CategoryControllerTest.java
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
  backend/src/test/java/codezap/template/service/TagSearchTest.java
  backend/src/test/java/codezap/template/service/TemplateServiceSearchTest.java
  backend/src/test/java/codezap/template/service/TemplateServiceTest.java
Labels: documentation, BE

#438 로그인 안한 사용자에게 / 경로가 랜딩페이지로 보이도록 설정
  frontend/src/api/categories.ts
  frontend/src/api/tags.ts
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.spec.tsx
  frontend/src/queries/category/useCategoryListQuery.spec.tsx
  frontend/src/queries/tag/useTagListQuery.spec.tsx
  frontend/src/queries/template/useTemplateListQuery.spec.tsx
  frontend/src/routes/GuestGuard.tsx
  frontend/src/routes/HomeRouter.tsx
  frontend/src/routes/router.tsx
Labels: FE, refactor

#440 에러 바운더리에 query reset과 key 추가
  frontend/src/api/customFetch.ts
  frontend/src/components/Layout/Layout.tsx
  frontend/src/hooks/authentication/useSignupForm.ts
  frontend/src/mocks/handlers.ts
  frontend/src/pages/NotFoundPage/NotFoundPage.tsx
  frontend/src/queries/authentication/index.ts
  frontend/src/queries/authentication/useSignupMutation.ts
  frontend/src/queries/template/useTemplateListQuery.ts
Labels: feature, FE

#424 CD 실행 브랜치 변경 및 self-hosted-runner 사용하도록 변경
  .github/workflows/backend_cd.yml
  .github/workflows/backend_ci.yml
  .github/workflows/frontend_cd.yml
  .github/workflows/frontend_ci.yml
Labels: FE, refactor, infrastructure

#447 카테고리 글자 esllipse 처리, 영단어 한글화, 코드 에디터 높이 변경
  frontend/src/components/CategoryFilterMenu/CategoryFilterMenu.style.ts
  frontend/src/components/SnippetEditor/SnippetEditor.tsx
  frontend/src/components/TemplateEdit/TemplateEdit.tsx
Labels: FE, refactor

#445 RouteGuard 리팩토링, 로그인 관련 버그 픽스 및 안내메시지 추가
  frontend/src/contexts/AuthContext.tsx
  frontend/src/queries/authentication/useLoginMutation.ts
  frontend/src/queries/authentication/useLoginStateQuery.ts
  frontend/src/queries/authentication/useLogoutMutation.ts
  frontend/src/routes/AuthGuard.tsx
  frontend/src/routes/GuestGuard.tsx
  frontend/src/routes/RouteGuard.tsx
  frontend/src/routes/router.tsx
Labels: feature, FE

#448 CD가 아닌 다른 actions들은 ubuntu-latest 사용으로 변경
  .github/workflows/backend_ci.yml
  .github/workflows/ci_cd_fail_notification.yml
  .github/workflows/frontend_ci.yml
  .github/workflows/pr_notification.yml
  .github/workflows/review_notification.yml
Labels: refactor, zap, BE, infrastructure

#443 TemplateCard 썸네일 추가 및 리디자인
  frontend/src/components/Header/Header.style.ts
  frontend/src/components/TemplateCard/TemplateCard.style.ts
  frontend/src/components/TemplateCard/TemplateCard.tsx
  frontend/src/components/TemplateGrid/TemplateGrid.style.ts
  frontend/src/components/TemplateGrid/TemplateGrid.tsx
  frontend/src/hooks/authentication/index.ts
  frontend/src/hooks/authentication/useShowPassword.ts
  frontend/src/hooks/utils/index.ts
  frontend/src/hooks/utils/useModal.ts
  frontend/src/hooks/utils/useToggle.ts
  frontend/src/mocks/templateList.json
  frontend/src/pages/LoginPage/LoginPage.tsx
  frontend/src/pages/SignupPage/SignupPage.tsx
  frontend/src/pages/TemplatePage/TemplatePage.tsx
  frontend/src/queries/template/useTemplateListQuery.spec.tsx
  frontend/src/types/api.ts
  frontend/src/types/index.ts
  frontend/src/types/template.ts
Labels: feature, FE

#452 Header에 '서비스 소개'옵션 추가, 로그인 상태에 따른 '내 템플릿' 옵션 활성화
  frontend/src/components/Header/Header.tsx
Labels: feature, FE

#451 font 404 에러 해결
  frontend/public/index.html
  frontend/src/style/GlobalStyles.tsx
Labels: bug, FE

#450 백엔드 CI JDK 설정 추가
  .github/workflows/backend_ci.yml
Labels: bug, zap, BE, infrastructure

#444 Auth 도메인 리팩토링 및 회원 조회 기능 구현
  backend/src/main/java/codezap/auth/configuration/AuthArgumentResolver.java
  backend/src/main/java/codezap/auth/configuration/AuthWebConfiguration.java
  backend/src/main/java/codezap/auth/configuration/AuthenticationPrinciple.java
  backend/src/main/java/codezap/auth/configuration/AuthorizationInterceptor.java
  backend/src/main/java/codezap/auth/controller/AuthController.java
  backend/src/main/java/codezap/auth/controller/SpringDocAuthController.java
  backend/src/main/java/codezap/auth/dto/LoginAndCredentialDto.java
  backend/src/main/java/codezap/auth/dto/request/LoginRequest.java
  backend/src/main/java/codezap/auth/dto/response/LoginResponse.java
  backend/src/main/java/codezap/auth/manager/CookieCredentialManager.java
  backend/src/main/java/codezap/auth/manager/CredentialManager.java
  backend/src/main/java/codezap/auth/provider/CredentialProvider.java
  backend/src/main/java/codezap/auth/provider/basic/BasicAuthCredentialProvider.java
  backend/src/main/java/codezap/auth/provider/basic/BasicAuthDecoder.java
  backend/src/main/java/codezap/auth/service/AuthService.java
  backend/src/main/java/codezap/category/controller/CategoryController.java
  backend/src/main/java/codezap/category/controller/SpringDocCategoryController.java
  backend/src/main/java/codezap/category/service/CategoryService.java
  backend/src/main/java/codezap/global/swagger/AuthOperationCustomizer.java
  backend/src/main/java/codezap/member/configuration/AuthWebConfiguration.java
  backend/src/main/java/codezap/member/controller/MemberController.java
  backend/src/main/java/codezap/member/controller/SpringDocMemberController.java
  backend/src/main/java/codezap/member/domain/Member.java
  backend/src/main/java/codezap/member/dto/LoginResponse.java
  backend/src/main/java/codezap/member/dto/MemberDto.java
  backend/src/main/java/codezap/member/dto/SignupRequest.java
  backend/src/main/java/codezap/member/dto/request/SignupRequest.java
  backend/src/main/java/codezap/member/dto/request/UpdateMemberProfileRequest.java
  backend/src/main/java/codezap/member/dto/response/FindMemberResponse.java
  backend/src/main/java/codezap/member/dto/response/UpdateMemberProfileResponse.java
  backend/src/main/java/codezap/member/repository/MemberJpaRepository.java
  backend/src/main/java/codezap/member/repository/MemberRepository.java
  backend/src/main/java/codezap/member/service/AuthService.java
  backend/src/main/java/codezap/member/service/MemberService.java
  backend/src/main/java/codezap/template/controller/TemplateController.java
  backend/src/main/java/codezap/template/service/TemplateService.java
  backend/src/test/java/codezap/auth/manager/CookieCredentialManagerTest.java
  backend/src/test/java/codezap/auth/provider/basic/BasicAuthCredentialProviderTest.java
  backend/src/test/java/codezap/auth/provider/basic/BasicAuthDecoderTest.java
  backend/src/test/java/codezap/auth/service/AuthServiceTest.java
  backend/src/test/java/codezap/category/controller/CategoryControllerTest.java
  backend/src/test/java/codezap/category/service/CategoryServiceTest.java
  backend/src/test/java/codezap/fixture/MemberDtoFixture.java
  backend/src/test/java/codezap/global/MockMvcTest.java
  backend/src/test/java/codezap/member/controller/MemberControllerTest.java
  backend/src/test/java/codezap/member/domain/MemberTest.java
  backend/src/test/java/codezap/member/fixture/MemberFixture.java
  backend/src/test/java/codezap/member/repository/FakeMemberRepository.java
  backend/src/test/java/codezap/member/service/MemberServiceTest.java
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
  backend/src/test/java/codezap/template/service/TagSearchTest.java
  backend/src/test/java/codezap/template/service/TemplateServiceSearchTest.java
  backend/src/test/java/codezap/template/service/TemplateServiceTest.java
  backend/src/test/resources/clear.sql
Labels: feature, refactor, BE

#449 FE CD beta서버 분리
  .github/workflows/frontend_cd.yml
Labels: FE, refactor, zap

#455 email 제거, username -> name으로 변경
  frontend/src/api/authentication.ts
  frontend/src/api/categories.ts
  frontend/src/api/index.ts
  frontend/src/api/queryKeys.ts
  frontend/src/api/tags.ts
  frontend/src/contexts/AuthContext.tsx
  frontend/src/hooks/authentication/useLoginForm.ts
  frontend/src/hooks/authentication/useSignupForm.ts
  frontend/src/mocks/handlers.ts
  frontend/src/pages/LoginPage/LoginPage.tsx
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
  frontend/src/pages/SignupPage/SignupPage.tsx
  frontend/src/queries/authentication/index.ts
  frontend/src/queries/authentication/useCheckEmailQuery.ts
  frontend/src/queries/authentication/useCheckNameQuery.ts
  frontend/src/queries/authentication/useCheckUsernameQuery.ts
  frontend/src/queries/authentication/useLoginMutation.ts
  frontend/src/queries/authentication/useLogoutMutation.ts
  frontend/src/service/index.ts
  frontend/src/service/validates.ts
  frontend/src/types/authentication.ts
  frontend/src/types/index.ts
Labels: feature, FE

#456 회원 아이디 중복 검증 엔드포인트 수정
  backend/src/main/java/codezap/member/controller/MemberController.java
  backend/src/test/java/codezap/member/controller/MemberControllerTest.java
Labels: bug, zap, BE

#458 회원만 접근할 수 있는 엔드포인트 검증용 interceptor 제거
  backend/src/main/java/codezap/auth/configuration/AuthWebConfiguration.java
  backend/src/main/java/codezap/global/swagger/SpringDocConfiguration.java
Labels: bug, BE

#460 refactor(workflows): ubuntu-latest 로 변경
  .github/workflows/frontend_ci.yml
Labels: FE, refactor, infrastructure

#453 템플릿 선택 삭제 기능 추가
  frontend/src/api/templates.ts
  frontend/src/assets/images/arrowUp.png
  frontend/src/assets/images/index.ts
  frontend/src/components/Dropdown/Dropdown.style.ts
  frontend/src/components/Input/Input.style.ts
  frontend/src/components/PagingButton/PagingButton.style.ts
  frontend/src/components/SourceCodeEditor/SourceCodeEditor.tsx
  frontend/src/components/SourceCodeEditor/style.ts
  frontend/src/components/TemplateCard/TemplateCard.tsx
  frontend/src/components/TemplateEdit/TemplateEdit.tsx
  frontend/src/components/TemplateGrid/TemplateGrid.style.ts
  frontend/src/components/TemplateGrid/TemplateGrid.tsx
  frontend/src/components/TemplateItem/TemplateItem.tsx
  frontend/src/components/index.ts
  frontend/src/hooks/template/useTemplate.ts
  frontend/src/hooks/template/useTemplateEdit.ts
  frontend/src/hooks/template/useTemplateUpload.ts
  frontend/src/index.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/template.json
  frontend/src/mocks/templateList.json
  frontend/src/pages/LandingPage/LandingPage.tsx
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.spec.tsx
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.style.ts
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
  frontend/src/pages/TemplatePage/TemplatePage.tsx
  frontend/src/queries/template/useTemplateDeleteMutation.spec.tsx
  frontend/src/queries/template/useTemplateDeleteMutation.ts
  frontend/src/queries/template/useTemplateEditMutation.spec.tsx
  frontend/src/queries/template/useTemplateListQuery.spec.tsx
  frontend/src/queries/template/useTemplateUploadMutation.spec.tsx
  frontend/src/types/api.ts
  frontend/src/types/index.ts
  frontend/src/types/template.ts
  frontend/src/utils/scroll.ts
Labels: feature, FE

#462 '/' 경로에서 새로고침 시, 로그인 해제되는 버그
  frontend/src/components/Header/Header.tsx
  frontend/src/contexts/AuthContext.tsx
  frontend/src/hooks/category/useCategory.ts
  frontend/src/routes/HomeRouter.tsx
  frontend/src/routes/RouteGuard.tsx
Labels: bug, FE

#466 PNG -> SVG 변경
  frontend/.storybook/main.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/images/arrowUp.png
  frontend/src/assets/images/arrowUp.svg
  frontend/src/assets/images/chevron.png
  frontend/src/assets/images/chevron.svg
  frontend/src/assets/images/codezapLogo.png
  frontend/src/assets/images/codezapLogo.svg
  frontend/src/assets/images/eye.svg
  frontend/src/assets/images/index.ts
  frontend/src/assets/images/logo_24x24.png
  frontend/src/assets/images/newTemplate.png
  frontend/src/assets/images/passwordEye.png
  frontend/src/assets/images/pencil.png
  frontend/src/assets/images/pencil.svg
  frontend/src/assets/images/plus.svg
  frontend/src/assets/images/search.png
  frontend/src/assets/images/search.svg
  frontend/src/assets/images/tiger.svg
  frontend/src/assets/images/tigger.png
  frontend/src/assets/images/trashcan.png
  frontend/src/assets/images/trashcan.svg
  frontend/src/assets/images/userCircle.svg
  frontend/src/assets/images/userMenu_38x38.png
  frontend/src/assets/images/xCircle.svg
  frontend/src/assets/images/x_circle.png
  frontend/src/components/Dropdown/Dropdown.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Input/Input.stories.tsx
  frontend/src/components/TagInput/TagInput.style.ts
  frontend/src/components/TagInput/TagInput.tsx
  frontend/src/components/TemplateEdit/TemplateEdit.tsx
  frontend/src/pages/LandingPage/LandingPage.tsx
  frontend/src/pages/LoginPage/LoginPage.tsx
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
  frontend/src/pages/NotFoundPage/NotFoundPage.tsx
  frontend/src/pages/SignupPage/SignupPage.tsx
  frontend/src/pages/TemplatePage/TemplatePage.tsx
  frontend/src/types/images.d.ts
  frontend/webpack.common.js
Labels: FE, refactor

#459 충돌한 테스트 코드 해결 및 equals 재정의
  backend/src/main/java/codezap/auth/configuration/AuthorizationInterceptor.java
  backend/src/main/java/codezap/auth/controller/AuthController.java
  backend/src/main/java/codezap/category/domain/Category.java
  backend/src/main/java/codezap/member/domain/Member.java
  backend/src/main/java/codezap/template/domain/SourceCode.java
  backend/src/main/java/codezap/template/domain/Tag.java
  backend/src/main/java/codezap/template/domain/Template.java
  backend/src/main/java/codezap/template/domain/TemplateTag.java
  backend/src/main/java/codezap/template/domain/Thumbnail.java
  backend/src/main/java/codezap/template/dto/request/validation/SourceCodesCountValidator.java
  backend/src/main/java/codezap/template/dto/request/validation/SourceCodesOrdinalValidator.java
  backend/src/main/java/codezap/template/service/TemplateService.java
  backend/src/test/java/codezap/auth/provider/basic/BasicAuthDecoderTest.java
  backend/src/test/java/codezap/auth/service/AuthServiceTest.java
  backend/src/test/java/codezap/category/controller/CategoryControllerTest.java
  backend/src/test/java/codezap/category/service/CategoryServiceTest.java
  backend/src/test/java/codezap/fixture/MemberDtoFixture.java
  backend/src/test/java/codezap/member/controller/MemberControllerTest.java
  backend/src/test/java/codezap/member/domain/MemberTest.java
  backend/src/test/java/codezap/member/fixture/MemberFixture.java
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
  backend/src/test/java/codezap/template/repository/FakeSourceCodeRepository.java
  backend/src/test/java/codezap/template/service/TagSearchTest.java
  backend/src/test/java/codezap/template/service/TemplateServiceSearchTest.java
  backend/src/test/java/codezap/template/service/TemplateServiceTest.java
Labels: refactor, BE

#468 운영 환경 로그 설정
  backend/src/main/resources/logback-spring.xml
  backend/src/main/resources/logger/logback-spring-prod.xml
Labels: zap, BE, infrastructure

#472 백엔드 CD 돌아가지 않는 오류 해결
  .github/workflows/backend_cd.yml
  .github/workflows/backend_cd_prod.yml
Labels: bug, zap, BE

#470 헤더 반응형 대응
  frontend/src/assets/images/Hamburger.tsx
  frontend/src/assets/images/index.ts
  frontend/src/components/Header/Header.style.ts
  frontend/src/components/Header/Header.tsx
  frontend/src/hooks/utils/usePressESC.ts
  frontend/src/hooks/utils/useScrollDisable.ts
Labels: feature, FE

#485 카테고리 생성 시 생성된 카테고리 값 반환
  backend/src/main/java/codezap/category/controller/CategoryController.java
  backend/src/main/java/codezap/category/controller/SpringDocCategoryController.java
  backend/src/main/java/codezap/category/dto/response/CreateCategoryResponse.java
  backend/src/main/java/codezap/category/service/CategoryService.java
  backend/src/test/java/codezap/category/controller/CategoryControllerTest.java
  backend/src/test/java/codezap/category/service/CategoryServiceTest.java
Labels: refactor, zap, BE

#488 백엔드 cd runner 결정 로직 변경
  .github/workflows/backend_cd.yml
  .github/workflows/backend_cd_prod.yml
Labels: bug, BE

#491 코드 에디터에서 확장자명에 따라 문법 하이라이팅 기능
  frontend/package-lock.json
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/components/SourceCodeEditor/SourceCodeEditor.tsx
Labels: feature, FE

#486 태그 관련 디자인 리팩토링
  frontend/src/components/TagButton/TagButton.style.ts
  frontend/src/components/TagButton/TagButton.tsx
  frontend/src/components/TagInput/TagInput.style.ts
  frontend/src/components/TagInput/TagInput.tsx
  frontend/src/components/TemplateCard/TemplateCard.style.ts
  frontend/src/components/TemplateCard/TemplateCard.tsx
  frontend/src/components/TemplateEdit/TemplateEdit.style.ts
  frontend/src/components/TemplateEdit/TemplateEdit.tsx
  frontend/src/components/TemplateItem/TemplateItem.tsx
  frontend/src/mocks/template.json
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
Labels: FE, refactor

#494 카테고리 편집(변경/삭제) 기능 구현
  frontend/src/api/categories.ts
  frontend/src/api/customFetch.ts
  frontend/src/api/index.ts
  frontend/src/assets/images/index.ts
  frontend/src/assets/images/setting.svg
  frontend/src/assets/images/spinArrow.svg
  frontend/src/components/CategoryEditModal/CategoryEditModal.style.ts
  frontend/src/components/CategoryEditModal/CategoryEditModal.tsx
  frontend/src/components/CategoryFilterMenu/CategoryFilterMenu.style.ts
  frontend/src/components/CategoryFilterMenu/CategoryFilterMenu.tsx
  frontend/src/components/Heading/Heading.style.ts
  frontend/src/components/Heading/Heading.tsx
  frontend/src/components/Modal/Modal.style.ts
  frontend/src/components/Modal/Modal.tsx
  frontend/src/components/TemplateEdit/TemplateEdit.tsx
  frontend/src/components/Text/Text.style.ts
  frontend/src/components/Text/Text.tsx
  frontend/src/components/index.ts
  frontend/src/hooks/category/index.ts
  frontend/src/hooks/category/useCategoryNameValidation.ts
  frontend/src/index.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.spec.tsx
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
  frontend/src/queries/category/index.ts
  frontend/src/queries/category/useCategoryDeleteMutation.ts
  frontend/src/queries/category/useCategoryEditMutation.ts
  frontend/src/types/api.ts
  frontend/src/types/index.ts
Labels: feature, FE

#475 fe 슬랙 알람 워크플로 변수 secret에서 가져오도록 변경
  .github/workflows/ci_cd_fail_notification.yml
  .github/workflows/pr_notification.yml
  .github/workflows/review_notification.yml
Labels: bug, FE

#498 cd-prod deploy 로직 수정
  .github/workflows/backend_cd_prod.yml
Labels: bug, BE

#490 카테고리 안내 메세지 및 생성 후 자동 선택 기능 추가
  frontend/src/api/categories.ts
  frontend/src/components/Dropdown/Dropdown.style.ts
  frontend/src/components/Guide/Guide.style.ts
  frontend/src/components/Guide/Guide.tsx
  frontend/src/components/Input/Input.style.ts
  frontend/src/components/Input/Input.tsx
  frontend/src/components/TemplateEdit/TemplateEdit.tsx
  frontend/src/components/index.ts
  frontend/src/queries/category/useCategoryUploadMutation.ts
Labels: feature, FE

#497 backend CI DB를 mysql로 변경
  .github/workflows/backend_ci.yml
Labels: refactor, BE

#499 전체 선택 버튼 클릭시 선택 안된 템플릿 흐리게 만들기
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/SourceCodeEditor/SourceCodeEditor.tsx
  frontend/src/components/TemplateEdit/TemplateEdit.tsx
  frontend/src/hooks/template/useTemplateEdit.ts
  frontend/src/hooks/template/useTemplateUpload.ts
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.spec.tsx
  frontend/src/service/validates.ts
Labels: feature, FE

#500 생성한 템플릿이 아무 것도 없을 경우, 새 템플릿 추가 버튼 보이도록 변경
  frontend/src/components/TagButton/TagButton.style.ts
  frontend/src/components/TemplateCard/TemplateCard.style.ts
  frontend/src/components/TemplateCard/TemplateCard.tsx
  frontend/src/components/TemplateGrid/TemplateGrid.style.ts
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.style.ts
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
  frontend/src/pages/TemplatePage/TemplatePage.tsx
  frontend/src/queries/template/useTemplateDeleteMutation.ts
Labels: feature, FE

#474 be 슬랙 알람 워크플로 변수 secret에서 가져오도록 변경
  .github/workflows/ci_cd_fail_notification.yml
  .github/workflows/pr_notification.yml
  .github/workflows/review_notification.yml
Labels: bug, BE

#430 flyway 설정 추가
  backend/build.gradle
  backend/src/main/java/codezap/global/flyway/FlywayRepairConfiguration.java
  backend/src/main/resources/db/migration/V1__init.sql
Labels: feature, BE

#501 프론트엔드 CD 파일 오타 수정
  .github/workflows/frontend_cd.yml
Labels: bug, FE, zap

#502 CI 시에 db yml 가져오는 step 추가
  .github/workflows/backend_ci.yml
  backend/build.gradle
Labels: bug, BE

#503 working-directory 상대 경로 변경
  .github/workflows/backend_ci.yml
Labels: BE

#506 dev 서버의 로그 저장소 변경
  .github/workflows/backend_cd.yml
  .github/workflows/backend_cd_prod.yml
  backend/src/main/resources/logback-spring.xml
  backend/src/main/resources/logger/logback-spring-dev.xml
Labels: bug, BE

#509 '내 템플릿' 페이지의 페이징 버튼 디자인 리팩토링
  frontend/src/api/templates.ts
  frontend/src/components/PagingButton/PagingButton.stories.tsx
  frontend/src/components/PagingButton/PagingButton.style.ts
  frontend/src/components/PagingButton/PagingButton.tsx
  frontend/src/components/PagingButtons/PagingButtons.stories.tsx
  frontend/src/components/PagingButtons/PagingButtons.style.ts
  frontend/src/components/PagingButtons/PagingButtons.tsx
  frontend/src/components/index.ts
  frontend/src/mocks/handlers.ts
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
  frontend/src/types/api.ts
Labels: FE, refactor

#517 전체 템플릿 조회 명세 변경 및 카테고리 길이 제약조건 실패 문서 추가
  backend/src/main/java/codezap/category/controller/SpringDocCategoryController.java
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
  backend/src/main/java/codezap/template/dto/response/FindAllTemplatesResponse.java
  backend/src/main/java/codezap/template/dto/response/FindMemberResponse.java
  backend/src/main/java/codezap/template/dto/response/FindTemplateResponse.java
Labels: documentation, BE

#477 템플릿 도메인 서비스 책임 분리
  backend/src/main/java/codezap/auth/dto/response/LoginResponse.java
  backend/src/main/java/codezap/category/controller/CategoryController.java
  backend/src/main/java/codezap/category/domain/Category.java
  backend/src/main/java/codezap/category/service/CategoryService.java
  backend/src/main/java/codezap/category/service/CategoryTemplateService.java
  backend/src/main/java/codezap/category/service/facade/MemberCategoryApplicationService.java
  backend/src/main/java/codezap/category/service/facade/MemberCategoryTemplateApplicationService.java
  backend/src/main/java/codezap/member/service/MemberService.java
  backend/src/main/java/codezap/tag/controller/SpringDocTagController.java
  backend/src/main/java/codezap/tag/controller/TagController.java
  backend/src/main/java/codezap/tag/domain/Tag.java
  backend/src/main/java/codezap/tag/dto/response/FindAllTagsResponse.java
  backend/src/main/java/codezap/tag/dto/response/FindTagResponse.java
  backend/src/main/java/codezap/tag/repository/TagJpaRepository.java
  backend/src/main/java/codezap/tag/repository/TagRepository.java
  backend/src/main/java/codezap/tag/repository/TemplateTagJpaRepository.java
  backend/src/main/java/codezap/tag/repository/TemplateTagRepository.java
  backend/src/main/java/codezap/tag/service/TemplateTagService.java
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
  backend/src/main/java/codezap/template/controller/TemplateController.java
  backend/src/main/java/codezap/template/domain/Template.java
  backend/src/main/java/codezap/template/domain/TemplateTag.java
  backend/src/main/java/codezap/template/dto/response/FindAllTemplateItemResponse.java
  backend/src/main/java/codezap/template/dto/response/FindAllTemplatesResponse.java
  backend/src/main/java/codezap/template/dto/response/FindTemplateResponse.java
  backend/src/main/java/codezap/template/repository/SourceCodeJpaRepository.java
  backend/src/main/java/codezap/template/repository/SourceCodeRepository.java
  backend/src/main/java/codezap/template/service/SourceCodeService.java
  backend/src/main/java/codezap/template/service/TemplateApplicationService.java
  backend/src/main/java/codezap/template/service/TemplateService.java
  backend/src/main/java/codezap/template/service/ThumbnailService.java
  backend/src/main/java/codezap/template/service/facade/CategoryTemplateApplicationService.java
  backend/src/main/java/codezap/template/service/facade/MemberTemplateApplicationService.java
  backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
  backend/src/main/resources/application-local.yml
  backend/src/test/java/codezap/category/controller/CategoryControllerTest.java
  backend/src/test/java/codezap/category/service/CategoryServiceTest.java
  backend/src/test/java/codezap/category/service/CategoryTemplateServiceTest.java
  backend/src/test/java/codezap/global/MockMvcTest.java
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
  backend/src/test/java/codezap/template/repository/FakeSourceCodeRepository.java
  backend/src/test/java/codezap/template/repository/FakeTagRepository.java
  backend/src/test/java/codezap/template/repository/FakeTemplateRepository.java
  backend/src/test/java/codezap/template/repository/FakeTemplateTagRepository.java
  backend/src/test/java/codezap/template/service/TagSearchTest.java
  backend/src/test/java/codezap/template/service/TemplateServiceSearchTest.java
  backend/src/test/java/codezap/template/service/TemplateServiceTest.java
Labels: refactor, BE

#519 favicon 추가, head의 title 변경
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/webpack.common.js
Labels: feature, FE

#518 HTTP 요청과 응답의 Thread UUID가 출력되지 않는 버그 해결
  backend/src/main/java/codezap/global/logger/MDCFilter.java
  backend/src/main/java/codezap/global/logger/RequestResponseLogger.java
  backend/src/main/resources/logger/file/error-appender.xml
  backend/src/main/resources/logger/file/info-appender.xml
  backend/src/main/resources/logger/file/warn-appender.xml
Labels: bug, BE, infrastructure

#516 '내 템플릿' 페이지의 태그 필터 박스 위치/디자인 리팩토링
  frontend/src/components/TagButton/TagButton.style.ts
  frontend/src/components/TagFilterMenu/TagFilterMenu.stories.tsx
  frontend/src/components/TagFilterMenu/TagFilterMenu.style.ts
  frontend/src/components/TagFilterMenu/TagFilterMenu.tsx
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
  frontend/src/utils/index.ts
  frontend/src/utils/remToPx.ts
Labels: FE, refactor

#527 스크롤바 커스텀 디자인
  frontend/src/style/GlobalStyles.tsx
Labels: feature, FE

#526 Modal 컴포넌트 완성
  frontend/src/components/CategoryEditModal/CategoryEditModal.tsx
  frontend/src/components/Modal/Modal.style.ts
  frontend/src/components/Modal/Modal.tsx
Labels: FE, refactor

#522 템플릿 업로드 페이지 - 카테고리 글자수 제한, 로딩 UI 추가
  frontend/src/components/Input/Input.style.ts
  frontend/src/components/LoadingBall/LoadingBall.style.ts
  frontend/src/components/LoadingBall/LoadingBall.tsx
  frontend/src/components/TemplateEdit/TemplateEdit.tsx
  frontend/src/components/index.ts
  frontend/src/hooks/utils/index.ts
  frontend/src/hooks/utils/useLoaderDelay.ts
  frontend/src/service/validates.ts
Labels: feature, FE

#528 프론트엔드 CD 파일 오타 수정
  .github/workflows/frontend_cd.yml
Labels: bug, FE

#539 페이지네이션 시에 페이지의 시작 인덱스를 1로 지정해주는 옵션 제거
  backend/src/main/resources/application-local.yml
Labels: feature, BE

#529 테스트 시 DB 격리 및 레포지토리 테스트를 위한 베이스 어노테이션 생성
  backend/src/test/java/codezap/global/DatabaseCleaner.java
  backend/src/test/java/codezap/global/DatabaseIsolation.java
  backend/src/test/java/codezap/global/repository/JpaRepositoryTest.java
Labels: refactor, zap, BE

#535 구경가기 페이지
  frontend/.gitignore
  frontend/src/api/templates.ts
  frontend/src/components/Header/Header.tsx
  frontend/src/hooks/authentication/index.ts
  frontend/src/hooks/authentication/useCheckLoginState.ts
  frontend/src/mocks/handlers.ts
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.style.ts
  frontend/src/pages/TemplateExplorePage/TemplateExplorePage.style.ts
  frontend/src/pages/TemplateExplorePage/TemplateExplorePage.tsx
  frontend/src/pages/TemplateListPage/TemplateListPage.tsx
  frontend/src/pages/index.ts
  frontend/src/queries/template/index.ts
  frontend/src/queries/template/useTemplateExploreQuery.ts
  frontend/src/queries/template/useTemplateListQuery.spec.tsx
  frontend/src/queries/template/useTemplateListQuery.ts
  frontend/src/routes/router.tsx
  frontend/src/types/api.ts
  frontend/src/types/template.ts
Labels: feature, FE

#544 태그 API 요청 엔드포인트 변경 / 태그가 0개 일 때, 태그박스 자리에 0이 렌더링 되는 문제 해결
  frontend/src/api/tags.ts
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
Labels: bug, FE

#530 템플릿 조회에서 동적 쿼리 생성을 위한 Specification 구현
  backend/src/main/java/codezap/template/repository/TemplateJpaRepository.java
  backend/src/main/java/codezap/template/repository/TemplateRepository.java
  backend/src/main/java/codezap/template/repository/TemplateSpecification.java
  backend/src/test/java/codezap/template/repository/FakeTemplateRepository.java
  backend/src/test/java/codezap/template/repository/TemplateRepositoryFindAllTest.java
Labels: refactor, zap, BE

#541 카테고리 편집 메뉴 및 모달 리팩토링 (2차 UT 및 QA 반영)
  frontend/src/components/CategoryEditModal/CategoryEditModal.style.ts
  frontend/src/components/CategoryEditModal/CategoryEditModal.tsx
  frontend/src/components/CategoryFilterMenu/CategoryFilterMenu.tsx
  frontend/src/components/Modal/Modal.style.ts
  frontend/src/hooks/category/useCategoryNameValidation.ts
  frontend/src/mocks/handlers.ts
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
Labels: FE, refactor

#543 Header 경로 변경, 엔드포인트 상수화
  frontend/src/api/authentication.ts
  frontend/src/api/categories.ts
  frontend/src/api/templates.ts
  frontend/src/components/Header/Header.tsx
  frontend/src/pages/LoginPage/LoginPage.tsx
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
  frontend/src/queries/authentication/useLoginMutation.ts
  frontend/src/queries/authentication/useSignupMutation.ts
  frontend/src/routes/endPoints.ts
  frontend/src/routes/index.ts
  frontend/src/routes/router.tsx
Labels: FE, refactor

#545 Templatepage 2차 유저피드백 반영
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/images/clock.svg
  frontend/src/assets/images/index.ts
  frontend/src/assets/images/person.svg
  frontend/src/components/SourceCodeEditor/SourceCodeEditor.style.ts
  frontend/src/components/SourceCodeEditor/SourceCodeEditor.tsx
  frontend/src/components/TemplateCard/TemplateCard.style.ts
  frontend/src/components/TemplateCard/TemplateCard.tsx
  frontend/src/mocks/templateList.json
  frontend/src/pages/LandingPage/LandingPage.tsx
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.spec.tsx
  frontend/src/pages/TemplatePage/TemplatePage.style.ts
  frontend/src/pages/TemplatePage/TemplatePage.tsx
  frontend/src/types/template.ts
Labels: FE, refactor

#546 로그인 / 회원가입 페이지 반응형 추가, 쨉쨉이 로고 추가
  frontend/src/api/tags.ts
  frontend/src/assets/images/index.ts
  frontend/src/assets/images/zapzap.svg
  frontend/src/components/Text/Text.style.ts
  frontend/src/pages/LoginPage/LoginPage.style.ts
  frontend/src/pages/LoginPage/LoginPage.tsx
  frontend/src/pages/SignupPage/SignupPage.style.ts
  frontend/src/pages/SignupPage/SignupPage.tsx
  frontend/src/pages/TemplateExplorePage/TemplateExplorePage.tsx
  frontend/src/queries/authentication/useLogoutMutation.ts
  frontend/src/routes/endPoints.ts
Labels: feature, FE

#532 비회원 조회 가능하도록 태그, 카테고리, 템플릿 조회 시 MemberDto 제거
  backend/src/main/java/codezap/auth/provider/basic/BasicAuthCredentialProvider.java
  backend/src/main/java/codezap/auth/service/AuthService.java
  backend/src/main/java/codezap/category/controller/CategoryController.java
  backend/src/main/java/codezap/category/controller/SpringDocCategoryController.java
  backend/src/main/java/codezap/category/service/facade/MemberCategoryApplicationService.java
  backend/src/main/java/codezap/member/controller/MemberController.java
  backend/src/main/java/codezap/member/repository/MemberJpaRepository.java
  backend/src/main/java/codezap/member/repository/MemberRepository.java
  backend/src/main/java/codezap/member/service/MemberService.java
  backend/src/main/java/codezap/tag/controller/SpringDocTagController.java
  backend/src/main/java/codezap/tag/controller/TagController.java
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
  backend/src/main/java/codezap/template/controller/TemplateController.java
  backend/src/main/java/codezap/template/dto/response/FindAllTemplateItemResponse.java
  backend/src/main/java/codezap/template/dto/response/FindAllTemplatesResponse.java
  backend/src/main/java/codezap/template/dto/response/FindTemplateResponse.java
  backend/src/main/java/codezap/template/service/TemplateService.java
  backend/src/main/java/codezap/template/service/facade/MemberTemplateApplicationService.java
  backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
  backend/src/test/java/codezap/category/controller/CategoryControllerTest.java
  backend/src/test/java/codezap/member/controller/MemberControllerTest.java
  backend/src/test/java/codezap/member/repository/FakeMemberRepository.java
  backend/src/test/java/codezap/member/repository/MemberJpaRepositoryTest.java
  backend/src/test/java/codezap/member/service/MemberServiceTest.java
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
  backend/src/test/java/codezap/template/service/TemplateServiceTest.java
Labels: feature, zap, BE

#549 비회원이 템플릿 업로드 페이지 이동 시, 페이지가 렌더링되는 버그 임시 해결
  frontend/src/components/Header/Header.tsx
Labels: bug, FE

#552 템플릿 삭제 시 다른 리소스 삭제 순서 변경
  backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
Labels: bug, BE

#554 카테고리가 없는 사용자가 카테고리를 생성하지 못하는 문제 해결
  frontend/src/components/CategoryEditModal/CategoryEditModal.tsx
  frontend/src/components/CategoryFilterMenu/CategoryFilterMenu.tsx
Labels: bug, FE

#556 카테고리 생성 시 body에 값 추가
  backend/src/main/java/codezap/category/controller/CategoryController.java
  backend/src/main/java/codezap/category/service/facade/MemberCategoryApplicationService.java
  backend/src/test/java/codezap/category/controller/CategoryControllerTest.java
Labels: bug, BE

#559 tag 수정시 존재하는 태그가 사라지는 오류 수정
  backend/src/main/java/codezap/tag/service/TemplateTagService.java
Labels: bug, BE

#560 카테고리 요청 트리거 onKeyDown 이벤트로 변경
  frontend/src/components/TemplateEdit/TemplateEdit.tsx
Labels: bug, FE

#557 카테고리 필터 메뉴 모바일 반응형 디자인 구현
  frontend/src/assets/images/books.svg
  frontend/src/assets/images/chevron2.svg
  frontend/src/assets/images/index.ts
  frontend/src/components/CategoryFilterMenu/CategoryFilterMenu.style.ts
  frontend/src/components/CategoryFilterMenu/CategoryFilterMenu.tsx
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.style.ts
Labels: feature, FE

#561 템플릿 카드에 member 추가
  frontend/src/components/TemplateCard/TemplateCard.style.ts
  frontend/src/components/TemplateCard/TemplateCard.tsx
Labels: feature, FE, refactor

#562 fix(service): 썸네일 소스코드 삭제 안되는 문제 해결
  backend/src/main/java/codezap/template/service/SourceCodeService.java
Labels: bug, BE

#564 태그 중복 제거 문제 해결
  backend/src/main/java/codezap/tag/repository/TemplateTagJpaRepository.java
  backend/src/main/java/codezap/tag/repository/TemplateTagRepository.java
  backend/src/main/java/codezap/tag/service/TemplateTagService.java
  backend/src/test/java/codezap/tag/repository/TemplateTagJpaRepositoryTest.java
  backend/src/test/java/codezap/template/repository/FakeTemplateTagRepository.java
Labels: bug, BE

#563 TagInput 첫 글자 삭제되지 않는 bug 수정 및 onBlur 일때 태그 등록되도록 변경
  frontend/src/components/TagInput/TagInput.tsx
  frontend/src/hooks/template/useTemplateUpload.ts
  frontend/src/hooks/utils/useInputWithValidate.ts
Labels: bug, FE

#569 프론트엔드 CD 파일 경로 수정
  .github/workflows/frontend_cd.yml
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.style.ts
Labels: FE, refactor
