Repository woowacourse-teams/2024-code-zap, pull requests merged in 2024-12, with the labels that each got.

#940 MSW 폴더 구조 변경 및 mockResponse 유틸 response 생성
  frontend/jest.config.ts
  frontend/setupTests.ts
  frontend/src/components/TemplateCard/TemplateCard.stories.tsx
  frontend/src/mocks/fixtures/categoryList.json
  frontend/src/mocks/fixtures/tagList.json
  frontend/src/mocks/fixtures/templateList.json
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/handlers/authentication.ts
  frontend/src/mocks/handlers/category.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/like.ts
  frontend/src/mocks/handlers/member.ts
  frontend/src/mocks/handlers/tag.ts
  frontend/src/mocks/handlers/template.ts
  frontend/src/mocks/settings/browser.ts
  frontend/src/mocks/settings/fileMock.js
  frontend/src/mocks/settings/fileTransformer.js
  frontend/src/mocks/settings/server.ts
  frontend/src/pages/MyTemplatesPage/components/CategoryEditModal/CategoryEditModal.tsx
  frontend/src/pages/MyTemplatesPage/components/CategoryFilterMenu/CategoryFilterMenu.stories.tsx
  frontend/src/pages/MyTemplatesPage/components/TagFilterMenu/TagFilterMenu.stories.tsx
  frontend/src/pages/TemplatePage/hooks/useTemplate.ts
  frontend/src/queries/categories/useCategoryDeleteMutation.ts
  frontend/src/queries/categories/useCategoryListQuery.spec.tsx
  frontend/src/queries/tags/useTagListQuery.spec.tsx
  frontend/src/queries/templates/useTemplateListQuery.spec.tsx
  frontend/src/types/fetch.ts
  frontend/src/types/index.ts
  frontend/src/utils/mockResponse.ts
Labels: FE, refactor

#941 서버 scale-in으로 인한 CD 코드 변경
  .github/workflows/backend_cd.yml
Labels: refactor, BE, infrastructure

#926 검색시 boolean mode로 변경
  backend/src/main/java/codezap/template/repository/FullTextFunctionContributor.java
  backend/src/main/java/codezap/template/repository/TemplateSearchExpressionProvider.java
  backend/src/main/java/codezap/template/repository/strategy/FullTextSearchSearchStrategy.java
  backend/src/main/java/codezap/template/repository/strategy/LikeSearchStrategy.java
  backend/src/test/java/codezap/global/repository/RepositoryTest.java
  backend/src/test/java/codezap/template/repository/TemplateSearchRepositoryTest.java
  backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java
Labels: refactor, BE

#943 QueryDSL QClass 생성 경로를 gitignore에 등록
  backend/.gitignore
Labels: refactor, BE

#939 템플릿 생성 및 수정시 파일명 랜덤 생성 및 중복호출 막기, 공개 범위 설정 radio UI로 변경
  frontend/.storybook/preview.tsx
  frontend/src/api/authentication.ts
  frontend/src/components/Radio/Radio.stories.tsx
  frontend/src/components/Radio/Radio.style.ts
  frontend/src/components/Radio/Radio.tsx
  frontend/src/components/index.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/usePreventDuplicateMutation.ts
  frontend/src/pages/TemplateEditPage/TemplateEditPage.style.ts
  frontend/src/pages/TemplateEditPage/TemplateEditPage.tsx
  frontend/src/pages/TemplateUploadPage/TemplateUploadPage.style.ts
  frontend/src/pages/TemplateUploadPage/TemplateUploadPage.tsx
  frontend/src/queries/templates/useTemplateEditMutation.ts
  frontend/src/queries/templates/useTemplateUploadMutation.ts
  frontend/src/service/constants.ts
  frontend/src/service/generateUniqueFilename.ts
  frontend/src/service/validates.ts
  frontend/src/types/template.ts
Labels: FE, refactor

#947 운영 환경에서 Swagger 문서 및 API 차단
  backend/src/main/java/codezap/global/swagger/SpringDocConfiguration.java
  backend/src/main/resources/application-swagger.yml
Labels: documentation, BE

#953 운영 환경, 메서드 로그 전략 변경
  backend/src/main/java/codezap/global/logger/MDCFilter.java
  backend/src/main/java/codezap/global/logger/MethodExecutionTimeAspect.java
  backend/src/main/resources/logger/logback-spring-prod.xml
Labels: refactor, BE

#946 인텔리제이 플러그인 구현
  intelliJ-plugin/.gitignore
  intelliJ-plugin/build.gradle.kts
  intelliJ-plugin/gradle.properties
  intelliJ-plugin/gradle/wrapper/gradle-wrapper.jar
  intelliJ-plugin/gradle/wrapper/gradle-wrapper.properties
  intelliJ-plugin/gradlew
  intelliJ-plugin/gradlew.bat
  intelliJ-plugin/settings.gradle.kts
  intelliJ-plugin/src/main/java/com/codezap/action/CreateTemplateAction.java
  intelliJ-plugin/src/main/java/com/codezap/client/CodeZapClient.java
  intelliJ-plugin/src/main/java/com/codezap/client/HttpMethod.java
  intelliJ-plugin/src/main/java/com/codezap/client/MakeResponse.java
  intelliJ-plugin/src/main/java/com/codezap/dto/request/CreateSourceCodeRequest.java
  intelliJ-plugin/src/main/java/com/codezap/dto/request/LoginRequest.java
  intelliJ-plugin/src/main/java/com/codezap/dto/request/TemplateCreateRequest.java
  intelliJ-plugin/src/main/java/com/codezap/dto/response/FindAllCategoriesResponse.java
  intelliJ-plugin/src/main/java/com/codezap/dto/response/FindCategoryResponse.java
  intelliJ-plugin/src/main/java/com/codezap/dto/response/LoginResponse.java
  intelliJ-plugin/src/main/java/com/codezap/exception/ErrorType.java
  intelliJ-plugin/src/main/java/com/codezap/exception/PluginException.java
  intelliJ-plugin/src/main/java/com/codezap/message/ApiEndpoints.java
  intelliJ-plugin/src/main/java/com/codezap/message/PrintMessage.java
  intelliJ-plugin/src/main/java/com/codezap/panel/CreateTemplatePanel.java
  intelliJ-plugin/src/main/java/com/codezap/panel/LoginInputPanel.java
  intelliJ-plugin/src/main/java/com/codezap/panel/SwingComponentAdder.java
  intelliJ-plugin/src/main/java/com/codezap/service/CategoryService.java
  intelliJ-plugin/src/main/java/com/codezap/service/LoginService.java
  intelliJ-plugin/src/main/java/com/codezap/service/TemplateService.java
  intelliJ-plugin/src/main/resources/META-INF/plugin.xml
  intelliJ-plugin/src/main/resources/META-INF/pluginIcon.svg
  intelliJ-plugin/src/main/resources/icons/background_logo.png
  intelliJ-plugin/src/main/resources/icons/non_background_logo.png
Labels: feature, BE

#923 문의하기 구글 스프레드시트 API 요청 책임을 클라이언트에서 서버로 변경
  backend/src/main/java/codezap/voc/config/VocClientHttpRequestInterceptor.java
  backend/src/main/java/codezap/voc/config/VocConfiguration.java
  backend/src/main/java/codezap/voc/config/VocProperties.java
  backend/src/main/java/codezap/voc/config/VocResponseErrorHandler.java
  backend/src/main/java/codezap/voc/controller/SpringDocVocController.java
  backend/src/main/java/codezap/voc/controller/VocController.java
  backend/src/main/java/codezap/voc/dto/VocRequest.java
  backend/src/main/java/codezap/voc/service/VocService.java
  backend/src/main/resources/application-voc.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/codezap/global/MockMvcTest.java
  backend/src/test/java/codezap/voc/config/VocPropertiesTest.java
  backend/src/test/java/codezap/voc/controller/VocControllerTest.java
  backend/src/test/java/codezap/voc/dto/VocRequestTest.java
  backend/src/test/java/codezap/voc/service/VocServiceTest.java
Labels: feature, BE

#963 검색시 발생하는 500 에러 해결
  backend/src/main/java/codezap/template/repository/strategy/FullTextSearchSearchStrategy.java
  backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java
Labels: bug, zap, BE

#964 검색시 500 에러 해결
  backend/src/main/java/codezap/template/repository/strategy/FullTextSearchSearchStrategy.java
  backend/src/main/java/codezap/voc/config/VocClientHttpRequestInterceptor.java
  backend/src/main/java/codezap/voc/config/VocConfiguration.java
  backend/src/main/java/codezap/voc/config/VocProperties.java
  backend/src/main/java/codezap/voc/config/VocResponseErrorHandler.java
  backend/src/main/java/codezap/voc/controller/SpringDocVocController.java
  backend/src/main/java/codezap/voc/controller/VocController.java
  backend/src/main/java/codezap/voc/dto/VocRequest.java
  backend/src/main/java/codezap/voc/service/VocService.java
  backend/src/main/resources/application-voc.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/codezap/global/MockMvcTest.java
  backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java
  backend/src/test/java/codezap/voc/config/VocPropertiesTest.java
  backend/src/test/java/codezap/voc/controller/VocControllerTest.java
  backend/src/test/java/codezap/voc/dto/VocRequestTest.java
  backend/src/test/java/codezap/voc/service/VocServiceTest.java
Labels: bug, BE

#927 [BUG] 좋아요 반 정규화로 인한 템플릿 좋아요 시 해당 템플릿의 ModifiedAt 변경 문제
  backend/src/main/java/codezap/global/auditing/BaseTimeEntity.java
  backend/src/main/java/codezap/global/auditing/SkipModifiedAtBaseTimeEntity.java
  backend/src/main/java/codezap/template/domain/Template.java
  backend/src/test/java/codezap/fixture/CategoryFixture.java
  backend/src/test/java/codezap/likes/service/LikesServiceTest.java
  backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java
  backend/src/test/java/codezap/template/service/TemplateServiceTest.java
  backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
Labels: bug, BE

#961 최근순을 최근 수정순과 최근 생성순으로 나누어 구현
  frontend/src/api/index.ts
  frontend/src/api/templates.ts
  frontend/src/components/TemplateCard/TemplateCard.tsx
  frontend/src/hooks/useQueryParams.ts
  frontend/src/mocks/handlers/template.ts
  frontend/src/models/templates/.gitkeep
  frontend/src/models/templates/index.ts
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
  frontend/src/pages/TemplateExplorePage/TemplateExplorePage.tsx
  frontend/src/queries/templates/useTemplateExploreQuery.ts
  frontend/src/queries/templates/useTemplateListQuery.spec.tsx
  frontend/src/queries/templates/useTemplateListQuery.ts
  frontend/src/service/getSortingOptionByValue.ts
  frontend/src/types/api.ts
Labels: FE, refactor

#954 Authorization header를 사용하는 인증 클래스 생성
  backend/src/main/java/codezap/auth/configuration/AuthArgumentResolver.java
  backend/src/main/java/codezap/auth/configuration/AuthWebConfiguration.java
  backend/src/main/java/codezap/auth/controller/AuthController.java
  backend/src/main/java/codezap/auth/controller/SpringDocAuthController.java
  backend/src/main/java/codezap/auth/dto/Credential.java
  backend/src/main/java/codezap/auth/dto/LoginAndCredentialDto.java
  backend/src/main/java/codezap/auth/dto/LoginMember.java
  backend/src/main/java/codezap/auth/dto/response/LoginResponse.java
  backend/src/main/java/codezap/auth/manager/AuthorizationHeaderCredentialManager.java
  backend/src/main/java/codezap/auth/manager/CookieCredentialManager.java
  backend/src/main/java/codezap/auth/manager/CredentialManager.java
  backend/src/main/java/codezap/auth/provider/CredentialProvider.java
  backend/src/main/java/codezap/auth/provider/basic/BasicAuthCredentialProvider.java
  backend/src/main/java/codezap/auth/service/AuthService.java
  backend/src/test/java/codezap/auth/configuration/AuthArgumentResolverTest.java
  backend/src/test/java/codezap/auth/manager/AuthorizationHeaderCredentialManagerTest.java
  backend/src/test/java/codezap/auth/manager/CookieCredentialManagerTest.java
  backend/src/test/java/codezap/auth/manager/CredentialTest.java
  backend/src/test/java/codezap/auth/provider/PlainCredentialProvider.java
  backend/src/test/java/codezap/auth/provider/basic/BasicAuthCredentialProviderTest.java
  backend/src/test/java/codezap/auth/service/AuthServiceTest.java
  backend/src/test/java/codezap/category/controller/CategoryControllerTest.java
  backend/src/test/java/codezap/global/MockMvcTest.java
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
Labels: refactor, BE

#974 타인의 템플릿 페이지에서 노출된 업로드 버튼 오류 수정
  frontend/src/index.tsx
  frontend/src/mocks/handlers/category.ts
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
  frontend/src/pages/MyTemplatesPage/components/TemplateListSection/TemplateListSection.tsx
Labels: bug, FE, zap

#976 msw 핸들러 추가 및 msw 실행 스크립트 추가
  frontend/package.json
  frontend/src/index.tsx
  frontend/src/mocks/handlers/authentication.ts
  frontend/src/mocks/handlers/like.ts
  frontend/src/mocks/handlers/template.ts
  frontend/src/utils/mockResponse.ts
  frontend/webpack.dev.js
Labels: FE, refactor

#978 태그 동시 생성 시 중복 문제 해결
  backend/build.gradle
  backend/src/main/java/codezap/global/retry/RetryConfiguration.java
  backend/src/main/java/codezap/tag/domain/Tag.java
  backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
  backend/src/main/resources/db/migration/V10__add_constraint_unique_tag.sql
  backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
Labels: bug, BE

#982 MyTemplate -> MemberTemplate 으로 명칭 변경
  frontend/src/components/PagingButtons/PagingButtons.tsx
  frontend/src/pages/MemberTemplatePage/MemberTemplatePage.style.ts
  frontend/src/pages/MemberTemplatePage/MemberTemplatePage.tsx
  frontend/src/pages/MemberTemplatePage/components/CategoryEditModal/CategoryEditModal.style.ts
  frontend/src/pages/MemberTemplatePage/components/CategoryEditModal/CategoryEditModal.tsx
  frontend/src/pages/MemberTemplatePage/components/CategoryFilterMenu/CategoryFilterMenu.stories.tsx
  frontend/src/pages/MemberTemplatePage/components/CategoryFilterMenu/CategoryFilterMenu.style.ts
  frontend/src/pages/MemberTemplatePage/components/CategoryFilterMenu/CategoryFilterMenu.tsx
  frontend/src/pages/MemberTemplatePage/components/CategoryListSection/CategoryListSection.style.ts
  frontend/src/pages/MemberTemplatePage/components/CategoryListSection/CategoryListSection.tsx
  frontend/src/pages/MemberTemplatePage/components/CategoryListSection/CategoryListSectionSkeleton.tsx
  frontend/src/pages/MemberTemplatePage/components/ConfirmDeleteModal/ConfirmDeleteModal.tsx
  frontend/src/pages/MemberTemplatePage/components/NewTemplateButton/NewTemplateButton.style.ts
  frontend/src/pages/MemberTemplatePage/components/NewTemplateButton/NewTemplateButton.tsx
  frontend/src/pages/MemberTemplatePage/components/TagFilterMenu/TagFilterMenu.stories.tsx
  frontend/src/pages/MemberTemplatePage/components/TagFilterMenu/TagFilterMenu.style.ts
  frontend/src/pages/MemberTemplatePage/components/TagFilterMenu/TagFilterMenu.tsx
  frontend/src/pages/MemberTemplatePage/components/TagListSection/TagListSection.tsx
  frontend/src/pages/MemberTemplatePage/components/TagListSection/TagListSectionSkeleton.tsx
  frontend/src/pages/MemberTemplatePage/components/TemplateDeleteSelection/TemplateDeleteSelection.tsx
  frontend/src/pages/MemberTemplatePage/components/TemplateGrid/TemplateGrid.style.ts
  frontend/src/pages/MemberTemplatePage/components/TemplateGrid/TemplateGrid.tsx
  frontend/src/pages/MemberTemplatePage/components/TemplateListSection/TemplateListSection.tsx
  frontend/src/pages/MemberTemplatePage/components/TemplateListSection/TemplateListSectionLoading.style.ts
  frontend/src/pages/MemberTemplatePage/components/TemplateListSection/TemplateListSectionLoading.tsx
  frontend/src/pages/MemberTemplatePage/components/TopBanner/TopBanner.style.ts
  frontend/src/pages/MemberTemplatePage/components/TopBanner/TopBanner.tsx
  frontend/src/pages/MemberTemplatePage/components/index.ts
  frontend/src/pages/MemberTemplatePage/hooks/index.ts
  frontend/src/pages/MemberTemplatePage/hooks/useFilteredTemplateList.ts
  frontend/src/pages/MemberTemplatePage/hooks/useSelectAndDeleteTemplateList.ts
  frontend/src/pages/MyLikedTemplatePage/MyLikedTemplatePage.tsx
  frontend/src/pages/TemplateExplorePage/TemplateExplorePage.tsx
  frontend/src/pages/index.ts
  frontend/src/routes/router.tsx
  frontend/src/service/amplitude/track.ts
Labels: FE, refactor

#983 문의하기 api 적용
  frontend/src/api/contact.ts
  frontend/src/components/ContactUs/ContactUs.tsx
  frontend/src/mocks/handlers/contact.ts
  frontend/src/routes/endPoints.ts
Labels: FE, refactor

#985 문의하기 글자수 제한 20자 → 10자 변경 및 상태코드 200 → 201로 수정
  backend/src/main/java/codezap/voc/controller/SpringDocVocController.java
  backend/src/main/java/codezap/voc/controller/VocController.java
  backend/src/main/java/codezap/voc/dto/VocRequest.java
  backend/src/test/java/codezap/voc/controller/VocControllerTest.java
  backend/src/test/java/codezap/voc/dto/VocRequestTest.java
Labels: bug, refactor, BE

#986 Tomcat HTTP gzip 압축 적용
  backend/src/main/resources/application-was.yml
  backend/src/main/resources/application.yml
Labels: BE, infrastructure

#987 Gradle test 작업에 fast-fail 옵션 추가
  backend/build.gradle
Labels: BE, infrastructure

#991 @Disabled 된 테스트 검토 및 사용하지 않는 메서드 제거
  backend/src/main/java/codezap/category/repository/CategoryRepository.java
  backend/src/main/java/codezap/category/service/CategoryService.java
  backend/src/main/java/codezap/tag/service/TagService.java
  backend/src/main/java/codezap/template/dto/request/CreateTemplateRequest.java
  backend/src/main/java/codezap/template/dto/request/UpdateTemplateRequest.java
  backend/src/main/java/codezap/template/repository/TemplateRepository.java
  backend/src/main/java/codezap/template/service/SourceCodeService.java
  backend/src/main/java/codezap/template/service/TemplateService.java
  backend/src/main/java/codezap/template/service/ThumbnailService.java
  backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
  backend/src/test/java/codezap/category/service/CategoryServiceTest.java
  backend/src/test/java/codezap/tag/service/TagServiceTest.java
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
  backend/src/test/java/codezap/template/repository/TemplateRepositoryTest.java
  backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java
  backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java
  backend/src/test/java/codezap/template/service/TemplateServiceTest.java
  backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
Labels: refactor, BE

#990 로그에 헤더 정보 수정 및 컨테이너 정보 추가
  backend/src/main/java/codezap/global/logger/RequestResponseLogger.java
Labels: BE, infrastructure

#996 Request DTO 변수명을 request로 통일
  backend/src/main/java/codezap/auth/controller/AuthController.java
  backend/src/main/java/codezap/auth/service/AuthService.java
  backend/src/main/java/codezap/category/controller/CategoryController.java
  backend/src/main/java/codezap/category/service/CategoryService.java
  backend/src/main/java/codezap/template/controller/TemplateController.java
  backend/src/main/java/codezap/template/service/SourceCodeService.java
  backend/src/main/java/codezap/template/service/TemplateService.java
  backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
Labels: refactor, BE
