Repository woowacourse-teams/2024-code-zap, pull requests merged in 2024-07, with the labels that each got.

#6 개발 환경 초기 설정
  .gitignore
  backend/.gitignore
  backend/.gitkeep
  backend/build.gradle
  backend/docker/docker-compose.yml
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/codezap/CodeZapApplication.java
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/codezap/CodeZapApplicationTests.java
Labels: zap, BE

#22 필수 API Swagger 작성
  backend/src/main/java/codezap/swagger/SpringDocConfiguration.java
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
  backend/src/main/java/codezap/template/controller/TemplateController.java
  backend/src/main/java/codezap/template/dto/request/CreateSnippetRequest.java
  backend/src/main/java/codezap/template/dto/request/CreateTemplateResponse.java
  backend/src/main/java/codezap/template/dto/response/CreateTemplateRequest.java
  backend/src/main/java/codezap/template/dto/response/FindAllSnippetByTemplateResponse.java
  backend/src/main/java/codezap/template/dto/response/FindAllTemplatesResponse.java
  backend/src/main/java/codezap/template/dto/response/FindMemberBySummaryResponse.java
  backend/src/main/java/codezap/template/dto/response/FindRepresentativeSnippetResponse.java
  backend/src/main/java/codezap/template/dto/response/FindTemplateByIdResponse.java
  backend/src/main/java/codezap/template/dto/response/FindTemplateBySummaryResponse.java
Labels: documentation, zap, BE

#29 feat(workflows): actions ci 파이프라인 구성
  .github/workflows/build.yml
  backend/src/main/resources/application-local.yml
Labels: feature, BE

#25 모든 엔티티 생성
  backend/build.gradle
  backend/src/main/java/codezap/extension/domain/Extension.java
  backend/src/main/java/codezap/global/domain/BaseTimeEntity.java
  backend/src/main/java/codezap/global/domain/JpaAuditingConfiguration.java
  backend/src/main/java/codezap/language/domain/Language.java
  backend/src/main/java/codezap/member/domain/Member.java
  backend/src/main/java/codezap/snippet/domain/Snippet.java
  backend/src/main/java/codezap/template/domain/Template.java
Labels: feature, BE

#32 CI 파이프라인 구성
  .github/workflows/build.yml
  backend/src/main/java/codezap/swagger/SpringDocConfiguration.java
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
  backend/src/main/java/codezap/template/controller/TemplateController.java
  backend/src/main/java/codezap/template/dto/request/CreateSnippetRequest.java
  backend/src/main/java/codezap/template/dto/request/CreateTemplateResponse.java
  backend/src/main/java/codezap/template/dto/response/CreateTemplateRequest.java
  backend/src/main/java/codezap/template/dto/response/FindAllSnippetByTemplateResponse.java
  backend/src/main/java/codezap/template/dto/response/FindAllTemplatesResponse.java
  backend/src/main/java/codezap/template/dto/response/FindMemberBySummaryResponse.java
  backend/src/main/java/codezap/template/dto/response/FindRepresentativeSnippetResponse.java
  backend/src/main/java/codezap/template/dto/response/FindTemplateByIdResponse.java
  backend/src/main/java/codezap/template/dto/response/FindTemplateBySummaryResponse.java
  backend/src/main/resources/application-local.yml
Labels: feature, BE

#33 모든 레포지토리 생성
  backend/src/main/java/codezap/extension/repository/ExtensionRepository.java
  backend/src/main/java/codezap/language/repository/LanguageRepository.java
  backend/src/main/java/codezap/member/domain/Member.java
  backend/src/main/java/codezap/member/repository/MemberRepository.java
  backend/src/main/java/codezap/snippet/repository/SnippetRepository.java
  backend/src/main/java/codezap/template/repository/TemplateRepository.java
Labels: feature, BE

#34 PR 템플릿 작성
  .github/pull_request_template.md
Labels: documentation

#36 템플릿 목록 조회 API 구현
  backend/src/main/java/codezap/global/domain/BaseTimeEntity.java
  backend/src/main/java/codezap/representative_snippet/domain/RepresentativeSnippet.java
  backend/src/main/java/codezap/representative_snippet/repository/RepresentativeSnippetRepository.java
  backend/src/main/java/codezap/snippet/domain/Snippet.java
  backend/src/main/java/codezap/template/controller/TemplateController.java
  backend/src/main/java/codezap/template/dto/response/FindAllTemplatesResponse.java
  backend/src/main/java/codezap/template/dto/response/FindMemberBySummaryResponse.java
  backend/src/main/java/codezap/template/dto/response/FindRepresentativeSnippetResponse.java
  backend/src/main/java/codezap/template/dto/response/FindTemplateBySummaryResponse.java
  backend/src/main/java/codezap/template/service/TemplateService.java
Labels: feature, BE

#39 템플릿 상세 조회 API 구현
  backend/src/main/java/codezap/snippet/repository/SnippetRepository.java
  backend/src/main/java/codezap/template/controller/TemplateController.java
  backend/src/main/java/codezap/template/dto/response/FindAllSnippetByTemplateResponse.java
  backend/src/main/java/codezap/template/dto/response/FindTemplateByIdResponse.java
  backend/src/main/java/codezap/template/dto/response/FindTemplateBySummaryResponse.java
  backend/src/main/java/codezap/template/repository/TemplateRepository.java
  backend/src/main/java/codezap/template/service/TemplateService.java
Labels: feature, BE

#42 CD 파이프라인 구축
  .github/workflows/deploy.yml
Labels: feature, BE, hackathon

#43 [FIX] CD 파이프라인 구축
  .github/workflows/deploy.yml
Labels: bug, BE, hackathon

#44 [FIX] CD 파이프라인 구축
  .github/workflows/deploy.yml
Labels: bug, BE

#45 [FIX] CD 파이프라인 구축
  .github/workflows/deploy.yml
  backend/src/main/java/codezap/TestController.java
Labels: bug, BE, hackathon

#46 [FIX] CD 파이프라인 구축 4
  .github/workflows/deploy.yml
Labels: bug, BE, hackathon

#53 prettier 설정, eslint-prettier 설정
  frontend/.eslintrc.cjs
  frontend/.prettierrc
  frontend/package-lock.json
  frontend/package.json
Labels: feature, FE, hackathon

#56 템플릿 생성 API 구현
  backend/build.gradle
  backend/src/main/java/codezap/extension/domain/Extension.java
  backend/src/main/java/codezap/extension/repository/ExtensionRepository.java
  backend/src/main/java/codezap/language/domain/Language.java
  backend/src/main/java/codezap/language/repository/LanguageRepository.java
  backend/src/main/java/codezap/representative_snippet/domain/RepresentativeSnippet.java
  backend/src/main/java/codezap/snippet/domain/Snippet.java
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
  backend/src/main/java/codezap/template/controller/TemplateController.java
  backend/src/main/java/codezap/template/domain/Template.java
  backend/src/main/java/codezap/template/dto/request/CreateTemplateRequest.java
  backend/src/main/java/codezap/template/dto/request/CreateTemplateResponse.java
  backend/src/main/java/codezap/template/service/TemplateService.java
Labels: feature, BE

#58 날짜 시간 형식 지정을 위한 직렬화 설정
  backend/src/main/java/codezap/global/DateTimeFormatConfiguration.java
  backend/src/main/java/codezap/global/SpringDocConfiguration.java
Labels: feature, BE

#59 SelectList 컴포넌트 구현 및 적용
  frontend/src/components/SelectList/SelectList.tsx
  frontend/src/components/SelectList/index.ts
  frontend/src/pages/Template.tsx
Labels: feature, FE, hackathon

#62 Template 업로드 페이지
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/SnippetEditor/SnippetEditor.tsx
  frontend/src/components/SnippetEditor/index.ts
  frontend/src/components/SnippetEditor/style.ts
  frontend/src/components/TemplateTitleInput/TemplateTitleInput.tsx
  frontend/src/components/TemplateTitleInput/index.ts
  frontend/src/components/TemplateTitleInput/style.ts
  frontend/src/pages/UploadsTemplate.tsx
  frontend/src/routes/router.tsx
Labels: feature, FE, help wanted

#64 모든 페이지 Header 적용
  frontend/.gitignore
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/index.ts
  frontend/src/pages/Template.tsx
  frontend/src/routes/router.tsx
Labels: feature, FE, hackathon

#66 CORS 설정
  backend/src/main/java/codezap/global/WebCorsConfiguration.java
Labels: bug, BE

#68 CORS 설정을 변경
  backend/src/main/java/codezap/global/WebCorsConfiguration.java
Labels: bug, BE

#71 ReactQuery - 템플릿 리스트/상세/업로드 페이지 API fetch 구현
  .gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/TemplateItem/TemplateItem.tsx
  frontend/src/components/TemplateTitleInput/TemplateTitleInput.tsx
  frontend/src/hooks/useTemplateListQuery.ts
  frontend/src/hooks/useTemplateQuery.ts
  frontend/src/hooks/useTemplateUploadQuery.ts
  frontend/src/index.tsx
  frontend/src/pages/Template.tsx
  frontend/src/pages/TemplateList.tsx
  frontend/src/pages/UploadsTemplate.tsx
  frontend/src/types/template.ts
Labels: FE, hackathon

#74 README 서비스 소개 및 팀원 정보 작성
  README.md
Labels: documentation

#75 README 팀원 프로필 연결 링크 수정
  README.md
Labels: documentation

#76 Template 목록 조회, 상세 조회, 작성 기능
  .github/workflows/build.yml
  backend/build.gradle
  backend/src/main/java/codezap/extension/domain/Extension.java
  backend/src/main/java/codezap/extension/repository/ExtensionRepository.java
  backend/src/main/java/codezap/global/DateTimeFormatConfiguration.java
  backend/src/main/java/codezap/global/SpringDocConfiguration.java
  backend/src/main/java/codezap/global/WebCorsConfiguration.java
  backend/src/main/java/codezap/global/domain/BaseTimeEntity.java
  backend/src/main/java/codezap/global/domain/JpaAuditingConfiguration.java
  backend/src/main/java/codezap/language/domain/Language.java
  backend/src/main/java/codezap/language/repository/LanguageRepository.java
  backend/src/main/java/codezap/member/domain/Member.java
  backend/src/main/java/codezap/member/repository/MemberRepository.java
  backend/src/main/java/codezap/representative_snippet/domain/RepresentativeSnippet.java
  backend/src/main/java/codezap/representative_snippet/repository/RepresentativeSnippetRepository.java
  backend/src/main/java/codezap/snippet/domain/Snippet.java
  backend/src/main/java/codezap/snippet/repository/SnippetRepository.java
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
  backend/src/main/java/codezap/template/controller/TemplateController.java
  backend/src/main/java/codezap/template/domain/Template.java
  backend/src/main/java/codezap/template/dto/request/CreateTemplateRequest.java
  backend/src/main/java/codezap/template/dto/request/CreateTemplateResponse.java
  backend/src/main/java/codezap/template/dto/response/FindAllSnippetByTemplateResponse.java
  backend/src/main/java/codezap/template/dto/response/FindAllTemplatesResponse.java
  backend/src/main/java/codezap/template/dto/response/FindMemberBySummaryResponse.java
  backend/src/main/java/codezap/template/dto/response/FindRepresentativeSnippetResponse.java
  backend/src/main/java/codezap/template/dto/response/FindTemplateByIdResponse.java
  backend/src/main/java/codezap/template/dto/response/FindTemplateBySummaryResponse.java
  backend/src/main/java/codezap/template/repository/TemplateRepository.java
  backend/src/main/java/codezap/template/service/TemplateService.java
  backend/src/main/resources/application-local.yml
Labels: feature, BE, hackathon

#78 Template 목록 조회, 상세 조회, 생성 기능
  .gitignore
  frontend/.eslintrc.cjs
  frontend/.gitignore
  frontend/.prettierrc
  frontend/.storybook/preview.ts
  frontend/.storybook/preview.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/assets/images/logo.png
  frontend/src/assets/images/newTemplate.png
  frontend/src/assets/images/search.png
  frontend/src/components/.gitkeep
  frontend/src/components/Button/Button.stories.tsx
  frontend/src/components/Button/Button.tsx
  frontend/src/components/Button/index.ts
  frontend/src/components/Button/style.ts
  frontend/src/components/Flex/Flex.tsx
  frontend/src/components/Flex/index.ts
  frontend/src/components/Flex/style.ts
  frontend/src/components/Header/Header.stories.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/index.ts
  frontend/src/components/Header/style.ts
  frontend/src/components/Input/Input.stories.tsx
  frontend/src/components/Input/Input.tsx
  frontend/src/components/Input/index.ts
  frontend/src/components/Input/style.ts
  frontend/src/components/SelectList/SelectList.tsx
  frontend/src/components/SelectList/index.ts
  frontend/src/components/SnippetEditor/SnippetEditor.tsx
  frontend/src/components/SnippetEditor/index.ts
  frontend/src/components/SnippetEditor/style.ts
  frontend/src/components/TemplateItem/TemplateItem.tsx
  frontend/src/components/TemplateItem/index.ts
  frontend/src/components/TemplateTitleInput/TemplateTitleInput.tsx
  frontend/src/components/TemplateTitleInput/index.ts
  frontend/src/components/TemplateTitleInput/style.ts
  frontend/src/components/Text/Text.tsx
  frontend/src/components/Text/index.ts
  frontend/src/components/Text/style.ts
  frontend/src/hooks/useTemplateListQuery.ts
  frontend/src/hooks/useTemplateQuery.ts
  frontend/src/hooks/useTemplateUploadQuery.ts
  frontend/src/index.tsx
  frontend/src/mocks/template.json
  frontend/src/mocks/templateList.json
  frontend/src/pages/Template.tsx
  frontend/src/pages/TemplateList.tsx
  frontend/src/pages/UploadsTemplate.tsx
  frontend/src/routes/router.tsx
  frontend/src/style/GlobalStyles.tsx
  frontend/src/types/index.d.ts
  frontend/src/types/template.ts
  frontend/src/utils/convertToCamelCase.ts
  frontend/webpack.config.cjs
Labels: feature, FE, hackathon

#83 CI 워크플로에서 태스크를 build에서 test로 변경
  .github/workflows/backend_cd.yml
  .github/workflows/backend_ci.yml
  backend/src/main/resources/application-local.yml
Labels: BE

#87 eslint 설정 추가 및 stylelint 설정 추가
  frontend/.eslintrc.cjs
  frontend/.stylelintrc.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Button/Button.stories.tsx
  frontend/src/components/Button/Button.tsx
  frontend/src/components/Button/style.ts
  frontend/src/components/Flex/Flex.tsx
  frontend/src/components/Flex/style.ts
  frontend/src/components/Header/Header.stories.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/style.ts
  frontend/src/components/Input/Input.stories.tsx
  frontend/src/components/Input/Input.tsx
  frontend/src/components/Input/style.ts
  frontend/src/components/Layout/Layout.tsx
  frontend/src/components/Layout/index.ts
  frontend/src/components/SelectList/SelectList.tsx
  frontend/src/components/SnippetEditor/SnippetEditor.tsx
  frontend/src/components/SnippetEditor/style.ts
  frontend/src/components/TemplateItem/TemplateItem.tsx
  frontend/src/components/TemplateTitleInput/TemplateTitleInput.tsx
  frontend/src/components/TemplateTitleInput/style.ts
  frontend/src/components/Text/Text.tsx
  frontend/src/components/Text/style.ts
  frontend/src/hooks/useTemplateListQuery.ts
  frontend/src/hooks/useTemplateQuery.ts
  frontend/src/hooks/useTemplateUploadQuery.ts
  frontend/src/index.tsx
  frontend/src/pages/Template.tsx
  frontend/src/pages/TemplateList.tsx
  frontend/src/pages/UploadsTemplate.tsx
  frontend/src/routes/router.tsx
  frontend/src/style/GlobalStyles.tsx
  frontend/src/utils/convertToCamelCase.ts
Labels: FE, refactor

#89 CI 적용 후 rebase
  .github/workflows/backend_ci.yml
  .github/workflows/deploy.yml
  backend/src/main/resources/application-local.yml
Labels: BE

#96 Github Action Runner를 이용한 백엔드 CD 파이프라인 구축
  .github/workflows/backend_cd.yml
Labels: feature, BE

#99 테스트 도구 설치 및 stylelint config 변경
  frontend/.eslintrc.cjs
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/.stylelintrc.json
  frontend/jest.config.ts
  frontend/jest.polyfills.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/setupTests.ts
  frontend/src/hooks/useTemplateListQuery.spec.tsx
  frontend/src/hooks/useTemplateListQuery.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/server.ts
  frontend/tsconfig.json
Labels: feature, FE

#105 프론트엔드 CI 설정 (github actions)
  .github/workflows/frontend_ci.yml
Labels: feature, FE

#106 커스텀 검증 추가
  backend/src/main/java/codezap/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/codezap/global/serialization/DateTimeFormatConfiguration.java
  backend/src/main/java/codezap/global/validation/ByteLength.java
  backend/src/main/java/codezap/global/validation/ByteLengthValidator.java
  backend/src/main/java/codezap/template/controller/TemplateController.java
  backend/src/main/java/codezap/template/dto/request/CreateSnippetRequest.java
  backend/src/main/java/codezap/template/dto/request/CreateTemplateRequest.java
  backend/src/main/java/codezap/template/dto/request/validation/IncreasedIndex.java
  backend/src/main/java/codezap/template/dto/request/validation/IncreasedIndexValidator.java
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
Labels: feature, BE

#98 컴포넌트 스타일 일관성 리팩토링
  frontend/.storybook/main.ts
  frontend/src/components/Button/Button.stories.tsx
  frontend/src/components/Button/Button.tsx
  frontend/src/components/Button/style.ts
  frontend/src/components/Flex/Flex.tsx
  frontend/src/components/Flex/style.ts
  frontend/src/components/Header/Header.stories.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Input/Input.tsx
  frontend/src/components/Input/style.ts
  frontend/src/components/Layout/Layout.tsx
  frontend/src/components/Layout/style.ts
  frontend/src/components/SelectList/SelectList.tsx
  frontend/src/components/SelectList/style.ts
  frontend/src/components/TemplateItem/TemplateItem.tsx
  frontend/src/components/TemplateTitleInput/TemplateTitleInput.tsx
  frontend/src/components/TemplateTitleInput/style.ts
  frontend/src/components/Text/Text.tsx
  frontend/src/components/Text/style.ts
  frontend/src/hooks/useTemplateListQuery.spec.tsx
  frontend/src/pages/Template.tsx
  frontend/src/pages/TemplateList.tsx
  frontend/src/pages/UploadsTemplate.tsx
Labels: FE, refactor

#119 [BE] 배포 확인 작업 명령어 오류 수정
  .github/workflows/backend_cd.yml
Labels: bug, BE

#110 템플릿 목록 조회, 상세 조회, 생성 요청 로직 리펙토링
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/api/customFetch.ts
  frontend/src/api/queryKeys.ts
  frontend/src/api/templates.ts
  frontend/src/components/TemplateItem/TemplateItem.tsx
  frontend/src/hooks/useTemplateListQuery.spec.tsx
  frontend/src/hooks/useTemplateListQuery.ts
  frontend/src/hooks/useTemplateQuery.spec.tsx
  frontend/src/hooks/useTemplateQuery.ts
  frontend/src/hooks/useTemplateUploadQuery.spec.tsx
  frontend/src/hooks/useTemplateUploadQuery.ts
  frontend/src/index.tsx
  frontend/src/mocks/browser.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/template.json
  frontend/src/mocks/templateList.json
  frontend/src/pages/Template.tsx
  frontend/src/pages/TemplateUpload.tsx
  frontend/src/routes/router.tsx
  frontend/src/types/template.ts
  frontend/src/utils/convertToCamelCase.ts
  frontend/src/utils/formatRelativeTime.spec.ts
  frontend/src/utils/formatRelativeTime.ts
  frontend/webpack.config.cjs
Labels: FE, refactor, zap

#130 react-router-dom의 basename 설정, api filedName 수정
  .github/workflows/frontend_ci.yml
  frontend/package.json
  frontend/src/components/TemplateItem/TemplateItem.tsx
  frontend/src/mocks/templateList.json
  frontend/src/pages/Template.tsx
  frontend/src/routes/router.tsx
  frontend/src/types/template.ts
Labels: feature, FE, zap

#134 모듈 import/export 방식 변경 (index.ts)
  frontend/.eslintrc.json
  frontend/src/api/index.ts
  frontend/src/assets/images/index.ts
  frontend/src/components/Button/Button.stories.tsx
  frontend/src/components/Button/Button.tsx
  frontend/src/components/Button/index.ts
  frontend/src/components/Button/style.ts
  frontend/src/components/Flex/Flex.tsx
  frontend/src/components/Flex/index.ts
  frontend/src/components/Flex/style.ts
  frontend/src/components/Header/Header.stories.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/index.ts
  frontend/src/components/Input/Input.stories.tsx
  frontend/src/components/Input/Input.tsx
  frontend/src/components/Input/index.ts
  frontend/src/components/Input/style.ts
  frontend/src/components/Layout/Layout.tsx
  frontend/src/components/Layout/index.ts
  frontend/src/components/SelectList/SelectList.tsx
  frontend/src/components/SelectList/index.ts
  frontend/src/components/SelectList/style.ts
  frontend/src/components/SnippetEditor/SnippetEditor.tsx
  frontend/src/components/SnippetEditor/index.ts
  frontend/src/components/TemplateItem/TemplateItem.tsx
  frontend/src/components/TemplateItem/index.ts
  frontend/src/components/TemplateTitleInput/index.ts
  frontend/src/components/Text/Text.tsx
  frontend/src/components/Text/index.ts
  frontend/src/components/Text/style.ts
  frontend/src/components/index.ts
  frontend/src/hooks/template/index.ts
  frontend/src/hooks/template/useTemplateListQuery.spec.tsx
  frontend/src/hooks/template/useTemplateListQuery.ts
  frontend/src/hooks/template/useTemplateQuery.spec.tsx
  frontend/src/hooks/template/useTemplateQuery.ts
  frontend/src/hooks/template/useTemplateUploadQuery.spec.tsx
  frontend/src/hooks/template/useTemplateUploadQuery.ts
  frontend/src/index.tsx
  frontend/src/mocks/browser.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/server.ts
  frontend/src/pages/Template/Template.tsx
  frontend/src/pages/TemplateList/TemplateList.tsx
  frontend/src/pages/TemplateUpload/TemplateUpload.tsx
  frontend/src/pages/index.ts
  frontend/src/routes/router.tsx
  frontend/src/utils/index.ts
Labels: FE, refactor

#132 템플릿 수정 기능 구현
  backend/src/main/java/codezap/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/codezap/template/controller/TemplateController.java
  backend/src/main/java/codezap/template/domain/Snippet.java
  backend/src/main/java/codezap/template/domain/Template.java
  backend/src/main/java/codezap/template/domain/ThumbnailSnippet.java
  backend/src/main/java/codezap/template/dto/request/CreateTemplateRequest.java
  backend/src/main/java/codezap/template/dto/request/UpdateSnippetRequest.java
  backend/src/main/java/codezap/template/dto/request/UpdateTemplateRequest.java
  backend/src/main/java/codezap/template/dto/request/validation/IncreasedIndexValidator.java
  backend/src/main/java/codezap/template/dto/request/validation/SnippetsOrdinal.java
  backend/src/main/java/codezap/template/dto/request/validation/SnippetsOrdinalValidator.java
  backend/src/main/java/codezap/template/dto/request/validation/ValidatedSnippetsOrdinalRequest.java
  backend/src/main/java/codezap/template/repository/SnippetRepository.java
  backend/src/main/java/codezap/template/repository/TemplateRepository.java
  backend/src/main/java/codezap/template/repository/ThumbnailSnippetRepository.java
  backend/src/main/java/codezap/template/service/TemplateService.java
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
  backend/src/test/java/codezap/template/repository/SnippetRepositoryTest.java
  backend/src/test/java/codezap/template/service/TemplateServiceTest.java
Labels: feature, BE

#147 템플릿 삭제 기능 구현
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
  backend/src/main/java/codezap/template/controller/TemplateController.java
  backend/src/main/java/codezap/template/repository/SnippetRepository.java
  backend/src/main/java/codezap/template/repository/ThumbnailSnippetRepository.java
  backend/src/main/java/codezap/template/service/TemplateService.java
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
  backend/src/test/java/codezap/template/service/TemplateServiceTest.java
Labels: feature, BE

#142 refactor(workflows): cd 아티팩트 다운로드 개선
  .github/workflows/backend_cd.yml
Labels: refactor, BE

#143 템플릿 수정 페이지 구현
  frontend/src/components/Header/Header.tsx
  frontend/src/components/SelectList/SelectList.tsx
  frontend/src/components/SelectList/style.ts
  frontend/src/pages/Template/Template.tsx
  frontend/src/pages/TemplateEditPage/TemplateEditPage.style.ts
  frontend/src/pages/TemplateEditPage/TemplateEditPage.tsx
  frontend/src/pages/TemplateListPage/TemplateListPage.tsx
  frontend/src/pages/TemplatePage/TemplatePage.style.ts
  frontend/src/pages/TemplatePage/TemplatePage.tsx
  frontend/src/pages/TemplateUploadPage/TemplateUploadPage.tsx
  frontend/src/pages/index.ts
  frontend/src/routes/router.tsx
Labels: feature, FE

#136 템플릿 수정, 삭제 api 요청 기능 추가
  frontend/src/api/templates.ts
  frontend/src/hooks/useTemplateDeleteQuery.spec.tsx
  frontend/src/hooks/useTemplateDeleteQuery.ts
  frontend/src/hooks/useTemplateEditQuery.spec.tsx
  frontend/src/hooks/useTemplateEditQuery.ts
  frontend/src/mocks/handlers.ts
  frontend/src/types/template.ts
Labels: feature, FE, zap

#148 [BE] 템플릿 수정 및 삭제 기능 구현
  .github/workflows/backend_cd.yml
  backend/src/main/java/codezap/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
  backend/src/main/java/codezap/template/controller/TemplateController.java
  backend/src/main/java/codezap/template/domain/Snippet.java
  backend/src/main/java/codezap/template/domain/Template.java
  backend/src/main/java/codezap/template/domain/ThumbnailSnippet.java
  backend/src/main/java/codezap/template/dto/request/CreateTemplateRequest.java
  backend/src/main/java/codezap/template/dto/request/UpdateSnippetRequest.java
  backend/src/main/java/codezap/template/dto/request/UpdateTemplateRequest.java
  backend/src/main/java/codezap/template/dto/request/validation/IncreasedIndexValidator.java
  backend/src/main/java/codezap/template/dto/request/validation/SnippetsOrdinal.java
  backend/src/main/java/codezap/template/dto/request/validation/SnippetsOrdinalValidator.java
  backend/src/main/java/codezap/template/dto/request/validation/ValidatedSnippetsOrdinalRequest.java
  backend/src/main/java/codezap/template/repository/SnippetRepository.java
  backend/src/main/java/codezap/template/repository/TemplateRepository.java
  backend/src/main/java/codezap/template/repository/ThumbnailSnippetRepository.java
  backend/src/main/java/codezap/template/service/TemplateService.java
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
  backend/src/test/java/codezap/template/repository/SnippetRepositoryTest.java
  backend/src/test/java/codezap/template/service/TemplateServiceTest.java
Labels: feature, BE

#153 feat(workflows): 배포 파이프라인 구현
  .github/workflows/frontend_cd.yml
Labels: feature, FE

#155 템플릿 수정, 삭제 기능 페이지 연결
  frontend/src/assets/images/index.ts
  frontend/src/assets/images/trashcan.png
  frontend/src/components/TemplateItem/TemplateItem.tsx
  frontend/src/hooks/template/index.ts
  frontend/src/hooks/template/useTemplateDeleteQuery.spec.tsx
  frontend/src/hooks/template/useTemplateDeleteQuery.ts
  frontend/src/hooks/template/useTemplateEditQuery.spec.tsx
  frontend/src/hooks/template/useTemplateEditQuery.ts
  frontend/src/pages/TemplateEditPage/TemplateEditPage.style.ts
  frontend/src/pages/TemplateEditPage/TemplateEditPage.tsx
  frontend/src/pages/TemplatePage/TemplatePage.tsx
  frontend/src/routes/router.tsx
Labels: feature, FE, zap

#157 템플릿 요청시 사용하지 않는 필드 삭제
  frontend/src/pages/TemplateUploadPage/TemplateUploadPage.tsx
Labels: FE, refactor

#167 TestController 삭제
  backend/src/main/java/codezap/TestController.java
Labels: bug, BE

#164 템플릿 생성페이지, 수정 페이지 디자인 수정
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/style.ts
  frontend/src/pages/TemplateEditPage/TemplateEditPage.tsx
  frontend/src/pages/TemplateUploadPage/TemplateUploadPage.style.ts
  frontend/src/pages/TemplateUploadPage/TemplateUploadPage.tsx
Labels: FE, refactor

#166 스니펫 파일명 표시, SelectList 디자인 변경
  frontend/src/assets/images/index.ts
  frontend/src/assets/images/pencil.png
  frontend/src/components/Layout/style.ts
  frontend/src/components/SelectList/SelectList.tsx
  frontend/src/components/SelectList/style.ts
  frontend/src/components/TemplateItem/TemplateItem.tsx
  frontend/src/pages/TemplatePage/TemplatePage.style.ts
  frontend/src/pages/TemplatePage/TemplatePage.tsx
Labels: FE, refactor

#174 배포 사이트에서 Unexpected token '<' (at bundle.js:1:1) 에러 해결
  frontend/public/index.html
Labels: bug, FE, zap

#162 실패 케이스 문서화에 사용할 스웨거 커스텀 기능 구현
  backend/src/main/java/codezap/global/swagger/error/ApiErrorResponse.java
  backend/src/main/java/codezap/global/swagger/error/ApiErrorResponsesCustomizer.java
  backend/src/main/java/codezap/global/swagger/error/ErrorCase.java
  backend/src/main/java/codezap/global/swagger/error/ProblemDetailSchema.java
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
Labels: documentation, refactor, BE

#177 2차 스프린트 api 에러 문서화 응답 예시 보완
  backend/src/main/java/codezap/global/swagger/error/ApiErrorResponse.java
  backend/src/main/java/codezap/global/swagger/error/ApiErrorResponsesCustomizer.java
  backend/src/main/java/codezap/global/swagger/error/ErrorCase.java
  backend/src/main/java/codezap/global/swagger/error/ProblemDetailSchema.java
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
Labels: documentation, BE

#204 롬복을 최신 버전을 사용하도록 변경
  backend/build.gradle
Labels: refactor, BE

#206 [REFACTOR] CI actions에 DB 정보를 숨기기
  .github/workflows/backend_ci.yml
Labels: refactor, BE

#209 코드 하이라이터 적용을 위해 언어 추론 추가 및 SelectList 헤더 길이 고려하도록 변경
  frontend/src/components/Layout/style.ts
  frontend/src/components/SelectList/style.ts
  frontend/src/components/TemplateItem/TemplateItem.tsx
  frontend/src/mocks/templateList.json
  frontend/src/pages/TemplatePage/TemplatePage.tsx
  frontend/src/style/GlobalStyles.tsx
  frontend/src/utils/getLanguageByFileName.spec.ts
  frontend/src/utils/getLanguageByFileName.ts
  frontend/src/utils/index.ts
Labels: FE, refactor

#224 [FIX] secrets 문제를 pull_request_target으로 변경
  .github/workflows/backend_ci.yml
  README.md
Labels: bug, BE

#215 Input 컴포넌트 리팩토링
  frontend/.storybook/preview.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Input/Input.stories.tsx
  frontend/src/components/Input/Input.tsx
  frontend/src/components/Input/style.ts
Labels: FE, refactor

#225 템플릿 생성 기능 리팩토링
  backend/src/main/java/codezap/category/controller/CategoryController.java
  backend/src/main/java/codezap/category/domain/Category.java
  backend/src/main/java/codezap/category/dto/request/CreateCategoryRequest.java
  backend/src/main/java/codezap/category/dto/response/FindAllCategoriesResponse.java
  backend/src/main/java/codezap/category/dto/response/FindCategoryByIdResponse.java
  backend/src/main/java/codezap/category/repository/CategoryRepository.java
  backend/src/main/java/codezap/category/service/CategoryService.java
  backend/src/main/java/codezap/template/domain/Snippet.java
  backend/src/main/java/codezap/template/domain/Tag.java
  backend/src/main/java/codezap/template/domain/Template.java
  backend/src/main/java/codezap/template/domain/TemplateTag.java
  backend/src/main/java/codezap/template/domain/ThumbnailSnippet.java
  backend/src/main/java/codezap/template/dto/request/CreateTemplateRequest.java
  backend/src/main/java/codezap/template/repository/TagRepository.java
  backend/src/main/java/codezap/template/repository/TemplateTagRepository.java
  backend/src/main/java/codezap/template/service/TemplateService.java
  backend/src/test/java/codezap/category/controller/CategoryControllerTest.java
  backend/src/test/java/codezap/category/service/CategoryServiceTest.java
  backend/src/test/java/codezap/template/service/TemplateServiceTest.java
  backend/src/test/resources/clear.sql
Labels: feature, BE
