Repository woowacourse-teams/2024-code-zap, pull requests merged in 2024-10, with the labels that each got.

#719 전문 검색 인덱스 적용
  backend/src/main/java/codezap/template/repository/FullTextSearchMySQLDialect.java
  backend/src/main/java/codezap/template/repository/TemplateSpecification.java
  backend/src/main/resources/db/migration/V6__add_full_text_index.sql
  backend/src/test/java/codezap/global/DatabaseCleaner.java
  backend/src/test/java/codezap/template/repository/TemplateJpaRepositoryTest.java
  backend/src/test/java/codezap/template/repository/TemplateSearchJpaRepositoryTest.java
  backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java
  backend/src/test/java/codezap/template/service/TemplateServiceTest.java
  backend/src/test/resources/search.sql
Labels: refactor, BE

#694 템플릿 생성 및 수정페이지 컴포넌트 및 훅 분리
  frontend/playwright/tests/search.spec.ts
  frontend/playwright/tests/templates.actions.ts
  frontend/playwright/tests/templates.spec.ts
  frontend/src/components/CategoryDropdown/CategoryDropdown.tsx
  frontend/src/components/CategoryGuide/CategoryGuide.tsx
  frontend/src/components/NewCategoryInput/NewCategoryInput.tsx
  frontend/src/components/SourceCode/SourceCode.style.ts
  frontend/src/components/SourceCode/SourceCode.tsx
  frontend/src/components/SourceCodeEditor/SourceCodeEditor.style.ts
  frontend/src/components/SourceCodeEditor/SourceCodeEditor.tsx
  frontend/src/components/SourceCodeViewer/SourceCodeViewer.style.ts
  frontend/src/components/SourceCodeViewer/SourceCodeViewer.tsx
  frontend/src/components/TagInput/TagInput.tsx
  frontend/src/components/TemplateCard/TemplateCard.style.ts
  frontend/src/components/TemplateCard/TemplateCard.tsx
  frontend/src/components/index.ts
  frontend/src/hooks/authentication/useAuth.ts
  frontend/src/hooks/category/useCategory.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/template/index.ts
  frontend/src/hooks/template/useSourceCode.ts
  frontend/src/hooks/template/useTag.ts
  frontend/src/hooks/useNoSpaceInput.ts
  frontend/src/hooks/useSelectList.ts
  frontend/src/hooks/useToast.ts
  frontend/src/pages/TemplateEditPage/TemplateEditPage.style.ts
  frontend/src/pages/TemplateEditPage/TemplateEditPage.tsx
  frontend/src/pages/TemplateEditPage/components/.gitkeep
  frontend/src/pages/TemplateEditPage/components/TemplateEdit/TemplateEdit.tsx
  frontend/src/pages/TemplateEditPage/components/index.ts
  frontend/src/pages/TemplateEditPage/hooks/.gitkeep
  frontend/src/pages/TemplateEditPage/hooks/index.ts
  frontend/src/pages/TemplateEditPage/hooks/useTemplateEdit.ts
  frontend/src/pages/TemplatePage/TemplatePage.tsx
  frontend/src/pages/TemplatePage/hooks/index.ts
  frontend/src/pages/TemplatePage/hooks/useTemplate.ts
  frontend/src/pages/TemplateUploadPage/TemplateUploadPage.style.ts
  frontend/src/pages/TemplateUploadPage/TemplateUploadPage.tsx
  frontend/src/pages/TemplateUploadPage/components/.gitkeep
  frontend/src/pages/TemplateUploadPage/components/TemplateEdit/TemplateEdit.tsx
  frontend/src/pages/TemplateUploadPage/components/index.ts
  frontend/src/pages/TemplateUploadPage/hooks/.gitkeep
  frontend/src/pages/TemplateUploadPage/hooks/index.ts
  frontend/src/pages/TemplateUploadPage/hooks/useTemplateUpload.ts
  frontend/src/service/index.ts
  frontend/src/service/validates.ts
  frontend/src/utils/index.ts
  frontend/src/utils/removeAllWhitespace.ts
Labels: FE, refactor

#730 Swagger 개발 서버 IP 추가
  backend/src/main/java/codezap/global/swagger/SpringDocConfiguration.java
Labels: documentation, BE

#736 [접근성개선] 카테고리 가이드 숨김 상태일 때 aria-hidden 설정
  frontend/src/components/CategoryGuide/CategoryGuide.tsx
Labels: feature, FE

#716 Bundle 사이즈 최적화
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Toast/Toast.tsx
  frontend/src/routes/router.tsx
  frontend/webpack.common.js
  frontend/webpack.prod.js
Labels: feature, FE

#641 로컬 환경에서 서버 실행을 위한 도커 컴포즈 스크립트 작성
  backend/.gitignore
  backend/docker/app/application.yml
  backend/docker/compose.yml
  backend/docker/run.sh
Labels: FE, BE

#729 사용되지 않는 MemberDto 제거
  backend/src/main/java/codezap/global/swagger/AuthOperationCustomizer.java
  backend/src/main/java/codezap/member/dto/MemberDto.java
  backend/src/test/java/codezap/fixture/MemberDtoFixture.java
Labels: refactor, BE

#728 태그 및 카테고리 생성 시 글자수 검증
  backend/src/main/java/codezap/category/dto/request/CreateCategoryRequest.java
  backend/src/main/java/codezap/global/validation/ByteLength.java
  backend/src/main/java/codezap/global/validation/GroupedByteLengthValidator.java
  backend/src/main/java/codezap/template/dto/request/CreateTemplateRequest.java
  backend/src/test/java/codezap/category/controller/CategoryControllerTest.java
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
Labels: feature, BE

#724 백엔드 로그 수정
  backend/src/main/resources/logger/logback-spring-prod.xml
Labels: refactor, BE

#742 [접근성 개선] 로그인 input 및 상세페이지 소스코드 접기 버튼 접근성 개선
  frontend/src/components/Input/Input.style.ts
  frontend/src/components/Input/Input.tsx
  frontend/src/components/SourceCodeViewer/SourceCodeViewer.tsx
  frontend/src/pages/LoginPage/LoginPage.tsx
Labels: FE, refactor

#737 좋아요한 템플릿 삭제 시 좋아요 테이블 삭제 구현
  backend/src/main/java/codezap/likes/domain/Likes.java
  backend/src/main/java/codezap/likes/repository/LikesJpaRepository.java
  backend/src/main/java/codezap/likes/repository/LikesRepository.java
  backend/src/main/java/codezap/likes/service/LikesService.java
  backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
  backend/src/test/java/codezap/likes/repository/FakeLikeRepository.java
  backend/src/test/java/codezap/likes/repository/LikesJpaRepositoryTest.java
  backend/src/test/java/codezap/likes/service/LikesServiceTest.java
  backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
Labels: bug, BE

#727 [접근성개선] 스크린 리더가 태그 등록 메시지 안내
  frontend/src/components/ScreenReaderOnly/ScreenReaderOnly.tsx
  frontend/src/components/TagInput/TagInput.tsx
  frontend/src/components/index.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/useScreenReader.ts
  frontend/src/index.tsx
Labels: feature, FE

#759 태그 이름으로 태그 조회 시 대소문자를 구분하지 않아 태그가 중복으로 반환되는 버그 수정
  backend/src/main/java/codezap/tag/repository/TagJpaRepository.java
  backend/src/main/java/codezap/tag/repository/TagRepository.java
  backend/src/main/java/codezap/tag/repository/TemplateTagJpaRepository.java
  backend/src/main/java/codezap/tag/service/TagService.java
  backend/src/test/java/codezap/tag/repository/TagJpaRepositoryTest.java
  backend/src/test/java/codezap/template/repository/FakeTagRepository.java
Labels: bug, zap, BE

#750 같은 경로로 이동시 히스토리 쌓이지 않도록 변경
  frontend/src/components/Header/Header.tsx
  frontend/src/components/NonmemberAlerter/NonmemberAlerter.tsx
  frontend/src/hooks/index.ts
  frontend/src/hooks/useCustomNavigate.ts
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
  frontend/src/pages/NotFoundPage/NotFoundPage.tsx
  frontend/src/pages/SignupPage/hooks/useSignupForm.ts
  frontend/src/pages/TemplatePage/hooks/useTemplate.ts
  frontend/src/pages/TemplateUploadPage/TemplateUploadPage.tsx
  frontend/src/queries/authentication/useLoginMutation.ts
  frontend/src/queries/authentication/useSignupMutation.ts
  frontend/src/routes/RouteGuard.tsx
Labels: FE, refactor

#743 [접근성 개선] - 상단 Header, 로그인 Input
  frontend/package.json
  frontend/src/components/Header/Header.style.ts
  frontend/src/components/Header/Header.tsx
  frontend/src/pages/LoginPage/LoginPage.tsx
Labels: feature, FE

#738 전반적으로 자잘한 코드 컨벤션 정리
  backend/src/main/java/codezap/global/cors/CorsProperties.java
  backend/src/main/java/codezap/global/exception/CodeZapException.java
  backend/src/main/java/codezap/global/rds/DataSourceRouter.java
  backend/src/main/java/codezap/global/serialization/DateTimeFormatConfiguration.java
  backend/src/main/java/codezap/global/swagger/AuthOperationCustomizer.java
  backend/src/main/java/codezap/global/swagger/error/ApiErrorResponses.java
  backend/src/main/java/codezap/global/swagger/error/ApiErrorResponsesCustomizer.java
  backend/src/main/java/codezap/global/validation/ValidationGroups.java
  backend/src/main/java/codezap/likes/repository/LikesRepository.java
  backend/src/main/java/codezap/tag/controller/SpringDocTagController.java
  backend/src/main/java/codezap/tag/repository/TemplateTagJpaRepository.java
  backend/src/main/java/codezap/tag/repository/TemplateTagRepository.java
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
  backend/src/main/java/codezap/template/repository/FullTextSearchMySQLDialect.java
  backend/src/main/java/codezap/template/repository/SourceCodeJpaRepository.java
  backend/src/main/java/codezap/template/repository/SourceCodeRepository.java
  backend/src/main/java/codezap/template/repository/TemplateSpecification.java
  backend/src/main/java/codezap/template/repository/ThumbnailJpaRepository.java
  backend/src/test/java/codezap/auth/manager/CookieCredentialManagerTest.java
  backend/src/test/java/codezap/auth/provider/basic/BasicAuthCredentialProviderTest.java
  backend/src/test/java/codezap/auth/service/AuthServiceTest.java
  backend/src/test/java/codezap/category/controller/CategoryControllerTest.java
  backend/src/test/java/codezap/member/repository/MemberJpaRepositoryTest.java
  backend/src/test/java/codezap/tag/repository/TagJpaRepositoryTest.java
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
  backend/src/test/java/codezap/template/repository/FakeTemplateTagRepository.java
  backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java
Labels: refactor, BE

#769 [BE] MySQL 대소문자 구분 문제로 태그 생성 시 다른 태그까지 생성되는 버그 픽스
  backend/src/main/java/codezap/global/cors/CorsProperties.java
  backend/src/main/java/codezap/global/exception/CodeZapException.java
  backend/src/main/java/codezap/global/rds/DataSourceRouter.java
  backend/src/main/java/codezap/global/serialization/DateTimeFormatConfiguration.java
  backend/src/main/java/codezap/global/swagger/AuthOperationCustomizer.java
  backend/src/main/java/codezap/global/swagger/error/ApiErrorResponses.java
  backend/src/main/java/codezap/global/swagger/error/ApiErrorResponsesCustomizer.java
  backend/src/main/java/codezap/global/validation/ValidationGroups.java
  backend/src/main/java/codezap/likes/repository/LikesRepository.java
  backend/src/main/java/codezap/tag/controller/SpringDocTagController.java
  backend/src/main/java/codezap/tag/repository/TagJpaRepository.java
  backend/src/main/java/codezap/tag/repository/TagRepository.java
  backend/src/main/java/codezap/tag/repository/TemplateTagJpaRepository.java
  backend/src/main/java/codezap/tag/repository/TemplateTagRepository.java
  backend/src/main/java/codezap/tag/service/TagService.java
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
  backend/src/main/java/codezap/template/repository/FullTextSearchMySQLDialect.java
  backend/src/main/java/codezap/template/repository/SourceCodeJpaRepository.java
  backend/src/main/java/codezap/template/repository/SourceCodeRepository.java
  backend/src/main/java/codezap/template/repository/TemplateSpecification.java
  backend/src/main/java/codezap/template/repository/ThumbnailJpaRepository.java
  backend/src/test/java/codezap/auth/manager/CookieCredentialManagerTest.java
  backend/src/test/java/codezap/auth/provider/basic/BasicAuthCredentialProviderTest.java
  backend/src/test/java/codezap/auth/service/AuthServiceTest.java
  backend/src/test/java/codezap/category/controller/CategoryControllerTest.java
  backend/src/test/java/codezap/member/repository/MemberJpaRepositoryTest.java
  backend/src/test/java/codezap/tag/repository/TagJpaRepositoryTest.java
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
  backend/src/test/java/codezap/template/repository/FakeTagRepository.java
  backend/src/test/java/codezap/template/repository/FakeTemplateTagRepository.java
  backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java
Labels: bug, zap, BE

#747 AuthenticationPrinciple 어노테이션에 required 속성 추가
  backend/src/main/java/codezap/auth/configuration/AuthArgumentResolver.java
  backend/src/main/java/codezap/auth/configuration/AuthenticationPrinciple.java
  backend/src/main/java/codezap/auth/manager/CookieCredentialManager.java
  backend/src/main/java/codezap/auth/manager/CredentialManager.java
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
  backend/src/main/java/codezap/template/controller/TemplateController.java
  backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
  backend/src/test/java/codezap/auth/configuration/AuthArgumentResolverTest.java
  backend/src/test/java/codezap/auth/provider/PlainCredentialProvider.java
  backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
Labels: refactor, BE

#748 템플릿 공개 여부에 따른 Swagger 파일 수정
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
  backend/src/main/java/codezap/template/domain/Template.java
  backend/src/main/java/codezap/template/domain/Visibility.java
  backend/src/main/java/codezap/template/dto/request/CreateTemplateRequest.java
  backend/src/main/java/codezap/template/dto/response/FindAllTemplateItemResponse.java
  backend/src/main/java/codezap/template/dto/response/FindTemplateResponse.java
  backend/src/main/java/codezap/template/service/TemplateService.java
  backend/src/main/resources/db/migration/V7__add_visibility.sql
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
  backend/src/test/java/codezap/template/domain/TemplateTagTest.java
  backend/src/test/java/codezap/template/domain/ThumbnailTest.java
  backend/src/test/java/codezap/template/repository/FakeTemplateRepository.java
  backend/src/test/java/codezap/template/service/TemplateServiceTest.java
  backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
  backend/src/test/resources/search.sql
Labels: documentation, BE

#761 에러 코드 구현 및 적용
  backend/src/main/java/codezap/auth/controller/SpringDocAuthController.java
  backend/src/main/java/codezap/auth/encryption/SHA2PasswordEncryptor.java
  backend/src/main/java/codezap/auth/manager/CookieCredentialManager.java
  backend/src/main/java/codezap/auth/provider/basic/BasicAuthCredentialProvider.java
  backend/src/main/java/codezap/auth/provider/basic/BasicAuthDecoder.java
  backend/src/main/java/codezap/auth/service/AuthService.java
  backend/src/main/java/codezap/category/controller/SpringDocCategoryController.java
  backend/src/main/java/codezap/category/domain/Category.java
  backend/src/main/java/codezap/category/repository/CategoryJpaRepository.java
  backend/src/main/java/codezap/category/service/CategoryService.java
  backend/src/main/java/codezap/global/exception/CodeZapException.java
  backend/src/main/java/codezap/global/exception/ErrorCode.java
  backend/src/main/java/codezap/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/codezap/global/swagger/AuthOperationCustomizer.java
  backend/src/main/java/codezap/likes/repository/LikesJpaRepository.java
  backend/src/main/java/codezap/member/repository/MemberJpaRepository.java
  backend/src/main/java/codezap/member/service/MemberService.java
  backend/src/main/java/codezap/tag/repository/TagJpaRepository.java
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
  backend/src/main/java/codezap/template/domain/Template.java
  backend/src/main/java/codezap/template/repository/SourceCodeJpaRepository.java
  backend/src/main/java/codezap/template/repository/TemplateJpaRepository.java
  backend/src/main/java/codezap/template/repository/ThumbnailJpaRepository.java
  backend/src/main/java/codezap/template/service/SourceCodeService.java
  backend/src/main/java/codezap/template/service/TemplateService.java
  backend/src/test/java/codezap/auth/provider/basic/BasicAuthCredentialProviderTest.java
  backend/src/test/java/codezap/auth/service/AuthServiceTest.java
  backend/src/test/java/codezap/category/controller/CategoryControllerTest.java
  backend/src/test/java/codezap/category/repository/FakeCategoryRepository.java
  backend/src/test/java/codezap/member/repository/FakeMemberRepository.java
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
  backend/src/test/java/codezap/template/repository/FakeSourceCodeRepository.java
  backend/src/test/java/codezap/template/repository/FakeTagRepository.java
  backend/src/test/java/codezap/template/repository/FakeTemplateRepository.java
  backend/src/test/java/codezap/template/repository/FakeThumbnailRepository.java
Labels: feature, BE

#773 cd 방법 변경으로인해 사용하지 않는 프론트엔드 cd 파일 삭제
  .github/workflows/frontend_cd.yml
Labels: FE, refactor, zap

#774 [FIX] 에러코드 detail 정보 없는 경우 수정 및 스웨거 수정
  backend/src/main/java/codezap/global/exception/GlobalExceptionHandler.java
Labels: bug, zap, BE

#764 로그백 롤링 파일 정책 변경
  backend/src/main/resources/logger/file/error-appender.xml
  backend/src/main/resources/logger/file/info-appender.xml
  backend/src/main/resources/logger/file/warn-appender.xml
Labels: refactor, BE

#777 문의하기 모달 생성
  frontend/src/components/ContactUs/ContactUs.style.ts
  frontend/src/components/ContactUs/ContactUs.tsx
  frontend/src/components/Footer/Footer.tsx
  frontend/src/components/Header/Header.style.ts
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Input/Input.tsx
  frontend/src/components/Modal/Modal.tsx
  frontend/src/components/Textarea/Textarea.stories.tsx
  frontend/src/components/Textarea/Textarea.style.ts
  frontend/src/components/Textarea/Textarea.tsx
  frontend/src/components/index.ts
  frontend/src/hooks/useInput.ts
  frontend/src/service/validates.ts
  frontend/src/utils/index.ts
  frontend/src/utils/reactChildrenHelpers.ts
Labels: feature, FE, zap

#775 TagControllerTest 작성
  backend/src/test/java/codezap/global/MockMvcTest.java
  backend/src/test/java/codezap/tag/controller/TagControllerTest.java
Labels: refactor, BE

#756 PR 템플릿에 마감 기한 추가
  .github/ISSUE_TEMPLATE/-bug-fix-template.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/ISSUE_TEMPLATE/refactor-issue-template.md
  .github/pull_request_template.md
Labels: documentation

#791 로그백 설정 오류로 서버가 실행되지 않는 버그 픽스
  backend/src/main/resources/logger/file/error-appender.xml
  backend/src/main/resources/logger/file/info-appender.xml
  backend/src/main/resources/logger/file/warn-appender.xml
Labels: bug, zap, BE

#793 로그백 설정 오류로 서버가 실행되지 않는 버그 픽스 (re)
  backend/src/main/resources/logger/file/error-appender.xml
  backend/src/main/resources/logger/file/info-appender.xml
  backend/src/main/resources/logger/file/warn-appender.xml
Labels: bug, zap, BE

#796 응답 바디 Json 형식 오류 메시지 변경
  backend/src/main/java/codezap/global/exception/GlobalExceptionHandler.java
Labels: refactor, BE

#792 delete 메서드명 명확하게 변경
  backend/src/main/java/codezap/likes/repository/LikesJpaRepository.java
  backend/src/main/java/codezap/likes/repository/LikesRepository.java
  backend/src/main/java/codezap/likes/service/LikesService.java
  backend/src/main/java/codezap/tag/repository/TemplateTagJpaRepository.java
  backend/src/main/java/codezap/tag/repository/TemplateTagRepository.java
  backend/src/main/java/codezap/tag/service/TagService.java
  backend/src/main/java/codezap/template/controller/TemplateController.java
  backend/src/main/java/codezap/template/repository/SourceCodeJpaRepository.java
  backend/src/main/java/codezap/template/repository/SourceCodeRepository.java
  backend/src/main/java/codezap/template/repository/ThumbnailJpaRepository.java
  backend/src/main/java/codezap/template/repository/ThumbnailRepository.java
  backend/src/main/java/codezap/template/service/SourceCodeService.java
  backend/src/main/java/codezap/template/service/ThumbnailService.java
  backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
  backend/src/test/java/codezap/likes/repository/FakeLikeRepository.java
  backend/src/test/java/codezap/likes/repository/LikesJpaRepositoryTest.java
  backend/src/test/java/codezap/template/repository/FakeSourceCodeRepository.java
  backend/src/test/java/codezap/template/repository/FakeTemplateTagRepository.java
  backend/src/test/java/codezap/template/repository/FakeThumbnailRepository.java
  backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
  backend/src/test/java/codezap/template/repository/ThumbnailRepositoryTest.java
  backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java
  backend/src/test/java/codezap/template/service/ThumbnailServiceTest.java
  backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
Labels: refactor, BE

#799 DataSourceConfig를 모든 환경에 적용되도록 변경
  .github/workflows/backend_ci.yml
  backend/.gitignore
  backend/src/main/java/codezap/global/rds/DataSourceConfig.java
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/codezap/global/repository/JpaRepositoryTest.java
  backend/src/test/java/codezap/template/repository/TemplateSearchJpaRepositoryTest.java
  backend/src/test/resources/application-local.yml
  backend/src/test/resources/application.yml
  backend/src/test/resources/clear.sql
Labels: refactor, zap, BE

#808 api 변경에 따른 /login 엔드포인트 제거
  frontend/package-lock.json
  frontend/playwright/tests/search.spec.ts
  frontend/playwright/tests/templates.spec.ts
  frontend/src/api/templates.ts
  frontend/src/queries/templates/useTemplateExploreQuery.ts
  frontend/src/queries/templates/useTemplateQuery.ts
Labels: FE, refactor, zap

#813 카테고리, 태그, 템플릿 목록 로딩 처리 개선
  frontend/src/components/ScrollTopButton/ScrollTopButton.style.ts
  frontend/src/components/ScrollTopButton/ScrollTopButton.tsx
  frontend/src/components/index.ts
  frontend/src/hooks/template/index.ts
  frontend/src/hooks/template/useSearchKeyword.ts
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.style.ts
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
  frontend/src/pages/MyTemplatesPage/components/CategoryListSection/CategoryListSection.style.ts
  frontend/src/pages/MyTemplatesPage/components/CategoryListSection/CategoryListSection.tsx
  frontend/src/pages/MyTemplatesPage/components/CategoryListSection/CategoryListSectionSkeleton.tsx
  frontend/src/pages/MyTemplatesPage/components/ConfirmDeleteModal/ConfirmDeleteModal.tsx
  frontend/src/pages/MyTemplatesPage/components/NewTemplateButton/NewTemplateButton.style.ts
  frontend/src/pages/MyTemplatesPage/components/NewTemplateButton/NewTemplateButton.tsx
  frontend/src/pages/MyTemplatesPage/components/TagListSection/TagListSection.tsx
  frontend/src/pages/MyTemplatesPage/components/TagListSection/TagListSectionSkeleton.tsx
  frontend/src/pages/MyTemplatesPage/components/TemplateDeleteSelection/TemplateDeleteSelection.tsx
  frontend/src/pages/MyTemplatesPage/components/TemplateListSection/TemplateListSection.tsx
  frontend/src/pages/MyTemplatesPage/components/TemplateListSection/TemplateListSectionLoading.style.ts
  frontend/src/pages/MyTemplatesPage/components/TemplateListSection/TemplateListSectionLoading.tsx
  frontend/src/pages/MyTemplatesPage/components/TopBanner/TopBanner.style.ts
  frontend/src/pages/MyTemplatesPage/components/TopBanner/TopBanner.tsx
  frontend/src/pages/MyTemplatesPage/components/index.ts
  frontend/src/pages/MyTemplatesPage/hooks/.gitkeep
  frontend/src/pages/MyTemplatesPage/hooks/index.ts
  frontend/src/pages/MyTemplatesPage/hooks/useFilteredTemplateList.ts
  frontend/src/pages/MyTemplatesPage/hooks/useSelectAndDeleteTemplateList.ts
  frontend/src/queries/categories/useCategoryListQuery.ts
  frontend/src/queries/tags/useTagListQuery.ts
  frontend/src/queries/templates/index.ts
  frontend/src/queries/templates/useTemplateCategoryTagQueries.ts
  frontend/src/routes/router.tsx
Labels: FE, refactor

#787 템플릿 공개 범위 설정( visibility) 기능 구현
  frontend/src/assets/images/Hamburger.tsx
  frontend/src/assets/images/index.ts
  frontend/src/assets/images/private.svg
  frontend/src/assets/images/public.svg
  frontend/src/components/CategoryDropdown/CategoryDropdown.style.ts
  frontend/src/components/CategoryDropdown/CategoryDropdown.tsx
  frontend/src/components/CategoryGuide/CategoryGuide.tsx
  frontend/src/components/Dropdown/Dropdown.tsx
  frontend/src/components/LikeButton/LikeButton.tsx
  frontend/src/components/LikeCounter/LikeCounter.tsx
  frontend/src/components/SourceCodeEditor/SourceCodeEditor.tsx
  frontend/src/components/TemplateCard/TemplateCard.stories.tsx
  frontend/src/components/TemplateCard/TemplateCard.style.ts
  frontend/src/components/TemplateCard/TemplateCard.tsx
  frontend/src/components/Toggle/Toggle.stories.tsx
  frontend/src/components/Toggle/Toggle.style.ts
  frontend/src/components/Toggle/Toggle.tsx
  frontend/src/components/index.ts
  frontend/src/mocks/templateList.json
  frontend/src/pages/LandingPage/LandingPage.tsx
  frontend/src/pages/MyTemplatesPage/components/CategoryEditModal/CategoryEditModal.tsx
  frontend/src/pages/MyTemplatesPage/components/CategoryFilterMenu/CategoryFilterMenu.tsx
  frontend/src/pages/MyTemplatesPage/components/TagFilterMenu/TagFilterMenu.tsx
  frontend/src/pages/MyTemplatesPage/components/TemplateGrid/TemplateGrid.stories.tsx
  frontend/src/pages/TemplateEditPage/TemplateEditPage.style.ts
  frontend/src/pages/TemplateEditPage/TemplateEditPage.tsx
  frontend/src/pages/TemplatePage/TemplatePage.style.ts
  frontend/src/pages/TemplatePage/TemplatePage.tsx
  frontend/src/pages/TemplateUploadPage/TemplateUploadPage.style.ts
  frontend/src/pages/TemplateUploadPage/TemplateUploadPage.tsx
  frontend/src/queries/templates/useTemplateEditMutation.spec.tsx
  frontend/src/queries/templates/useTemplateUploadMutation.spec.tsx
  frontend/src/service/constants.ts
  frontend/src/style/styleConstants.ts
  frontend/src/types/api.ts
  frontend/src/types/template.ts
Labels: feature, FE, zap

#772 TemplateControllerTest를 MockMvcTest로 변경
  backend/src/main/java/codezap/template/dto/request/CreateTemplateRequest.java
  backend/src/test/java/codezap/global/MockMvcTest.java
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
Labels: refactor, BE

#783 ApiError 및 ApiClient 생성으로 HTTP 요청 및 에러 핸들링 리팩토링
  frontend/package-lock.json
  frontend/package.json
  frontend/setupTests.ts
  frontend/src/api/ApiClient.ts
  frontend/src/api/Error/ApiError.ts
  frontend/src/api/Error/statusCode.ts
  frontend/src/api/authentication.ts
  frontend/src/api/categories.ts
  frontend/src/api/like.ts
  frontend/src/api/tags.ts
  frontend/src/api/templates.ts
  frontend/src/components/Error/TemporaryError.tsx
  frontend/src/components/index.ts
  frontend/src/pages/TemplateExplorePage/TemplateExplorePage.tsx
  frontend/src/pages/TemplateUploadPage/TemplateUploadPage.tsx
  frontend/src/queries/templates/useTemplateExploreQuery.ts
  frontend/src/queries/templates/useTemplateUploadMutation.spec.tsx
  frontend/src/queries/templates/useTemplateUploadMutation.ts
Labels: feature, FE

#789 CategoryControllerTest 에러코드 확인 로직 추가 및 개선
  backend/src/test/java/codezap/category/controller/CategoryControllerTest.java
Labels: refactor, BE

#814 확장자 기반으로 언어 태그 자동 생성 기능 추가
  frontend/src/components/SourceCodeEditor/SourceCodeEditor.tsx
  frontend/src/components/TagInput/TagInput.tsx
  frontend/src/hooks/template/useTag.ts
  frontend/src/pages/TemplateEditPage/TemplateEditPage.tsx
  frontend/src/pages/TemplateUploadPage/TemplateUploadPage.tsx
  frontend/src/utils/getLanguageByFileName.ts
  frontend/src/utils/index.ts
Labels: feature, FE

#804 모든 ServiceTest가 Base 클래스를 상속받도록 통일
  backend/src/test/java/codezap/auth/service/AuthServiceTest.java
  backend/src/test/java/codezap/category/service/CategoryServiceTest.java
  backend/src/test/java/codezap/global/ServiceTest.java
  backend/src/test/java/codezap/likes/service/LikesServiceTest.java
  backend/src/test/java/codezap/member/service/MemberServiceTest.java
  backend/src/test/java/codezap/tag/service/TagServiceTest.java
  backend/src/test/java/codezap/template/service/TemplateServiceTest.java
  backend/src/test/java/codezap/template/service/ThumbnailServiceTest.java
  backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
Labels: refactor, BE

#817 version 1.1.4 업데이트
  frontend/package.json
Labels: FE, zap

#785 템플릿 공개 범위 설정 기능 구현
  backend/src/main/java/codezap/member/domain/Member.java
  backend/src/main/java/codezap/template/domain/Template.java
  backend/src/main/java/codezap/template/dto/request/UpdateTemplateRequest.java
  backend/src/main/java/codezap/template/repository/TemplateSpecification.java
  backend/src/main/java/codezap/template/service/TemplateService.java
  backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
  backend/src/test/java/codezap/fixture/CategoryFixture.java
  backend/src/test/java/codezap/fixture/TemplateFixture.java
  backend/src/test/java/codezap/likes/repository/LikesJpaRepositoryTest.java
  backend/src/test/java/codezap/member/domain/MemberTest.java
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
  backend/src/test/java/codezap/template/repository/TemplateSearchJpaRepositoryTest.java
  backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java
  backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java
  backend/src/test/java/codezap/template/service/TemplateServiceTest.java
  backend/src/test/java/codezap/template/service/ThumbnailServiceTest.java
  backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
  backend/src/test/resources/search.sql
Labels: feature, BE

#797 LikeControllerTest 작성
  backend/src/test/java/codezap/global/MockMvcTest.java
  backend/src/test/java/codezap/likes/controller/LikesControllerTest.java
Labels: refactor, BE

#812 사용되지 않는 로그인용 조회 API 제거
  backend/src/main/java/codezap/template/controller/TemplateController.java
Labels: refactor, BE

#803 ZAP PR 생성 시 리뷰 메시지 변경
  .github/workflows/pr_notification.yml
Labels: FE, refactor, BE

#825 DB 설정 키를 변경
  backend/src/main/resources/application-db.yml
Labels: bug, zap, BE

#827 DB 설정 키를 변경
  backend/src/main/resources/application-db.yml
Labels: bug, BE

#836 태그 검색 조건 or로 변경
  backend/src/main/java/codezap/template/repository/TemplateSpecification.java
  backend/src/test/java/codezap/template/repository/TemplateSearchJpaRepositoryTest.java
  backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java
Labels: refactor, BE

#834 서비스 트랜잭션 적용
  backend/src/main/java/codezap/auth/service/AuthService.java
  backend/src/main/java/codezap/category/service/CategoryService.java
  backend/src/main/java/codezap/likes/service/LikesService.java
  backend/src/main/java/codezap/member/service/MemberService.java
  backend/src/main/java/codezap/tag/service/TagService.java
  backend/src/main/java/codezap/template/service/SourceCodeService.java
  backend/src/main/java/codezap/template/service/TemplateService.java
  backend/src/main/java/codezap/template/service/ThumbnailService.java
  backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
  backend/src/main/resources/application-db.yml
Labels: refactor, BE

#844 새 템플릿 업로드 시, 템플릿 순서 정렬
  frontend/src/pages/TemplateUploadPage/TemplateUploadPage.tsx
Labels: bug, FE, zap

#838 문의하기 모달 버그 수정 및 템플릿 수정시 visibility 기본값 설정
  frontend/src/components/ContactUs/ContactUs.style.ts
  frontend/src/components/ContactUs/ContactUs.tsx
  frontend/src/components/Modal/Modal.style.ts
  frontend/src/pages/LandingPage/LandingPage.tsx
  frontend/src/pages/MyTemplatesPage/components/ConfirmDeleteModal/ConfirmDeleteModal.tsx
  frontend/src/pages/TemplateEditPage/TemplateEditPage.tsx
Labels: bug, FE, zap

#835 Fake DB 제거
  backend/src/test/java/codezap/auth/provider/basic/BasicAuthCredentialProviderTest.java
  backend/src/test/java/codezap/category/repository/FakeCategoryRepository.java
  backend/src/test/java/codezap/likes/repository/FakeLikeRepository.java
  backend/src/test/java/codezap/member/repository/FakeMemberRepository.java
  backend/src/test/java/codezap/template/repository/FakeSourceCodeRepository.java
  backend/src/test/java/codezap/template/repository/FakeTagRepository.java
  backend/src/test/java/codezap/template/repository/FakeTemplateRepository.java
  backend/src/test/java/codezap/template/repository/FakeTemplateTagRepository.java
  backend/src/test/java/codezap/template/repository/FakeThumbnailRepository.java
Labels: refactor, BE

#811 사용자 id 로 사용자의 정보를 받아오는 기능 추가
  backend/src/main/java/codezap/member/controller/MemberController.java
  backend/src/main/java/codezap/member/controller/SpringDocMemberController.java
  backend/src/main/java/codezap/member/service/MemberService.java
  backend/src/test/java/codezap/member/controller/MemberControllerTest.java
  backend/src/test/java/codezap/member/service/MemberServiceTest.java
Labels: feature, BE

#847 Amplitude 초기 설정 및 핵심 기능(업로드) 트래킹
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Header/Header.tsx
  frontend/src/components/PagingButtons/PagingButtons.tsx
  frontend/src/components/SourceCodeViewer/SourceCodeViewer.tsx
  frontend/src/index.tsx
  frontend/src/pages/LandingPage/LandingPage.tsx
  frontend/src/pages/LoginPage/LoginPage.tsx
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
  frontend/src/pages/SignupPage/SignupPage.tsx
  frontend/src/pages/TemplateEditPage/TemplateEditPage.tsx
  frontend/src/pages/TemplateExplorePage/TemplateExplorePage.tsx
  frontend/src/pages/TemplatePage/TemplatePage.tsx
  frontend/src/pages/TemplateUploadPage/TemplateUploadPage.tsx
  frontend/src/service/amplitude/AmplitudeInitializer.tsx
  frontend/src/service/amplitude/getBrowser.ts
  frontend/src/service/amplitude/index.ts
  frontend/src/service/amplitude/track.ts
  frontend/src/service/amplitude/useTrackPageViewed.ts
Labels: feature, FE, zap

#849 구경가기 상단 캐러셀 구현
  frontend/src/api/templates.ts
  frontend/src/assets/images/clock.svg
  frontend/src/assets/images/person.svg
  frontend/src/components/Footer/Footer.tsx
  frontend/src/components/TemplateCard/TemplateCard.tsx
  frontend/src/pages/TemplateExplorePage/TemplateExplorePage.style.ts
  frontend/src/pages/TemplateExplorePage/TemplateExplorePage.tsx
  frontend/src/pages/TemplateExplorePage/components/.gitkeep
  frontend/src/pages/TemplateExplorePage/components/Carousel/Carousel.style.ts
  frontend/src/pages/TemplateExplorePage/components/Carousel/Carousel.tsx
  frontend/src/pages/TemplateExplorePage/components/HotTopicCarousel/HotTopicCarousel.style.ts
  frontend/src/pages/TemplateExplorePage/components/HotTopicCarousel/HotTopicCarousel.tsx
  frontend/src/pages/TemplateExplorePage/components/index.ts
  frontend/src/pages/TemplateExplorePage/hooks/.gitkeep
  frontend/src/pages/TemplateExplorePage/hooks/index.ts
  frontend/src/pages/TemplateExplorePage/hooks/useHotTopic.ts
  frontend/src/pages/TemplatePage/TemplatePage.tsx
  frontend/src/queries/templates/useTemplateExploreQuery.ts
  frontend/src/style/styleConstants.ts
Labels: feature, FE, zap

#853 현재 필터링 조건(page, sort, keyword 등) useSearchParams로 저장
  frontend/src/hooks/index.ts
  frontend/src/hooks/template/useSearchKeyword.ts
  frontend/src/hooks/useQueryParams.ts
  frontend/src/pages/MyTemplatesPage/hooks/useFilteredTemplateList.ts
  frontend/src/pages/TemplateExplorePage/TemplateExplorePage.tsx
  frontend/src/service/getSortingOptionByValue.ts
Labels: feature, FE, zap

#815 멤버 별 템플릿 페이지 구현
  frontend/package.json
  frontend/src/api/categories.ts
  frontend/src/api/index.ts
  frontend/src/api/members.ts
  frontend/src/api/queryKeys.ts
  frontend/src/api/tags.ts
  frontend/src/components/Header/Header.tsx
  frontend/src/components/TemplateCard/TemplateCard.style.ts
  frontend/src/components/TemplateCard/TemplateCard.tsx
  frontend/src/hooks/category/useCategory.ts
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
  frontend/src/pages/MyTemplatesPage/components/CategoryFilterMenu/CategoryFilterMenu.tsx
  frontend/src/pages/MyTemplatesPage/components/CategoryListSection/CategoryListSection.tsx
  frontend/src/pages/MyTemplatesPage/components/TagListSection/TagListSection.tsx
  frontend/src/pages/MyTemplatesPage/components/TemplateGrid/TemplateGrid.tsx
  frontend/src/pages/MyTemplatesPage/hooks/useFilteredTemplateList.ts
  frontend/src/pages/TemplateEditPage/TemplateEditPage.tsx
  frontend/src/pages/TemplatePage/TemplatePage.style.ts
  frontend/src/pages/TemplatePage/TemplatePage.tsx
  frontend/src/pages/TemplatePage/hooks/useTemplate.ts
  frontend/src/pages/TemplateUploadPage/TemplateUploadPage.tsx
  frontend/src/queries/authentication/useLoginMutation.ts
  frontend/src/queries/categories/useCategoryListQuery.spec.tsx
  frontend/src/queries/categories/useCategoryListQuery.ts
  frontend/src/queries/members/index.ts
  frontend/src/queries/members/useMemberNameQuery.ts
  frontend/src/queries/tags/useTagListQuery.spec.tsx
  frontend/src/queries/tags/useTagListQuery.ts
  frontend/src/queries/templates/useTemplateListQuery.ts
  frontend/src/routes/endPoints.ts
  frontend/src/routes/router.tsx
  frontend/src/types/api.ts
  frontend/src/types/index.ts
Labels: feature, FE

#855 [BE] 코드잽 프로덕션 v1.1.5 배포
  backend/src/main/java/codezap/member/controller/MemberController.java
  backend/src/main/java/codezap/member/controller/SpringDocMemberController.java
  backend/src/main/java/codezap/member/service/MemberService.java
  backend/src/test/java/codezap/auth/provider/basic/BasicAuthCredentialProviderTest.java
  backend/src/test/java/codezap/category/repository/FakeCategoryRepository.java
  backend/src/test/java/codezap/likes/repository/FakeLikeRepository.java
  backend/src/test/java/codezap/member/controller/MemberControllerTest.java
  backend/src/test/java/codezap/member/repository/FakeMemberRepository.java
  backend/src/test/java/codezap/member/service/MemberServiceTest.java
  backend/src/test/java/codezap/template/repository/FakeSourceCodeRepository.java
  backend/src/test/java/codezap/template/repository/FakeTagRepository.java
  backend/src/test/java/codezap/template/repository/FakeTemplateRepository.java
  backend/src/test/java/codezap/template/repository/FakeTemplateTagRepository.java
  backend/src/test/java/codezap/template/repository/FakeThumbnailRepository.java
Labels: feature, zap, BE

#852 상세 조회에서 다른 사람의 비공개 템플릿 확인 시 예외 처리
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
  backend/src/main/java/codezap/template/domain/Template.java
  backend/src/main/java/codezap/template/service/TemplateService.java
  backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
  backend/src/main/java/codezap/template/service/facade/TemplateOwnershipChecker.java
  backend/src/test/java/codezap/template/domain/TemplateTest.java
  backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
Labels: refactor, zap, BE

#866 인기 토픽 배너 수정 및 url 로 필터 정보 저장하도록 변경
  frontend/src/assets/images/topic_algorithm.jpg
  frontend/src/assets/images/topic_android.jpg
  frontend/src/assets/images/topic_java.jpg
  frontend/src/assets/images/topic_js.jpg
  frontend/src/assets/images/topic_kt.jpg
  frontend/src/assets/images/topic_precourse.jpg
  frontend/src/assets/images/topic_react.jpg
  frontend/src/assets/images/topic_spring.jpg
  frontend/src/assets/images/topic_wooteco.jpg
  frontend/src/components/SourceCodeViewer/SourceCodeViewer.style.ts
  frontend/src/pages/MyTemplatesPage/hooks/useFilteredTemplateList.ts
  frontend/src/pages/TemplateExplorePage/TemplateExplorePage.tsx
  frontend/src/pages/TemplateExplorePage/components/Carousel/Carousel.style.ts
  frontend/src/pages/TemplateExplorePage/components/Carousel/Carousel.tsx
  frontend/src/pages/TemplateExplorePage/components/HotTopicCarousel/HotTopicCarousel.style.ts
  frontend/src/pages/TemplateExplorePage/components/HotTopicCarousel/HotTopicCarousel.tsx
  frontend/src/pages/TemplateExplorePage/hooks/useHotTopic.ts
  frontend/src/pages/TemplatePage/TemplatePage.style.ts
  frontend/src/service/hotTopic.ts
  frontend/src/types/images.d.ts
  frontend/webpack.common.js
Labels: FE, zap

#848 좋아요한 템플릿 목록 조회 API 구현
  backend/src/main/java/codezap/likes/repository/LikesJpaRepository.java
  backend/src/main/java/codezap/likes/repository/LikesRepository.java
  backend/src/main/java/codezap/likes/service/LikesService.java
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
  backend/src/main/java/codezap/template/controller/TemplateController.java
  backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
  backend/src/test/java/codezap/global/MockMvcTest.java
  backend/src/test/java/codezap/likes/repository/LikesJpaRepositoryTest.java
  backend/src/test/java/codezap/likes/service/LikesServiceTest.java
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
  backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
Labels: feature, BE

#871 full text index 한글 필드에 대해 n-gram parser 적용
  backend/src/main/resources/db/migration/V8__replace_ft_parser.sql
  backend/src/test/java/codezap/fixture/TemplateFixture.java
  backend/src/test/java/codezap/global/DatabaseCleaner.java
  backend/src/test/java/codezap/template/repository/TemplateSearchJpaRepositoryTest.java
  backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java
Labels: feature, zap, BE

#870 템플릿 카드의 클릭 가능 영역 변경 및 유저 이름 클릭 시 유저 페이지로 이동
  frontend/src/components/AuthorInfo/AuthorInfo.style.ts
  frontend/src/components/AuthorInfo/AuthorInfo.tsx
  frontend/src/components/TemplateCard/TemplateCard.style.ts
  frontend/src/components/TemplateCard/TemplateCard.tsx
  frontend/src/pages/MyTemplatesPage/components/TemplateGrid/TemplateGrid.tsx
  frontend/src/pages/TemplateExplorePage/TemplateExplorePage.tsx
  frontend/src/pages/TemplatePage/TemplatePage.style.ts
  frontend/src/pages/TemplatePage/TemplatePage.tsx
Labels: FE, refactor

#873 사용자 이름 ellipsis 처리 및 모바일 환경일 때 템플릿 카드의 시간 숨김
  frontend/src/components/AuthorInfo/AuthorInfo.style.ts
  frontend/src/components/TemplateCard/TemplateCard.style.ts
  frontend/src/components/TemplateCard/TemplateCard.tsx
Labels: FE, refactor, zap

#874 SourceCode 컴포넌트의 최소 높이 설정
  frontend/src/components/SourceCode/SourceCode.tsx
Labels: FE, refactor

#875 모바일 환경의 SourceCode 폰트 사이즈 변경
  frontend/src/components/AuthorInfo/AuthorInfo.style.ts
  frontend/src/components/SourceCode/SourceCode.tsx
Labels: FE, refactor

#878 내템플릿, 구경가기, 좋아요한 템플릿 타이틀 모바일 반응형 적용
  frontend/src/pages/MyLikedTemplatePage/MyLikedTemplatePage.style.ts
  frontend/src/pages/MyLikedTemplatePage/MyLikedTemplatePage.tsx
  frontend/src/pages/MyTemplatesPage/components/TopBanner/TopBanner.style.ts
  frontend/src/pages/MyTemplatesPage/components/TopBanner/TopBanner.tsx
  frontend/src/pages/TemplateExplorePage/TemplateExplorePage.tsx
Labels: FE, refactor, zap

#879 SourceCode 폰트 사이즈 조정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/SourceCode/SourceCode.tsx
Labels: FE, refactor

#884 SourceCode mode에 따라 minHeight 적용 추가
  frontend/src/components/SourceCode/SourceCode.tsx
Labels: bug, FE

#885 visibility toggle 색상 변경 및 상세 페이지 공유 버튼 추가
  frontend/public/index.html
  frontend/src/assets/images/index.ts
  frontend/src/assets/images/share.svg
  frontend/src/components/Modal/Modal.style.ts
  frontend/src/pages/TemplateEditPage/TemplateEditPage.style.ts
  frontend/src/pages/TemplateEditPage/TemplateEditPage.tsx
  frontend/src/pages/TemplatePage/TemplatePage.style.ts
  frontend/src/pages/TemplatePage/TemplatePage.tsx
  frontend/src/pages/TemplateUploadPage/TemplateUploadPage.tsx
  frontend/src/service/amplitude/track.ts
Labels: feature, FE, refactor, zap

#886 타 유저의 Private 경로 진입 시, Forbidden 페이지 전환
  frontend/src/api/templates.ts
  frontend/src/components/Layout/Layout.tsx
  frontend/src/pages/ForbiddenPage/ForbiddenPage.tsx
  frontend/src/queries/templates/useTemplateQuery.ts
Labels: FE, refactor, zap

#887 [FE] Public 아이콘 색상 변경, Private 라우트 Forbidden 전환
  frontend/public/index.html
  frontend/src/api/templates.ts
  frontend/src/assets/images/index.ts
  frontend/src/assets/images/share.svg
  frontend/src/components/Layout/Layout.tsx
  frontend/src/components/Modal/Modal.style.ts
  frontend/src/components/SourceCode/SourceCode.tsx
  frontend/src/pages/ForbiddenPage/ForbiddenPage.tsx
  frontend/src/pages/TemplateEditPage/TemplateEditPage.style.ts
  frontend/src/pages/TemplateEditPage/TemplateEditPage.tsx
  frontend/src/pages/TemplatePage/TemplatePage.style.ts
  frontend/src/pages/TemplatePage/TemplatePage.tsx
  frontend/src/pages/TemplateUploadPage/TemplateUploadPage.tsx
  frontend/src/queries/templates/useTemplateQuery.ts
  frontend/src/service/amplitude/track.ts
Labels: FE, refactor

#889 스토리북 Preview에 AuthProvider, ToastProvider 설정 추가
  frontend/.storybook/preview.tsx
  frontend/package-lock.json
  frontend/public/mockServiceWorker.js
  frontend/src/pages/MyTemplatesPage/components/TemplateGrid/TemplateGrid.stories.tsx
Labels: FE, refactor
