Repository woowacourse-teams/2024-code-zap, pull requests merged in 2024-11, with the labels that each got.

#891 로그인하지 않아도 사용자 페이지 접근 가능하도록 RouteGuard 제거
  frontend/src/components/SelectList/SelectList.style.ts
  frontend/src/components/SelectList/SelectList.tsx
  frontend/src/components/SourceCode/SourceCode.tsx
  frontend/src/components/SourceCodeEditor/SourceCodeEditor.tsx
  frontend/src/components/SourceCodeViewer/SourceCodeViewer.style.ts
  frontend/src/components/Toast/Toast.style.ts
  frontend/src/pages/TemplatePage/TemplatePage.tsx
  frontend/src/routes/router.tsx
Labels: bug, FE, zap

#869 QueryDSL 도입
  backend/build.gradle
  backend/src/main/java/codezap/category/repository/CategoryJpaRepository.java
  backend/src/main/java/codezap/category/repository/CategoryRepository.java
  backend/src/main/java/codezap/global/querydsl/QueryDSLConfig.java
  backend/src/main/java/codezap/global/rds/DataSourceConfig.java
  backend/src/main/java/codezap/likes/repository/LikesJpaRepository.java
  backend/src/main/java/codezap/likes/repository/LikesQueryDslRepository.java
  backend/src/main/java/codezap/likes/repository/LikesRepository.java
  backend/src/main/java/codezap/member/controller/MemberController.java
  backend/src/main/java/codezap/member/controller/SpringDocMemberController.java
  backend/src/main/java/codezap/member/repository/MemberJpaRepository.java
  backend/src/main/java/codezap/member/repository/MemberQueryDSLRepository.java
  backend/src/main/java/codezap/member/repository/MemberRepository.java
  backend/src/main/java/codezap/member/service/MemberService.java
  backend/src/main/java/codezap/tag/repository/TagJpaRepository.java
  backend/src/main/java/codezap/tag/repository/TagRepository.java
  backend/src/main/java/codezap/tag/repository/TemplateTagJpaRepository.java
  backend/src/main/java/codezap/tag/repository/TemplateTagQueryDSLRepository.java
  backend/src/main/java/codezap/tag/repository/TemplateTagRepository.java
  backend/src/main/java/codezap/template/domain/TemplateTag.java
  backend/src/main/java/codezap/template/repository/FullTextFunctionContributor.java
  backend/src/main/java/codezap/template/repository/FullTextSearchMySQLDialect.java
  backend/src/main/java/codezap/template/repository/SourceCodeJpaRepository.java
  backend/src/main/java/codezap/template/repository/SourceCodeQueryDSLRepository.java
  backend/src/main/java/codezap/template/repository/SourceCodeRepository.java
  backend/src/main/java/codezap/template/repository/TemplateJpaRepository.java
  backend/src/main/java/codezap/template/repository/TemplateOrderSpecifierUtils.java
  backend/src/main/java/codezap/template/repository/TemplateQueryDSLRepository.java
  backend/src/main/java/codezap/template/repository/TemplateRepository.java
  backend/src/main/java/codezap/template/repository/TemplateSearchExpressionProvider.java
  backend/src/main/java/codezap/template/repository/TemplateSpecification.java
  backend/src/main/java/codezap/template/repository/ThumbnailJpaRepository.java
  backend/src/main/java/codezap/template/repository/ThumbnailQueryDSLRepository.java
  backend/src/main/java/codezap/template/repository/ThumbnailRepository.java
  backend/src/main/java/codezap/template/repository/strategy/FullTextSearchSearchStrategy.java
  backend/src/main/java/codezap/template/repository/strategy/LikeSearchStrategy.java
  backend/src/main/java/codezap/template/repository/strategy/SearchStrategy.java
  backend/src/main/java/codezap/template/service/TemplateService.java
  backend/src/main/resources/META-INF/services/org.hibernate.boot.model.FunctionContributor
  backend/src/main/resources/application-db.yml
  backend/src/main/resources/application-local.yml
  backend/src/test/java/codezap/auth/provider/basic/BasicAuthCredentialProviderTest.java
  backend/src/test/java/codezap/category/repository/CategoryRepositoryTest.java
  backend/src/test/java/codezap/global/repository/JpaRepositoryTest.java
  backend/src/test/java/codezap/global/repository/RepositoryTest.java
  backend/src/test/java/codezap/likes/repository/LikesRepositoryTest.java
  backend/src/test/java/codezap/member/repository/MemberRepositoryTest.java
  backend/src/test/java/codezap/tag/repository/TagRepositoryTest.java
  backend/src/test/java/codezap/tag/repository/TemplateTagRepositoryTest.java
  backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
  backend/src/test/java/codezap/template/repository/TemplateRepositoryTest.java
  backend/src/test/java/codezap/template/repository/TemplateSearchRepositoryTest.java
  backend/src/test/java/codezap/template/repository/ThumbnailRepositoryTest.java
  backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
Labels: refactor, BE

#893 좋아요 컬럼 반정규화
  backend/src/main/java/codezap/likes/service/LikesService.java
  backend/src/main/java/codezap/template/domain/Template.java
  backend/src/main/resources/db/migration/V9__like_column_denormalization.sql
  backend/src/test/java/codezap/likes/service/LikesServiceTest.java
  backend/src/test/java/codezap/template/domain/TemplateTest.java
  backend/src/test/java/codezap/template/service/TemplateServiceTest.java
Labels: refactor, BE

#902 페이지네이션 처리 시 최대 다음 페이지 수를 5개로 제한
  backend/src/main/java/codezap/global/pagination/FixedPage.java
  backend/src/main/java/codezap/global/pagination/FixedPageCounter.java
  backend/src/main/java/codezap/likes/repository/LikesJpaRepository.java
  backend/src/main/java/codezap/likes/repository/LikesRepository.java
  backend/src/main/java/codezap/likes/service/LikesService.java
  backend/src/main/java/codezap/template/dto/response/FindAllTemplatesResponse.java
  backend/src/main/java/codezap/template/repository/TemplateQueryDSLRepository.java
  backend/src/main/java/codezap/template/repository/TemplateRepository.java
  backend/src/main/java/codezap/template/service/TemplateService.java
  backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
  backend/src/test/java/codezap/global/pagination/FixedPageCounterTest.java
  backend/src/test/java/codezap/global/repository/RepositoryTest.java
  backend/src/test/java/codezap/likes/repository/LikesRepositoryTest.java
  backend/src/test/java/codezap/likes/service/LikesServiceTest.java
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
  backend/src/test/java/codezap/template/repository/TemplateRepositoryTest.java
  backend/src/test/java/codezap/template/repository/TemplateSearchRepositoryTest.java
  backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java
  backend/src/test/java/codezap/template/service/TemplateServiceTest.java
  backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
  backend/src/test/resources/search.sql
Labels: refactor, BE

#897 Jest 설정 변경 - 정적 파일 transform 설정
  frontend/jest.config.ts
  frontend/package-lock.json
  frontend/src/api/ApiClient.ts
  frontend/src/api/authentication.ts
  frontend/src/api/categories.ts
  frontend/src/api/like.ts
  frontend/src/api/members.ts
  frontend/src/api/tags.ts
  frontend/src/api/templates.ts
  frontend/src/mocks/fileTransformer.js
Labels: FE, zap

#906 totalPages => paginationSizes 로 변경
  frontend/src/components/PagingButtons/PagingButtons.stories.tsx
  frontend/src/components/PagingButtons/PagingButtons.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/pages/MyLikedTemplatePage/MyLikedTemplatePage.tsx
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
  frontend/src/pages/MyTemplatesPage/hooks/useFilteredTemplateList.ts
  frontend/src/pages/TemplateExplorePage/TemplateExplorePage.tsx
  frontend/src/service/amplitude/track.ts
  frontend/src/types/api.ts
Labels: FE, refactor

#915 템플릿 검색시 엔터를 눌러야 검색되도록 변경
  frontend/src/hooks/template/index.ts
  frontend/src/hooks/template/useSearchKeyword.ts
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.style.ts
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
  frontend/src/pages/MyTemplatesPage/hooks/useFilteredTemplateList.ts
  frontend/src/pages/TemplateExplorePage/TemplateExplorePage.style.ts
  frontend/src/pages/TemplateExplorePage/TemplateExplorePage.tsx
Labels: FE, refactor

#918 version 1.1.7 변경 및 theme 미적용 파일 수정
  frontend/package.json
  frontend/src/pages/LoginPage/LoginPage.tsx
  frontend/src/pages/SignupPage/SignupPage.tsx
Labels: FE, refactor

#914 콘솔 로그 하이라이팅
  backend/src/main/resources/logger/console/console-appender.xml
Labels: refactor, BE

#917 [FE] 코드잽 프로덕션 v1.1.7 배포
  frontend/.storybook/preview.tsx
  frontend/jest.config.ts
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/api/ApiClient.ts
  frontend/src/api/authentication.ts
  frontend/src/api/categories.ts
  frontend/src/api/like.ts
  frontend/src/api/members.ts
  frontend/src/api/tags.ts
  frontend/src/api/templates.ts
  frontend/src/components/PagingButtons/PagingButtons.stories.tsx
  frontend/src/components/PagingButtons/PagingButtons.tsx
  frontend/src/components/SelectList/SelectList.style.ts
  frontend/src/components/SelectList/SelectList.tsx
  frontend/src/components/SourceCode/SourceCode.tsx
  frontend/src/components/SourceCodeEditor/SourceCodeEditor.tsx
  frontend/src/components/SourceCodeViewer/SourceCodeViewer.style.ts
  frontend/src/components/Toast/Toast.style.ts
  frontend/src/hooks/template/index.ts
  frontend/src/hooks/template/useSearchKeyword.ts
  frontend/src/mocks/fileTransformer.js
  frontend/src/mocks/handlers.ts
  frontend/src/pages/LoginPage/LoginPage.tsx
  frontend/src/pages/MyLikedTemplatePage/MyLikedTemplatePage.tsx
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.style.ts
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
  frontend/src/pages/MyTemplatesPage/components/TemplateGrid/TemplateGrid.stories.tsx
  frontend/src/pages/MyTemplatesPage/hooks/useFilteredTemplateList.ts
  frontend/src/pages/SignupPage/SignupPage.tsx
  frontend/src/pages/TemplateExplorePage/TemplateExplorePage.style.ts
  frontend/src/pages/TemplateExplorePage/TemplateExplorePage.tsx
  frontend/src/pages/TemplatePage/TemplatePage.tsx
  frontend/src/routes/router.tsx
  frontend/src/service/amplitude/track.ts
  frontend/src/types/api.ts
Labels: feature, FE, zap

#922 태그가 중복 저장되는 버그 해결
  backend/src/main/java/codezap/tag/service/TagService.java
  backend/src/test/java/codezap/tag/service/TagServiceTest.java
Labels: bug, BE

#936 index의 중복 적용된 Suspense, ErrorBoundary 제거
  frontend/src/components/Layout/Layout.tsx
  frontend/src/routes/router.tsx
Labels: FE, refactor
