Repository woowacourse-teams/2024-code-zap, pull requests merged in 2024-09, with the labels that each got.

#582 로그인 상태일 때, 랜딩 페이지의 로그인, 회원가입 하러가기 버튼 숨기는 기능
  frontend/src/pages/LandingPage/LandingPage.tsx
Labels: feature, FE, zap

#587 Layout에 Footer 추가
  frontend/src/components/Footer/Footer.style.ts
  frontend/src/components/Footer/Footer.tsx
  frontend/src/components/Layout/Layout.tsx
  frontend/src/components/index.ts
Labels: feature, FE, zap

#593 비밀번호 암호화
  backend/src/main/java/codezap/auth/encryption/PasswordEncryptor.java
  backend/src/main/java/codezap/auth/encryption/RandomSaltGenerator.java
  backend/src/main/java/codezap/auth/encryption/SHA2PasswordEncryptor.java
  backend/src/main/java/codezap/auth/encryption/SaltGenerator.java
  backend/src/main/java/codezap/auth/service/AuthService.java
  backend/src/main/java/codezap/member/domain/Member.java
  backend/src/main/java/codezap/member/service/MemberService.java
  backend/src/main/resources/db/migration/V2__add_salt.sql
  backend/src/test/java/codezap/auth/encryption/RandomSaltGeneratorTest.java
  backend/src/test/java/codezap/auth/encryption/SHA2PasswordEncryptorTest.java
  backend/src/test/java/codezap/auth/service/AuthServiceTest.java
  backend/src/test/java/codezap/fixture/MemberFixture.java
  backend/src/test/java/codezap/member/fixture/MemberFixture.java
  backend/src/test/java/codezap/member/repository/FakeMemberRepository.java
  backend/src/test/java/codezap/member/service/MemberServiceTest.java
  backend/src/test/java/codezap/tag/repository/TemplateTagJpaRepositoryTest.java
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
  backend/src/test/java/codezap/template/repository/TemplateRepositoryFindAllTest.java
Labels: feature, BE

#595 cors를 허용하는 origin 지정
  backend/src/main/java/codezap/global/cors/WebCorsConfiguration.java
Labels: refactor, BE

#597 Revert "cors를 허용하는 origin 지정"
  backend/src/main/java/codezap/global/cors/WebCorsConfiguration.java
Labels: bug, BE

#598 cors를 허용하는 origin 지정
  backend/src/main/java/codezap/global/cors/WebCorsConfiguration.java
Labels: refactor, BE

#588 템플릿 생성 실패한 경우, 토스트로 알림 및 라우터 유지하도록 변경
  frontend/src/api/customFetch.ts
  frontend/src/api/templates.ts
  frontend/src/components/CategoryEditModal/CategoryEditModal.tsx
  frontend/src/components/TemplateEdit/TemplateEdit.tsx
  frontend/src/hooks/template/useTemplateUpload.ts
Labels: FE, refactor, zap

#596 파일명, 소스코드 길이 제한
  frontend/src/components/SourceCodeEditor/SourceCodeEditor.tsx
  frontend/src/service/index.ts
  frontend/src/service/validates.ts
  frontend/src/utils/getByteSize.ts
  frontend/src/utils/index.ts
Labels: FE, refactor

#605 cors 설정 롤백
  backend/src/main/java/codezap/global/cors/WebCorsConfiguration.java
Labels: zap, BE

#604 [BE] 코드잽 프로덕션 v1.1.1 배포
  backend/src/main/java/codezap/auth/encryption/PasswordEncryptor.java
  backend/src/main/java/codezap/auth/encryption/RandomSaltGenerator.java
  backend/src/main/java/codezap/auth/encryption/SHA2PasswordEncryptor.java
  backend/src/main/java/codezap/auth/encryption/SaltGenerator.java
  backend/src/main/java/codezap/auth/service/AuthService.java
  backend/src/main/java/codezap/member/domain/Member.java
  backend/src/main/java/codezap/member/service/MemberService.java
  backend/src/main/resources/db/migration/V2__add_salt.sql
  backend/src/test/java/codezap/auth/encryption/RandomSaltGeneratorTest.java
  backend/src/test/java/codezap/auth/encryption/SHA2PasswordEncryptorTest.java
  backend/src/test/java/codezap/auth/service/AuthServiceTest.java
  backend/src/test/java/codezap/fixture/MemberFixture.java
  backend/src/test/java/codezap/member/fixture/MemberFixture.java
  backend/src/test/java/codezap/member/repository/FakeMemberRepository.java
  backend/src/test/java/codezap/member/service/MemberServiceTest.java
  backend/src/test/java/codezap/tag/repository/TemplateTagJpaRepositoryTest.java
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
  backend/src/test/java/codezap/template/repository/TemplateRepositoryFindAllTest.java
Labels: BE

#603 아이디, 비밀번호 글자수 상한선 제한
  frontend/src/pages/LoginPage/LoginPage.tsx
  frontend/src/pages/SignupPage/SignupPage.tsx
  frontend/src/service/validates.ts
Labels: bug, FE, zap

#606 최상위 도메인 cors 허용
  backend/src/main/java/codezap/auth/service/AuthService.java
  backend/src/main/java/codezap/global/cors/WebCorsConfiguration.java
  backend/src/main/java/codezap/member/service/MemberService.java
  backend/src/main/java/codezap/tag/controller/TagController.java
Labels: bug, BE

#607 현재 선택된 카테고리 삭제 시 '전체 보기'로 변경
  frontend/src/components/CategoryEditModal/CategoryEditModal.tsx
  frontend/src/components/CategoryFilterMenu/CategoryFilterMenu.tsx
Labels: FE, refactor

#601 프론트엔드 CD 복구
  .github/workflows/frontend_cd.yml
Labels: bug, FE, zap

#608 cors 설정을 스프링 코드에서 제거
  backend/src/main/java/codezap/global/cors/WebCorsConfiguration.java
Labels: bug, BE

#612 Revert "cors 설정을 스프링 코드에서 제거"
  backend/src/main/java/codezap/global/cors/WebCorsConfiguration.java
Labels: BE

#610 [FE] 코드잽 프로덕션 v1.1.1 배포
  .github/workflows/frontend_cd.yml
  frontend/src/api/customFetch.ts
  frontend/src/api/templates.ts
  frontend/src/components/CategoryEditModal/CategoryEditModal.tsx
  frontend/src/components/CategoryFilterMenu/CategoryFilterMenu.tsx
  frontend/src/components/Footer/Footer.style.ts
  frontend/src/components/Footer/Footer.tsx
  frontend/src/components/Layout/Layout.tsx
  frontend/src/components/SourceCodeEditor/SourceCodeEditor.tsx
  frontend/src/components/TemplateEdit/TemplateEdit.tsx
  frontend/src/components/index.ts
  frontend/src/hooks/template/useTemplateUpload.ts
  frontend/src/pages/LandingPage/LandingPage.tsx
  frontend/src/pages/LoginPage/LoginPage.tsx
  frontend/src/pages/SignupPage/SignupPage.tsx
  frontend/src/service/index.ts
  frontend/src/service/validates.ts
  frontend/src/utils/getByteSize.ts
  frontend/src/utils/index.ts
Labels: feature, FE, zap

#613 [BE] 코드잽 프로덕션 v1.1.1 배포
  backend/src/main/java/codezap/auth/service/AuthService.java
  backend/src/main/java/codezap/global/cors/WebCorsConfiguration.java
  backend/src/main/java/codezap/member/service/MemberService.java
  backend/src/main/java/codezap/tag/controller/TagController.java
Labels: feature, BE

#616 크롬 extension cors 설정 추가
  backend/src/main/java/codezap/global/cors/WebCorsConfiguration.java
Labels: bug, BE

#617 [BE] 크롬 익스텐션 CORS 해결
  backend/src/main/java/codezap/global/cors/WebCorsConfiguration.java
Labels: bug, BE

#619 cors allow origin 을 yml에서 읽어오도록 변경
  backend/src/main/java/codezap/global/cors/CorsProperties.java
  backend/src/main/java/codezap/global/cors/WebCorsConfiguration.java
  backend/src/main/resources/application-local.yml
  backend/src/test/java/codezap/global/MockMvcTest.java
  backend/src/test/java/codezap/global/cors/CorsPropertiesTest.java
  backend/src/test/resources/application-local.yml
Labels: refactor, BE

#622 [BE] allow origin 을 yml에서 읽어오도록 변경
  .github/workflows/backend_cd.yml
  .github/workflows/backend_ci.yml
  backend/src/main/java/codezap/global/cors/CorsProperties.java
  backend/src/main/java/codezap/global/cors/WebCorsConfiguration.java
  backend/src/main/resources/application-local.yml
  backend/src/test/java/codezap/global/MockMvcTest.java
  backend/src/test/java/codezap/global/cors/CorsPropertiesTest.java
  backend/src/test/resources/application-local.yml
Labels: bug, refactor, zap, BE

#625 TagJpaRepository 테스트 구현
  backend/src/main/java/codezap/tag/repository/TagJpaRepository.java
  backend/src/test/java/codezap/tag/repository/TagJpaRepositoryTest.java
Labels: refactor, BE

#621 TemplateTagRepository 테스트
  backend/src/test/java/codezap/tag/repository/TemplateTagJpaRepositoryTest.java
Labels: BE

#624 MemberJpaRepository 테스트 구현
  backend/src/main/java/codezap/member/repository/MemberJpaRepository.java
  backend/src/test/java/codezap/member/repository/MemberJpaRepositoryTest.java
Labels: refactor, BE

#626 SourceCodeJpaRepository 테스트 구현
  backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
Labels: feature, BE

#629 Template Repository단 테스트 작성
  backend/src/test/java/codezap/fixture/TemplateFixture.java
  backend/src/test/java/codezap/template/repository/TemplateJpaRepositoryTest.java
  backend/src/test/java/codezap/template/repository/TemplateRepositoryFindAllTest.java
Labels: refactor, BE

#627 ThumbnailRepositoryTest 구현
  backend/src/test/java/codezap/template/repository/ThumbnailRepositoryTest.java
Labels: BE

#628 CategoryRepositoryTest 구현
  backend/src/test/java/codezap/category/repository/CategoryRepositoryTest.java
Labels: BE

#644 프론트엔드 E2E 테스트 - playwright 설정
  .github/workflows/frontend_playwright.yml
  frontend/.gitignore
  frontend/e2eTests/example.spec.ts
  frontend/jest.config.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/playwright.config.ts
Labels: feature, FE

#672 핵심기능 E2E 테스트 - 카테고리, 검색
  frontend/e2eTests/category.actions.ts
  frontend/e2eTests/category.spec.ts
  frontend/e2eTests/example.spec.ts
  frontend/e2eTests/search.actions.ts
  frontend/e2eTests/search.spec.ts
  frontend/e2eTests/utils.ts
  frontend/package-lock.json
  frontend/playwright.config.ts
Labels: feature, FE

#653 SourceCodeService 테스트 추가
  backend/src/test/java/codezap/fixture/SourceCodeFixture.java
  backend/src/test/java/codezap/global/ServiceTest.java
  backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java
Labels: refactor, BE

#646 Member Service 테스트
  backend/src/test/java/codezap/global/cors/CorsPropertiesTest.java
  backend/src/test/java/codezap/global/repository/JpaRepositoryTest.java
  backend/src/test/java/codezap/member/service/MemberServiceTest.java
Labels: refactor, BE

#654 MemberCategoryApplicationService 테스트
  backend/src/test/java/codezap/category/service/facade/MemberCategoryApplicationServiceTest.java
Labels: BE

#655 MemberCategoryTemplateApplicationService 테스트
  backend/src/test/java/codezap/category/service/facade/MemberCategoryTemplateApplicationServiceTest.java
Labels: BE

#661 TemplateServiceTest 추가
  backend/src/test/java/codezap/template/repository/TemplateJpaRepositoryTest.java
  backend/src/test/java/codezap/template/service/TemplateServiceTest.java
Labels: refactor, BE

#658 CategoryTemplateService 테스트
  backend/src/test/java/codezap/category/service/CategoryTemplateServiceTest.java
Labels: refactor, BE

#662 썸네일 서비스 테스트코드 작성
  backend/src/test/java/codezap/template/service/ThumbnailServiceTest.java
Labels: refactor, BE

#665 TemplateApplicationService 테스트
  backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
Labels: BE

#656 CategoryService 테스트
  backend/src/test/java/codezap/category/service/CategoryServiceTest.java
Labels: refactor, BE

#666 MemberTemplateApplicationService 테스트
  backend/src/main/java/codezap/category/domain/Category.java
  backend/src/test/java/codezap/template/service/facade/MemberTemplateApplicationServiceTest.java
Labels: BE

#675 좋아요 swagger 문서화 제공
  backend/src/main/java/codezap/like/controller/LikeController.java
  backend/src/main/java/codezap/like/controller/SpringDocsLikeController.java
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
  backend/src/main/java/codezap/template/dto/response/FindAllTemplateItemResponse.java
  backend/src/main/java/codezap/template/dto/response/FindTemplateResponse.java
  backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
Labels: documentation, BE

#669 group 설정 추가로 @Validated 검증 로직 보완
  backend/src/main/java/codezap/template/dto/request/CreateSourceCodeRequest.java
  backend/src/main/java/codezap/template/dto/request/CreateTemplateRequest.java
  backend/src/main/java/codezap/template/dto/request/UpdateSourceCodeRequest.java
  backend/src/main/java/codezap/template/dto/request/UpdateTemplateRequest.java
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
Labels: bug, BE

#647 핵심기능 E2E 테스트 - 템플릿, 인증/인가
  .gitignore
  frontend/e2eTests/category.spec.ts
  frontend/e2eTests/utils.ts
  frontend/jest.config.ts
  frontend/package.json
  frontend/playwright.config.ts
  frontend/playwright/tests/auth.setup.ts
  frontend/playwright/tests/category.actions.ts
  frontend/playwright/tests/category.spec.ts
  frontend/playwright/tests/search.actions.ts
  frontend/playwright/tests/search.spec.ts
  frontend/playwright/tests/templates.actions.ts
  frontend/playwright/tests/templates.spec.ts
  frontend/playwright/tests/utils.ts
Labels: feature, FE

#685 백엔드 CD 변경
  .github/workflows/backend_cd.yml
Labels: refactor, BE

#680 좋아요 기능 구현
  backend/src/main/java/codezap/like/controller/LikeController.java
  backend/src/main/java/codezap/likes/controller/LikesController.java
  backend/src/main/java/codezap/likes/controller/SpringDocsLikesController.java
  backend/src/main/java/codezap/likes/domain/Likes.java
  backend/src/main/java/codezap/likes/repository/LikesJpaRepository.java
  backend/src/main/java/codezap/likes/repository/LikesRepository.java
  backend/src/main/java/codezap/likes/service/LikedChecker.java
  backend/src/main/java/codezap/likes/service/LikesService.java
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
  backend/src/main/java/codezap/template/controller/TemplateController.java
  backend/src/main/java/codezap/template/domain/Template.java
  backend/src/main/java/codezap/template/dto/response/FindAllTemplateItemResponse.java
  backend/src/main/java/codezap/template/dto/response/FindTemplateResponse.java
  backend/src/main/java/codezap/template/service/facade/MemberTemplateApplicationService.java
  backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
  backend/src/main/resources/db/migration/V3__add_likes.sql
  backend/src/test/java/codezap/global/ServiceTest.java
  backend/src/test/java/codezap/likes/repository/FakeLikeRepository.java
  backend/src/test/java/codezap/likes/repository/LikesJpaRepositoryTest.java
  backend/src/test/java/codezap/likes/service/LikesServiceTest.java
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
  backend/src/test/java/codezap/template/repository/FakeTemplateRepository.java
  backend/src/test/java/codezap/template/service/TemplateServiceTest.java
  backend/src/test/java/codezap/template/service/facade/MemberTemplateApplicationServiceTest.java
  backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
Labels: feature, BE

#689 Beta 서버에서 프론트엔드 환경변수 문제 해결
  .github/workflows/frontend_cd.yml
  .github/workflows/frontend_playwright.yml
Labels: bug, FE, zap

#686 템플릿 좋아요 기능 구현
  frontend/src/api/index.ts
  frontend/src/api/like.ts
  frontend/src/api/templates.ts
  frontend/src/assets/images/index.ts
  frontend/src/assets/images/like.tsx
  frontend/src/components/LikeButton/LikeButton.style.ts
  frontend/src/components/LikeButton/LikeButton.tsx
  frontend/src/components/LikeCounter/LikeCounter.style.ts
  frontend/src/components/LikeCounter/LikeCounter.tsx
  frontend/src/components/TemplateCard/TemplateCard.tsx
  frontend/src/components/index.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/templateList.json
  frontend/src/pages/TemplatePage/TemplatePage.style.ts
  frontend/src/pages/TemplatePage/TemplatePage.tsx
  frontend/src/pages/TemplatePage/hooks/useLike.ts
  frontend/src/queries/likes/index.ts
  frontend/src/queries/likes/useDislikeMutation.ts
  frontend/src/queries/likes/useLikeMutation.ts
  frontend/src/queries/templates/useTemplateExploreQuery.ts
  frontend/src/queries/templates/useTemplateQuery.spec.tsx
  frontend/src/queries/templates/useTemplateQuery.ts
  frontend/src/routes/endPoints.ts
  frontend/src/types/api.ts
  frontend/src/types/index.ts
  frontend/src/types/template.ts
  frontend/src/utils/formatWithK.ts
  frontend/src/utils/index.ts
Labels: feature, FE, zap

#692 좋아요 기능의 응답 코드를 통일
  backend/src/main/java/codezap/likes/controller/LikesController.java
Labels: refactor, BE

#693 비회원이 좋아요 버튼 클릭 시, 로그인 안내 모달 (비회원 로그인 안내 모달 구현)
  frontend/src/components/Modal/Modal.style.ts
  frontend/src/components/NonmemberAlerter/NonmemberAlerter.tsx
  frontend/src/components/index.ts
  frontend/src/pages/TemplatePage/TemplatePage.tsx
Labels: feature, FE

#691 목록 조회 페이지 기본 값을 0으로 변경
  backend/src/main/java/codezap/template/controller/TemplateController.java
Labels: bug, BE

#702 로그인 정보를 Member 도메인으로 받도록 변경
  backend/src/main/java/codezap/likes/controller/LikesController.java
  backend/src/main/java/codezap/likes/controller/SpringDocsLikesController.java
  backend/src/main/java/codezap/likes/service/LikesService.java
  backend/src/test/java/codezap/likes/service/LikesServiceTest.java
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
Labels: bug, zap, BE

#701 RDS reader writer 적용
  backend/src/main/java/codezap/global/rds/DataSourceConfig.java
  backend/src/main/java/codezap/global/rds/DataSourceRouter.java
  backend/src/main/java/codezap/likes/service/LikesService.java
  backend/src/main/java/codezap/template/service/TemplateService.java
  backend/src/main/java/codezap/template/service/ThumbnailService.java
  backend/src/main/resources/logger/logback-spring-prod.xml
Labels: refactor, zap, BE

#657 AuthService 테스트
  backend/src/test/java/codezap/auth/service/AuthServiceTest.java
Labels: refactor, BE

#708 구경가기 페이지에 검색 추가 및 좋아요순 정렬 추가
  frontend/src/api/templates.ts
  frontend/src/pages/TemplateExplorePage/TemplateExplorePage.style.ts
  frontend/src/pages/TemplateExplorePage/TemplateExplorePage.tsx
  frontend/src/queries/templates/useTemplateExploreQuery.ts
Labels: feature, FE, zap

#698 build시 정적 리소스에 cache busting 기법 적용
  frontend/webpack.common.js
Labels: feature, FE

#714 NoSearchResults 생성 및 적용
  frontend/src/components/NoSearchResults/NoSearchResults.style.ts
  frontend/src/components/NoSearchResults/NoSearchResults.tsx
  frontend/src/components/index.ts
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
  frontend/src/pages/TemplateExplorePage/TemplateExplorePage.tsx
Labels: feature, FE, zap

#713 package.json의 version을 1.1.2로 변경
  frontend/package.json
Labels: feature, FE, zap

#703 검색 성능 개선
  backend/src/main/java/codezap/tag/repository/TemplateTagJpaRepository.java
  backend/src/main/java/codezap/tag/repository/TemplateTagRepository.java
  backend/src/main/java/codezap/tag/service/TagService.java
  backend/src/main/java/codezap/template/domain/TemplateTag.java
  backend/src/main/java/codezap/template/domain/Thumbnail.java
  backend/src/main/java/codezap/template/repository/TemplateSpecification.java
  backend/src/main/java/codezap/template/repository/ThumbnailJpaRepository.java
  backend/src/main/java/codezap/template/repository/ThumbnailRepository.java
  backend/src/main/java/codezap/template/service/ThumbnailService.java
  backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
  backend/src/test/java/codezap/tag/repository/TemplateTagJpaRepositoryTest.java
  backend/src/test/java/codezap/tag/service/TagServiceTest.java
  backend/src/test/java/codezap/template/domain/TemplateTagTest.java
  backend/src/test/java/codezap/template/domain/ThumbnailTest.java
  backend/src/test/java/codezap/template/repository/FakeTemplateTagRepository.java
  backend/src/test/java/codezap/template/repository/FakeThumbnailRepository.java
  backend/src/test/java/codezap/template/repository/ThumbnailRepositoryTest.java
  backend/src/test/java/codezap/template/service/ThumbnailServiceTest.java
Labels: refactor, BE

#706 MyTemplatePage 초기 랜더링 Layoutshift 개선
  frontend/src/components/Footer/Footer.tsx
  frontend/src/components/LoadingFallback/LoadingFallback.style.ts
  frontend/src/components/LoadingFallback/LoadingFallback.tsx
  frontend/src/components/index.ts
  frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
  frontend/src/pages/MyTemplatesPage/components/CategoryFilterMenu/CategoryFilterMenu.stories.tsx
  frontend/src/pages/MyTemplatesPage/components/CategoryFilterMenu/CategoryFilterMenu.tsx
  frontend/src/pages/MyTemplatesPage/components/TagFilterMenu/TagFilterMenu.stories.tsx
  frontend/src/pages/MyTemplatesPage/components/TagFilterMenu/TagFilterMenu.tsx
  frontend/src/pages/MyTemplatesPage/components/TemplateGrid/TemplateGrid.stories.tsx
  frontend/src/pages/MyTemplatesPage/components/TemplateGrid/TemplateGrid.tsx
  frontend/src/pages/TemplatePage/TemplatePage.tsx
  frontend/src/queries/templates/index.ts
  frontend/src/queries/templates/useTemplateCategoryTagQueries.ts
  frontend/src/routes/router.tsx
Labels: FE, refactor, zap

#717 API 서버 preconnect, 썸네일 코드에서 Gutter 제거
  frontend/public/index.html
  frontend/src/components/TemplateCard/TemplateCard.tsx
Labels: feature, FE

#704 템플릿 단건 조회/ 템플릿 삭제/ 태그 조회 성능 개선
  backend/src/main/java/codezap/category/domain/Category.java
  backend/src/main/java/codezap/likes/domain/Likes.java
  backend/src/main/java/codezap/tag/repository/TemplateTagJpaRepository.java
  backend/src/main/java/codezap/tag/repository/TemplateTagRepository.java
  backend/src/main/java/codezap/tag/service/TagService.java
  backend/src/main/java/codezap/template/repository/SourceCodeJpaRepository.java
  backend/src/main/java/codezap/template/repository/SourceCodeRepository.java
  backend/src/main/java/codezap/template/repository/ThumbnailJpaRepository.java
  backend/src/main/java/codezap/template/repository/ThumbnailRepository.java
  backend/src/main/java/codezap/template/service/SourceCodeService.java
  backend/src/main/java/codezap/template/service/ThumbnailService.java
  backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
  backend/src/main/resources/db/migration/V4__create_idx_member_id_on_category.sql
  backend/src/test/java/codezap/tag/repository/TemplateTagJpaRepositoryTest.java
  backend/src/test/java/codezap/tag/service/TagServiceTest.java
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
  backend/src/test/java/codezap/template/repository/FakeSourceCodeRepository.java
  backend/src/test/java/codezap/template/repository/FakeTemplateTagRepository.java
  backend/src/test/java/codezap/template/repository/FakeThumbnailRepository.java
  backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
  backend/src/test/java/codezap/template/repository/ThumbnailRepositoryTest.java
  backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java
Labels: refactor, BE

#715 템플릿 생성, 수정 쿼리 성능 개선
  backend/src/main/java/codezap/tag/domain/Tag.java
  backend/src/main/java/codezap/tag/repository/TagRepository.java
  backend/src/main/java/codezap/tag/service/TagService.java
  backend/src/main/java/codezap/template/domain/TemplateTag.java
  backend/src/main/resources/db/migration/V5__create_idx_tag_name.sql
  backend/src/test/java/codezap/tag/repository/TagJpaRepositoryTest.java
  backend/src/test/java/codezap/template/repository/FakeTagRepository.java
Labels: refactor, BE
