Repository woowacourse-teams/2024-code-zap, pull requests merged in 2025-01, with the labels that each got.

#997 인기 태그 목록 조회
  backend/src/main/java/codezap/tag/controller/SpringDocTagController.java
  backend/src/main/java/codezap/tag/controller/TagController.java
  backend/src/main/java/codezap/tag/repository/TagQueryDSLRepository.java
  backend/src/main/java/codezap/tag/repository/TagRepository.java
  backend/src/main/java/codezap/tag/service/TagService.java
  backend/src/test/java/codezap/global/DatabaseCleaner.java
  backend/src/test/java/codezap/tag/controller/TagControllerTest.java
  backend/src/test/java/codezap/tag/repository/TagRepositoryTest.java
  backend/src/test/java/codezap/tag/service/TagServiceTest.java
  backend/src/test/resources/top-tags.sql
Labels: feature, BE

#1006 콘솔 로그 추가
  backend/src/main/resources/logger/logback-spring-dev.xml
  backend/src/main/resources/logger/logback-spring-prod.xml
Labels: BE, infrastructure

#1004 태그 중복 생성 시 재시도 처리의 위치를 변경
  backend/src/main/java/codezap/tag/service/TagService.java
  backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
Labels: refactor, BE

#1009 gitignore에 local yml 추가
  backend/.gitignore
Labels: refactor, BE

#1011 Default yml에서 was, voc 프로파일 제거
  backend/src/main/resources/application.yml
Labels: refactor, BE

#1012 톰캣 MBean 활성화
  backend/src/main/resources/application-was.yml
Labels: BE, infrastructure

#1016 tag name 대소문자 구분으로 변경
  backend/src/main/resources/db/migration/V11__add_unique_binary_tag.sql
Labels: bug, zap, BE

#1017 [fix] tag name 대소문자 구분으로 변경
  backend/src/main/resources/db/migration/V11__add_unique_binary_tag.sql
Labels: bug, zap, BE

#981 Authorization 헤더를 응답하도록 변경
  backend/src/main/java/codezap/auth/configuration/AuthArgumentResolver.java
  backend/src/main/java/codezap/auth/configuration/AuthWebConfiguration.java
  backend/src/main/java/codezap/auth/controller/AuthController.java
  backend/src/main/java/codezap/auth/controller/SpringDocAuthController.java
  backend/src/main/java/codezap/auth/dto/LoginMember.java
  backend/src/main/java/codezap/auth/manager/AuthorizationHeaderCredentialManager.java
  backend/src/main/java/codezap/auth/manager/CookieCredentialManager.java
  backend/src/main/java/codezap/auth/manager/CredentialManager.java
  backend/src/main/java/codezap/auth/provider/CredentialProvider.java
  backend/src/main/java/codezap/auth/provider/basic/BasicAuthCredentialProvider.java
  backend/src/main/java/codezap/auth/service/AuthService.java
  backend/src/test/java/codezap/auth/configuration/AuthArgumentResolverTest.java
Labels: refactor, BE

#988 카테고리 순서 변경
  backend/src/main/java/codezap/category/controller/CategoryController.java
  backend/src/main/java/codezap/category/controller/SpringDocCategoryController.java
  backend/src/main/java/codezap/category/domain/Category.java
  backend/src/main/java/codezap/category/dto/request/CreateCategoryRequest.java
  backend/src/main/java/codezap/category/dto/request/UpdateAllCategoriesRequest.java
  backend/src/main/java/codezap/category/dto/request/UpdateCategoryRequest.java
  backend/src/main/java/codezap/category/dto/request/validation/DuplicateId.java
  backend/src/main/java/codezap/category/dto/request/validation/DuplicateIdValidator.java
  backend/src/main/java/codezap/category/dto/request/validation/DuplicateName.java
  backend/src/main/java/codezap/category/dto/request/validation/DuplicateNameValidator.java
  backend/src/main/java/codezap/category/dto/request/validation/ValidatedDuplicateIdRequest.java
  backend/src/main/java/codezap/category/dto/request/validation/ValidatedDuplicateNameRequest.java
  backend/src/main/java/codezap/category/dto/response/CreateCategoryResponse.java
  backend/src/main/java/codezap/category/dto/response/FindCategoryResponse.java
  backend/src/main/java/codezap/category/repository/CategoryJpaRepository.java
  backend/src/main/java/codezap/category/repository/CategoryRepository.java
  backend/src/main/java/codezap/category/service/CategoryService.java
  backend/src/main/java/codezap/category/service/CategoryValidationService.java
  backend/src/main/java/codezap/global/validation/Ordinal.java
  backend/src/main/java/codezap/global/validation/OrdinalValidator.java
  backend/src/main/java/codezap/global/validation/ValidatedOrdinalRequest.java
  backend/src/main/java/codezap/global/validation/ValidationGroups.java
  backend/src/main/java/codezap/global/validation/ValidationSequence.java
  backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
  backend/src/main/java/codezap/template/dto/request/CreateTemplateRequest.java
  backend/src/main/java/codezap/template/dto/request/UpdateTemplateRequest.java
  backend/src/main/java/codezap/template/dto/request/validation/SourceCodesOrdinalValidator.java
  backend/src/main/java/codezap/template/dto/request/validation/ValidatedSourceCodesOrdinalRequest.java
  backend/src/main/java/codezap/template/service/SourceCodeService.java
  backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
  backend/src/main/resources/db/migration/V12__add_category_ordinal.sql
  backend/src/test/java/codezap/auth/provider/basic/BasicAuthCredentialProviderTest.java
  backend/src/test/java/codezap/auth/service/AuthServiceTest.java
  backend/src/test/java/codezap/category/controller/CategoryControllerTest.java
  backend/src/test/java/codezap/category/repository/CategoryRepositoryTest.java
  backend/src/test/java/codezap/category/service/CategoryServiceTest.java
  backend/src/test/java/codezap/fixture/CategoryFixture.java
  backend/src/test/java/codezap/fixture/MemberFixture.java
  backend/src/test/java/codezap/global/MockMvcTest.java
  backend/src/test/java/codezap/member/controller/MemberControllerTest.java
  backend/src/test/java/codezap/member/domain/MemberTest.java
  backend/src/test/java/codezap/member/fixture/MemberFixture.java
  backend/src/test/java/codezap/member/service/MemberServiceTest.java
  backend/src/test/java/codezap/tag/service/TagServiceTest.java
  backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
  backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java
  backend/src/test/resources/search.sql
  backend/src/test/resources/top-tags.sql
Labels: feature, BE

#1013 프론트엔드 github actions CD 스크립트
  .github/workflows/frontend_cd.yml
Labels: feature, FE

#1024 ordinal 컬럼 생성 시 멤버별로 순서대로 ordinal 설정
  backend/src/main/resources/db/migration/V12__add_category_ordinal.sql
Labels: bug, BE

#1026 요청 헤더에 Authorization 필드 추가
  frontend/src/api/ApiClient.ts
  frontend/src/api/authentication.ts
  frontend/src/api/config.ts
  frontend/src/queries/authentication/useLoginMutation.ts
  frontend/src/queries/authentication/useLogoutMutation.ts
Labels: FE, refactor

#1028 QueryDSL 버전 업그레이드
  backend/build.gradle
Labels: refactor, BE

#1027 Category(member, ordinal) 유니크 제약 조건 삭제
  backend/src/main/java/codezap/category/domain/Category.java
  backend/src/main/java/codezap/category/repository/CategoryJpaRepository.java
  backend/src/main/java/codezap/category/repository/CategoryRepository.java
  backend/src/main/java/codezap/category/service/CategoryService.java
  backend/src/main/resources/db/migration/V13__drop_contraint_ordinal_member.sql
  backend/src/test/java/codezap/category/service/CategoryServiceTest.java
Labels: bug, BE

#1034 Authorization 토큰 사용 시, Credential-type 헤더 추가
  frontend/src/api/ApiClient.ts
Labels: feature, FE

#1025 깃허브 OAuth 문서 생성
  backend/src/main/java/codezap/auth/controller/OAuthController.java
  backend/src/main/java/codezap/auth/controller/SpringDocOAuthController.java
  backend/src/main/java/codezap/auth/dto/request/OAuthSignupRequest.java
  backend/src/main/java/codezap/auth/dto/request/OAuthUniqueCheckRequest.java
  backend/src/main/java/codezap/auth/dto/response/OAuthUniqueCheckResponse.java
  backend/src/main/java/codezap/member/controller/SpringDocMemberController.java
Labels: documentation, BE

#1040 /login/check API의 응답 형식 변경
  backend/src/main/java/codezap/auth/controller/AuthController.java
  backend/src/main/java/codezap/auth/controller/SpringDocAuthController.java
  backend/src/main/java/codezap/auth/dto/response/CheckLoginResponse.java
Labels: documentation, BE
